components/d2l-activity-list-item/d2l-activity-list-item-enroll.js
components/d2l-activity-list-item/d2l-activity-list-item.js
demo/d2l-activity-list-item/index.html

Update the behaviour of the activity list item for hover and focus.
A/C:
- A item is able to have focus and hover in AND/OR combinations
A user can have focused on a search result item with the keyboard and hover with the mouse on another (AKA don't move focus due to the user's hovering)
- When normal, the top item doesn't have a top border. When focused/hovered, it does
Ensure that the layout doesn't change due to hover/focus
- When the cursor is in the "bounds" of the search result, the hover effect is activated
NOT just on the link
The background of the list item changes to #F9FAFB on hover
The link appears underlined when hovered

Hover and Focus for list item.

---

components/d2l-activity-list-item/d2l-activity-list-item.js

This makes more sense when actually using the element.

Switch from actionEnrollHide to actionEnrollShow.

---

components/d2l-evaluation-hub-activities-list/d2l-evaluation-hub-activities-list.js

Weirdly this was exposing a bug in Babel when transpiled, which resulted in a JS error in IE11.

optimizing as this was tripping up Babel and failing in IE11

---

README.md
components/d2l-evaluation-hub-activities-list/d2l-evaluation-hub-activities-list.js
demo/d2l-evaluation-hub/data/activities/activitiesList/root.json
demo/d2l-evaluation-hub/data/activities/activitiesList/whoami.json
demo/d2l-evaluation-hub/index.html
test/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
test/d2l-evaluation-hub/data/root.json
test/d2l-evaluation-hub/data/whoami.json

Also simplified some Promises to async/await for readability, added some null checks, rewrote `followLink()` to use `getHref()`.

hypermedia calls can start directly from https://activities.api.prodev.d2l/my-unassessed-activities, don't have to go through root.

---

components/d2l-activity-list-item/d2l-activity-list-item.js

I talked to Colin about this and his suggestion was to remove the max width constraint in the component and impose a max width constraint in the containers that use the component.
Any concerns with removing this max width?

Remove the max width constraint for d2l-activity-list-item

---

components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
test/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js

This is something filter and sorting is going to need, so trying to help pave the way for those.  Now, `_loadMore` will concat data and add to the table, but the initial load and changes to the href will just call `_loadData` which replaces the table (and shows a loading spinner over the whole table as that is fetched). 
Sorting and filtering should use the `_loadData` function.

Add data concatenation just to Load More

---

components/d2l-activity-list-item/d2l-activity-list-item.js
test/d2l-activity-list-item/d2l-activity-list-item-test.js

This seems to fix the issue of firing the event too early before the element is stamped (I experienced this in a dom-repeat situation).
`d2l-course-image` does this as well.
Any issues that anyone can think of?

Fire the d2l-activity-text-loaded event after next render.

---

components/d2l-activity-evaluation-icon/d2l-activity-evaluation-icon-base.js
demo/d2l-activity-evaluation-icon/d2l-activity-evaluation-icon-base.html
demo/index.html
test/d2l-activity-evaluation-icon/d2l-activity-evaluation-icon-base.html
test/d2l-activity-evaluation-icon/d2l-activity-evaluation-icon-base.js
test/index.html

* Adding base component to display the draft icon when needed
* Next PR will look into adding the tool tip
* FYI some tests fail locally, does this happen for anyone else?
* For test "Setting the href attributeshould sned text loaded event
```
Error: done() called multiple times
forEach.testCase at d2l-activity-list-item-test.js:121
Suite.describe at d2l-activity-list-item-test.js:96
wrappedMochaFunction at /components/wct-browser-legacy/browser.js:2028
<unknown> at d2l-activity-list-item-test.js:2
```

US103573 - Simple base component that displays draft icon

---

demo/d2l-evaluation-hub/demo-data-parser.js

No spread operator (`...`) so I took it out. Then I had a hard time making `Set` work before I realized ie11 only partially supports `Set`. I couldn't figure out how to turn a `Set` into an array for ie11 so I just hacked something together.

Refactor to make ie11 work

---

components/d2l-activity-name/d2l-activity-name.js
components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
demo/d2l-evaluation-hub/table.js

As per design discussion, we are only adding truncate and nowrap for ActivityName (which already has it) and CourseName.
- First cut at truncate and no wrap for course name
- Specify padding for activity name
This is as small as the ActivityName and CourseName columns would get:

US104170 - truncate + nowrap for CourseName

---

components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js

* Manage sort state through internal variable rather than html attributes
* Reason we do this is because we want to load sort state on load, but there are race conditions when it comes to when the `dom-if`s render
* By managing sort state internally, we can guarantee it will be reflected properly on the page, previously the view and data state were tied together too tightly
* This is a refactor to support loading sort state on initial load, not new functional changes expected here

US104761 - Manage sort state through Internal Variables

---

components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
demo/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.html
demo/d2l-evaluation-hub/d2l-evaluation-hub.html

* Demo now shows sort state on initial load. I use `?sort=bydate-a` in demo data. LMS will need to be configured to use this sort by default as well.
* Demo will work correctly after https://github.com/BrightspaceHypermediaComponents/activities/pull/89

US104761 - Load sort state on load

---

components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js

* Draft icon seemed too close to name
* I used same spacing as in https://github.com/BrightspaceHypermediaComponents/activities/pull/74
Unsure why RTL looks weird for activity. Probably because everything is still left justified, I'm not sure what is normal for RTL case

Add padding for draft icon

---

components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js

This is coming up in a Firefox test a lot making it flaky.  The change itself is good anyways.

Only try to focus if the new element exists

---

components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
test/d2l-evaluation-hub/d2l-evaluation-hub-activities-list-sorting.js

This fixes `If I click between the columns too quickly, the UI will show multiple sort arrows at the same time`
There will be a follow up PR to add a test and fix the tests I gutted.
I've manually tested this change and it appears to work. You can reliably trigger the double sort arrows by spam clicking the same column a few times and then quickly spam clicking another column a few times. But after my change, you won't be able to get it to happen.

Reset all non primary headers to unsorted on load

---

package.json

Should be a one time thing.
In future this bump will happen as part of the PR with the changes (as per my suggested readme changes):
https://d2l.slack.com/archives/CBTK3JB6D/p1553084666352400

bump version number to 2.0.0

---

components/d2l-quick-eval/d2l-quick-eval-activities-list.js
test/d2l-quick-eval/d2l-quick-eval-activities-list.js

**Note:** Demo only works after https://github.com/BrightspaceHypermediaComponents/activities/pull/124
* Retain number of activities shown when sorting

US104726 - Retain number of shown activities on sort

---

.eslintrc.json
components/d2l-activity-evaluation-icon/d2l-activity-evaluation-icon.js
components/d2l-activity-list-item/ActivityListItemResponsiveConstants.js
components/d2l-activity-list-item/d2l-activity-list-item.js
components/d2l-quick-eval/d2l-quick-eval-activities-list.js
demo/d2l-activity-list-item/index.html
demo/d2l-activity-name/update-direction.js
demo/d2l-quick-eval/page-handler.js
demo/d2l-quick-eval/update-direction.js
scripts/remove_attest_from_project.js

We shouldn't use `var` because it causes surprises due to it being function-scoped (vs block-scoped which is what C# developers are used to).
`const` allows developers to catch runtime errors at "compile-time"
`let` has block-scope, which many developers are used to and can avoid hard to catch bugs such as the one below (stolen from the eslint docs)
```js
var count = people.length;
var enoughFood = count > sandwiches.length;
if (enoughFood) {
var count = sandwiches.length; // accidentally overriding the count variable
console.log("We have " + count + " sandwiches for everyone. Plenty for all!");
}
// our count variable is no longer accurate
console.log("We have " + count + " people and " + sandwiches.length + " sandwiches!");
```
Some environments don't fully support it but I think we are …

Enforce usage of `const`/`let` over `var`

---

components/d2l-quick-eval/d2l-quick-eval-activities-list.js
test/d2l-quick-eval/d2l-quick-eval-activities-list.js

* This is prep work for filters to try and maintain the number of activities to show
* This is needed because filters may reduce the number of activities shown, and I don't think we ever want to reduce the number of activities shown if we can avoid it

US105524 - Computed number of activities to show should never go down

---

components/d2l-quick-eval/d2l-quick-eval-activities-list.js
components/d2l-quick-eval/d2l-quick-eval.js
test/d2l-quick-eval/d2l-quick-eval-activities-list-sorting.js
test/d2l-quick-eval/d2l-quick-eval-activities-list.js
test/d2l-quick-eval/d2l-quick-eval.html

* Anytime `_numberOfActivitiesToShow` is updated in quick-eval-activities-list, we fire that event
* quick-eval listens for that event, and tells the filter component, "next time you request for activities, try to give me X amount"
* this way the number of activities should persist as best as possible through sort and filter
* Tested in LMS seems to be working fine
* Requires changes from https://github.com/BrightspaceHypermediaComponents/common/pull/19 to work

US105524 - Maintain number of activities shown when filters are modified

---

components/d2l-quick-eval/d2l-quick-eval-activities-list.js

* Noticed aria-label wasn't used when using activities-list within quick-eval
* This should fix it

US105617 - Use attribute variable 

---

components/d2l-quick-eval/d2l-quick-eval.js

The summary container should be 18px below the `d2l-hm-search`, and 54px above the headers in the activities list.

Fixing margins.

---

components/d2l-quick-eval/d2l-quick-eval.js

Before change: 
-
After change:
-
To verify distance between elements (should be 5):
```
var t = document.querySelector('d2l-quick-eval').shadowRoot.querySelector('d2l-hm-filter').getBoundingClientRect();
var u = document.querySelector('d2l-quick-eval').shadowRoot.querySelector('d2l-hm-search').getBoundingClientRect();
u.left - t.right
```

Moving filter dropdown closer to search (was 40px, now 5px).

---

components/d2l-quick-eval/compatability/universal-methods.js
components/d2l-quick-eval/d2l-quick-eval-activities-list.js
test/d2l-quick-eval/compatability/universal-methods.js

* QE component should now be comptable with IE11
* Filtering still doesn't work
* Reason why QE actions will still not work in IE11 is because of https://github.com/Brightspace/polymer-siren-behaviors/issues/41 but this is a platform issue not a QE issue

DE33386 - Remove all usages for url.searchParams

---

components/d2l-quick-eval/d2l-quick-eval.js

Filter/search should still be on the right and bottom when screen is wide enough:
They will wrap together when the width decreases:
And they will wrap separately when the width decreases even further:

Using flex to allow line wrapping.

---

components/d2l-activity-list-item/d2l-activity-list-item.js

Story: https://rally1.rallydev.com/#/39602890252d/detail/userstory/299905420308
I've mainly tested in Chrome, IE11, and Edge in Windows using NVDA. Tested in Chrome and Safari on MAC using VoiceOver.
Adding the aria-label allows chrome to announce the link with the accessibility text properly. Previously Chrome announced "link 123456" where 123456 is the end of the link (e.g. "leinstance.com/d2l/le/discovery/view/course/123456").
Keeping the span within the link tag allows Edge to announce the link properly. Removing the span will make Edge announce "blank" when selecting the item. The aria-label doesn't seem to do anything here in edge.
IE11 didn't need either of these changes.
H1 was added to the link tag to make it appear in heading rotors. It'll also appear in link rotors. (Tested …

Combine the header into the link for screen reader.

---

components/d2l-quick-eval/behaviors/d2l-hm-sort-behaviour.js
components/d2l-quick-eval/behaviors/d2l-quick-eval-siren-helper-behavior.js
components/d2l-quick-eval/d2l-quick-eval-activities-list.js

The first of many.
This PR just extracts the 3 sorting methods and drops them in a behaviour. My approach to this refactor is to move as much functionality out of d2l-quick-eval-activities-list to reduce the diff in further PRs and to make it easier to extract the core hm functionality.
Next PR: cleaning up the interface between d2l-hm-sort-behaviour and d2l-quick-eval-activities-list and separating the sorting tests from the d2l-quick-eval-activities-list tests

US106353 - extract sorting

---

components/d2l-quick-eval/behaviors/d2l-hm-sort-behaviour.js
components/d2l-quick-eval/d2l-quick-eval-activities-list.js
demo/d2l-quick-eval/d2l-quick-eval-activities-list.html
test/d2l-quick-eval/d2l-quick-eval-activities-list-sorting.js

Previous PR: https://github.com/BrightspaceHypermediaComponents/activities/pull/190
This PR: Tried to get the quick-eval specific things into `list` and keep the generic sorting stuff in the behaviour. I originally tried to have a complete sorting solution, but I couldn't figure out a good way to bind the sort headers to the sort behaviour. In the interest of time, I went with this smaller refactor.
Next PR: Going to create a new layer, `d2l-quick-eval-submission` that will serve as the controller for the submissions view. The new hierarchy will be `d2l-quick-eval` > `d2l-quick-eval-submission` > `d2l-quick-eval-activities-list`

US106353 - clean up sorting interface

---

components/d2l-activity-card/d2l-activity-card.js
components/d2l-activity-list-item/d2l-activity-list-item.js

d2l-activity-list-item: add support for styles for RTL and also reverse tags order in RTL.
d2l-activity-card: remove a right margin that's too small to notice anyway (0.05rem/1px) so that left and right margin are the same. No changes needed for RTL after this.

Changes for RTL support for d2l-activity-list-item and d2l-activity-card

---

components/d2l-quick-eval/behaviors/d2l-hm-sort-behaviour.js
components/d2l-quick-eval/d2l-quick-eval-activities-list.js
test/d2l-quick-eval/d2l-quick-eval-activities-list-sorting.js

Previous PR: https://github.com/BrightspaceHypermediaComponents/activities/pull/195
This PR: I noticed `d2l-hm-sort-behaviour` still had a dependency on `d2l-quick-eval-activities-list`, namely `_dispatchSortUpdatedEvent`. I moved that last bit over to `list`. The test change reflects this - `_applySortAndFetchData` is no longer coupled with `list` so it won't make the `list` callbacks.
Next PR: Going to create a new layer, `d2l-quick-eval-submission` that will serve as the controller for the submissions view. The new hierarchy will be `d2l-quick-eval` > `d2l-quick-eval-submission` > `d2l-quick-eval-activities-list`

US106353 - clean up sorting interface pt 2

---

components/d2l-quick-eval/d2l-quick-eval-submissions.js
components/d2l-quick-eval/d2l-quick-eval.js
test/d2l-quick-eval/d2l-quick-eval.html

Previous PR: https://github.com/BrightspaceHypermediaComponents/activities/pull/196
This PR: Adding a middle class called `d2l-quick-eval-submissions` that right now does nothing. This will be the controller for the submissions portion of the application. The plan is to slowly move functionality from above (quick-eval) and below (quick-eval-activities-list) until this follows the flux pattern.
Next PR: Since Josh is doing some search/filter stuff, I'm going to focus on moving things up from `list` next.

US106353 - add submissions controller

---

components/d2l-quick-eval/behaviors/d2l-hm-sort-behaviour.js
components/d2l-quick-eval/d2l-quick-eval-activities-list.js
test/d2l-quick-eval/d2l-quick-eval-activities-list-sorting.js

Previous PR: https://github.com/BrightspaceHypermediaComponents/activities/pull/198
This PR: Just noticed one last list-specific thing in sort that should be moved to the outside
Next PR: Since Josh is doing some search/filter stuff, I'm going to focus on moving things up from `list` next.

US106353 - move last bit of list-specific code out of sort

---

components/d2l-activity-card/d2l-activity-card.js
components/d2l-activity-list-item/d2l-activity-list-item.js
package.json

The store doesn't work nicely with the way I allowed embedded HM entities to be added. The siren-sdk will fix this issue! So YAY!
The issue that was caused was because the href was changed when adding the entity that entity would be fetched again. This would cause a fetch call to our outside service and fail it since there was too many.  Eek.
So this PR is here to fix this for cert and isn't a long term fix.

Remove store from activities.

---

components/d2l-quick-eval/d2l-quick-eval-activities-list.js
components/d2l-quick-eval/d2l-quick-eval-submissions.js
components/d2l-quick-eval/d2l-quick-eval.js
test/d2l-quick-eval/d2l-quick-eval-activities-list.js
test/d2l-quick-eval/d2l-quick-eval-submissions.html
test/d2l-quick-eval/d2l-quick-eval-submissions.js
test/index.html

This change is larger than I wanted it to be but I had lots of trouble decoupling the loading from the rest of the application. In the end, this change is:
* I moved all the entity things into `submissions` and now `submissions` passes `_data` into `list`
* Effectively that means moving `_loadData`, `_loadMore`, and `_parseActivities` up one level
* `list` now emits a `load-more` event which the controller listens for
* sorting still lives in `list` (for now) but it is triggered by the controller (see `_handleSorts`). Sorted data is emitted via events and listened to by the controller. (This will change in the next PR)
* I didn't modify any of the functions except when we acquired things via `querySelector` I just changed it to look in the correct shadowDom
* The change is to make …

US106353 - move loading to controller

---

components/d2l-quick-eval/behaviors/d2l-quick-eval-siren-helper-behavior.js
components/d2l-quick-eval/d2l-quick-eval-activities-list.js
components/d2l-quick-eval/d2l-quick-eval-submissions.js
components/d2l-quick-eval/d2l-quick-eval.js
test/d2l-quick-eval/d2l-quick-eval-activities-list-sorting.html
test/d2l-quick-eval/d2l-quick-eval-activities-list-sorting.js
test/d2l-quick-eval/d2l-quick-eval-activities-list.js
test/d2l-quick-eval/d2l-quick-eval-submissions.js
test/d2l-quick-eval/d2l-quick-eval.html

Builds off of https://github.com/BrightspaceHypermediaComponents/activities/pull/204
In this PR I made `d2l-quick-eval-activities-list.js` no longer extend `D2LQuickEvalSirenHelperBehavior` and `D2LHMSortBehaviour`, effectively removing all the controller code from `d2l-quick-eval-activities-list.js`. There's still some weirdness in the interface where `list` makes decisions, but I'm pretty happy with the current state of `list` now.
* Remove siren/sort behaviours from `list`
* Move `_handleSorts` and `_sortClickHandler` to the controller
* Now we have to emit an event, `d2l-quick-eval-submissions-table-sort-requested`, when the sort button is pressed and the controller handles it
* This also means that the source of truth for `_headerColumns` needs to be in the controller
* Remove list …

US106353 - move sorting to controller

---

components/d2l-quick-eval/d2l-quick-eval-submissions-table.js
components/d2l-quick-eval/d2l-quick-eval-submissions.js

Doing some small cleanup before I add the filter/search behaviour.
In this case, deleting some cruft in the-element-formerly-known-as-list (let's just call it `table` now).
`table` used to care about `filterHref` back when it made decisions but it's no longer used now.

Delete filterHref in preparation for adding filter behaviour

---

components/d2l-quick-eval/d2l-quick-eval-submissions-table.js

It probably made sense when we made it, but now it's just a function that replaces basic functionality (namely, `.`)
Killing it with fire!

 Get rid of complicated _getDataProperty

---

components/d2l-quick-eval/d2l-quick-eval-submissions-table.js
components/d2l-quick-eval/d2l-quick-eval-submissions.js

Further cleanup before sort/filter behaviours. Let's get loading into the controller (move decision making out of `table`).
This change also contains what I would consider a bugfix around loading. We weren't setting the load states before sending the sort request so you would see some weird data, then the loading screen would flash (during the time it takes to parse the new data), then you'd see your sorted data. This change just turns the loading screen on before we send the sort request (as you'd expect).
Previously:
1. Click sort header to sort, send sort request
2. See some wonky rearranged data
3. Data is received
4. Loading screen flashes on then off
5. Sorted data is displayed
This PR:
1. Click sort header to sort, send sort request
2. Loading screen appears
3. Data is received
4. …

Move loading to controller

---

components/d2l-quick-eval/d2l-quick-eval-submissions-table.js
components/d2l-quick-eval/d2l-quick-eval-submissions.js
test/d2l-quick-eval/d2l-quick-eval-submissions-table.js

Moving more decision making to the controller part 3. `table` should just be told what the health is, rather than keep track of it itself.

Move health into controller

---

components/d2l-quick-eval/d2l-quick-eval-submissions.js

I'm preferring the pattern of passing information to children via attributes, rather than searching the DOM for the element and calling functions on it directly

Clean up usages of `list` in submissions controller

---

components/d2l-quick-eval/d2l-quick-eval-submissions-table.js
components/d2l-quick-eval/d2l-quick-eval-submissions.js
test/d2l-quick-eval/d2l-quick-eval-submissions-table.js

This PR originally came from this comment (I was hoping we didn't have to do it but it makes sense to do it now): https://github.com/BrightspaceHypermediaComponents/activities/pull/218#discussion_r291725739
I got halfway through adding the filter/search behaviours but I encountered a problem around loading, specifically the default values. The default value for `_loading` is `true`, we assume the initial state will be to fetch the data. However the initial value for `filtersLoading` and `searchLoading` is `false`, because at first we are neither filtering or searching. But since they share a single loading state, `_loading`, there's no good way to differentiate "on the first load" and while it could be bandaided with more loading booleans, it felt like we were heading down the wrong …

Refactor loading to prepare for behaviours

---

components/d2l-quick-eval/compatability/ie11shims.js
test/d2l-quick-eval/compatability/ie11shims.js

> I believe this should be correct. Query params should always be encoded. So if we see a + symbol we know it should be a space. To actually represent a plus symbol it should be represented as %2B.
>We receive a + symbol instead of %20 is because of http://search.dev.d2l/source/xref/Lms/lp/framework/core/D2L/LP/Text/Html/UrlUtility.cs#125
Related:
* https://github.com/BrightspaceHypermediaComponents/common/pull/27
We should fix the polymer behavior at some point instead of maintaining these hacks in three places. Same fix follows here as the related PRs above

DE34932 - Treat plus as space

---

components/d2l-quick-eval/behaviors/d2l-hm-filter-behavior.js

A bug was introduced by #226 in regression, where an error message appears while loading. 
The reason this kept happening was that in #226, the `filterError` property type was changed from a boolean to an object, without a default value. The default value `filterError` is then initialized to undefined. This then breaks the view in `components/d2l-quick-eval/d2l-quick-eval-submissions.js` line 73, where `hidden$="[[!filterError]]"` evaluates to `false` when `filterError` is `undefined`  but `true` when `filterError` is `null`. The most likely explanation of this is that Polymer is known to misbehave when a property is `undefined` (see https://github.com/Polymer/polymer/issues/1813). There are a number of fixes for this (e.g. changing the template, changing `filterError` back to a boolean, …

Fix for US108137: Setting initial filterError value to null

---

components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card-items.js
components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card-unread-submissions.js
components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js

Looking ahead at the responsive layouts, it will be easier if this section and its styling is in its own component, since it moves around and changes.
Also updated the action buttons with the new icons.
There should be no visual change to the # of unread section:

Separating unread items into its own component.

---

components/d2l-quick-eval/d2l-quick-eval-view-toggle.js

So this is an image of the switcher in its default state:
And here it is when hovered:
Also the designers wanted to make the switcher look identical to the ones on the calendar page, so I attached a photo below:

Us107663 toggle styling

---

components/d2l-quick-eval/d2l-quick-eval-activities.js

Causing errors in console. Don't think the line is needed. Let me know if I'm missing something

Remove unneeded line

---

components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js
test/d2l-quick-eval/d2l-quick-eval-activity-card.js

[US108296](https://rally1.rallydev.com/#/detail/userstory/318899088768?fdp=true)
Here is a screenshot of two activity cards using data from Quad, one without a due date, one with:

Format date using the same method as submissions view

---

components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js

https://rally1.rallydev.com/#/238990806412d/detail/userstory/322170814228
Problem: Design does not want the hover state to occur when an activity card is clicked
Solution: Remove feature from code
I tested tabbing through and it still behaves the same way. I apologize for the whitespace diff. Atom is pretty strict about hanging spaces and I missed it in the diff. Hopefully doesn't cause a merge conflict for anyone.

Remove click to force hover state

---

components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card-items.js
components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js

on chrome
on firefox:
and safari:

made sure that the meters look the same on all browsers

---

components/d2l-quick-eval/d2l-quick-eval-activities.js
components/d2l-quick-eval/d2l-quick-eval-submissions.js
components/d2l-quick-eval/d2l-quick-eval-view-toggle.js
components/d2l-quick-eval/d2l-quick-eval.js

Fixes some of the issues noted in testing.
this is what it looks like in in RTL:
and this is what it looks like when the submissions is tabbed (You can barely see a difference):

robust switcher rtl styling and tabbing support

---

components/d2l-quick-eval/activities-list/d2l-quick-eval-activities-list.js
components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js
demo/d2l-quick-eval/d2l-quick-eval-activity-card.html

Adding the responsive css to the activities list - vertical spacing and course name size.
900px+:
525-899px:
524px-:
Also included a change to the activity card demo as the property name changed.

Adding responsive layout to activities list.

---

components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js

This PR is only to update the svg to look like that provided by design. New click behaviours are not covered. Hover behaviour (indicators switch on hover) should be retained.
New indicators:
Received LGTM from Erin.

Updating svg with new version from design.

---

components/d2l-quick-eval/d2l-quick-eval-activities.js

**Before:**
**After:**
Note: Same change applies for "No results here" message too.

add missing class

---

components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js

Dropping in the new action buttons into the activity card. Verified that click handlers (`_dispatchViewSubmissionListEvent` and `_dispatchPublishAllEvent`) still get fired on click.

Using new action button in activity card.

---

components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card-action-button.js
demo/d2l-quick-eval/d2l-quick-eval-activity-card-action-button.html

Disabled button in the middle, looks the same in all three states (default, hovered, focused).

Adding disabled styling to action button.

---

components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js

Should look exactly the same, but now the screen reader can tab through it, which i was able to do successfully.

Added a wrapper for activity-name

---

components/d2l-quick-eval/behaviors/d2l-quick-eval-siren-helper-behavior.js
components/d2l-quick-eval/d2l-quick-eval-activities.js

Problem: After clicking publish all, the activity view displays incorrect information about the evaluation status
Solution: Update the activity view to display current data

US108701 - update count after publish all

---

components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js

Problem: the publish all button is always enabled, but only certain activity types and permission sets allow it
Solution: disable the publish all button if the api does not allow it

US109177 - disable publish all button if api does not allow it

---

components/d2l-quick-eval/d2l-quick-eval-activities.js

Problem: users desire confirmation after taking actions
Solution: display a toast message after a successful publish all action
This PR does not contain langterms. Also, it does not fully cover the requirements - the requirements are to put the activity name in the toast as well as the message. As I mentioned in standup this morning, I want to merge this thin slice, followed by the activity name in the toast, and then lastly with langterms. Doing it this way will allow us to test the lion's share of the functionality before adding the complexity of langterms/activity name.

US109172 - show toast after successful publish all

---

components/d2l-quick-eval/behaviors/d2l-hm-filter-behavior.js
components/d2l-quick-eval/behaviors/d2l-hm-search-behavior.js
components/d2l-quick-eval/d2l-quick-eval-activities.js
components/d2l-quick-eval/d2l-quick-eval-submissions.js

Should clear search and filter when switching toggles from submissions to activities and vice-versa.

clears options and searches on hidden

---

components/d2l-quick-eval/activities-list/d2l-quick-eval-activities-list.js
components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card-action-button.js
components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js
components/d2l-quick-eval/behaviors/d2l-quick-eval-siren-helper-behavior.js
components/d2l-quick-eval/build/lang/en.js
components/d2l-quick-eval/d2l-quick-eval-activities.js
components/d2l-quick-eval/lang/en.json

I'm pushing this on behalf of Carol who is locked out of her GitHub account for now. Her comments:
Okay, so these are the design requirements that I'm attempting to fulfill with this PR:
State A is showing the action buttons and having the indicator aria-pressed="true" with the bottom circle filled in. State B is showing the speedometers and having the indicator aria-pressed="false" with the top circle filled in and none of the action buttons focused.
1. On hover enter, State A. If any other cards are in state A, change them to state B.
2. On hover leave, clear focus if it's inside the card just left and change to state B.
3. On tab/focus enter, state A
4. On tab/focus leave, state A if hover is still within the card, otherwise state B.
5. Clicking on the indicator button will toggle …

US108655 - wire up two dots

---

components/d2l-quick-eval/behaviors/d2l-quick-eval-siren-helper-behavior.js
components/d2l-quick-eval/d2l-quick-eval-activities.js

After applying filters to activities view and clicking evaluate-all or evaluate-new, clicking to `back to quick eval` should persist the filters that we originally had. I am simply leveraging functionality that already existed in submissions view.
things to keep in mind:
When clicking `back to quick eval` theres a bug that applies the filters to both submissions and acitivities views. Would appreciate some ideas over how to proceed in fixing it (probably in a separate PR).

added extra params to evaluate all and evaluate new buttons

---

components/d2l-quick-eval/d2l-quick-eval-activities.js
components/d2l-quick-eval/d2l-quick-eval-submissions.js

This allows that when the toggle is pressed, both submissions and activities are cleared. This is my attempt to solve the bug where clicking `back to quick eval` applies filters on both. This fixes the aforementioned bug.

clear both views on toggle change

---

components/d2l-quick-eval/d2l-quick-eval-submissions.js

There's now 42px of space below the submissions, because otherwise if the last submission has a tooltip, it will look weird.

added margin-bottom to submissions table

---

components/d2l-quick-eval/d2l-quick-eval-activities.js
demo/d2l-quick-eval/d2l-quick-eval-activities.html

If there are any `reject`ions inside a `Promise.all`, the entire thing is rejected. Wrapping each activity in a try/catch so that we still load all the 'good' activities instead of returning an empty array, and logging the error.

Adding try/catch if loading an activity fails.

---

components/d2l-quick-eval/d2l-quick-eval.js

This PR contains 2 changes:
1. when `activitiesViewEnabled` is set to `false`, we set `d2l-quick-eval-activities` `href` to empty string. [This causes the entitybehavior to not request the href](https://github.com/Brightspace/polymer-siren-behaviors/blob/9bc765ab8f130a980fd7d947f7925c2eea5bd2f4/store/entity-behavior.js#L70) since it will 404 anyways. This is from https://d2l.slack.com/archives/CBTK3JB6D/p1566491095322300
2. Cleanup of some old code that is no longer necessary (the LMS sends `submissionHref` now instead of `href`)

Dont request activities data when activities view is disabled

---

components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card-action-button.js

Before:
After:
tested in edge, chrome, firefox and safari on both windows and mac

fix to prevent button cutoff on safari

---

.travis.yml
README.md
package.json

1. Add auto-versioning using `frau-ci` with the default behavior being to bump the patch version if no increment tag is specified in the commit.
1. Add automatic release creation
1. Update the `package.json` version to be consistent with the current release version.

Add auto-versioning and release generation

---

components/d2l-quick-eval/d2l-quick-eval-view-toggle.js

Fix the low contrast when the button is selected and in focus/hover states (button background color and the border), see new design from here https://rally1.rallydev.com/#/15545167705d/detail/defect/328634861272.

DE35611-fix low contrast issue from the new design

---

components/d2l-quick-eval/d2l-quick-eval-view-toggle.js

No visual change. Verified that NVDA announces the difference between pressed and not pressed.

Setting aria-pressed to string.

---

components/d2l-quick-eval/activities-list/d2l-quick-eval-activities-list.js
components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card-items.js
components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card-unread-submissions.js
components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js
components/d2l-quick-eval/d2l-quick-eval-activities.js
components/d2l-quick-eval/d2l-quick-eval-search-results-summary-container.js
components/d2l-quick-eval/d2l-quick-eval-submissions-table.js
components/d2l-quick-eval/d2l-quick-eval-submissions.js
components/d2l-quick-eval/d2l-quick-eval-view-toggle.js
components/d2l-quick-eval/d2l-quick-eval.js

Lockhart hit list: `Web Components - Static “is” is no longer needed (Slide 21)`

No more static is

---

components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card-items.js
components/d2l-quick-eval/d2l-quick-eval-search-results-summary-container.js
components/d2l-quick-eval/d2l-quick-eval-submissions-table.js

This crosses off 2 Lockhart items (one of which is really small):
`Templates - Avoid Unnecessary DOM Nodes (Slide 18)` - majority of this PR
`Templates - Boolean attributes (Slide 16)` - one line, since I didn't find any other outstanding instances of this.
Again, this is a no-op change - I played around with it on the demo page with Quad data and it looks the same as before :) I would appreciate a verify of this - thanks!

Remove unneeded DOM nodes and style the :host instead

---

components/d2l-quick-eval/d2l-quick-eval-submissions-table.js
components/d2l-quick-eval/d2l-quick-eval.js

Lockhart list: `Web Components - reflectToAttribute (Slide 19)`
As per: https://polymer-library.polymer-project.org/3.0/docs/devguide/properties#attribute-reflection
We don't need to use `reflectToAttribute: true` if the variable in question does not change within the component. As the only time a value would be reflected back to the attribute would be on a value change.

Remove unneeded reflectToAttribute

---

components/d2l-activity-name/d2l-activity-name.js

This should fix the weird icon clipping across browsers, it should also make the ellipsis work.

fix ellipsis and icons being cut off on all browsers

---

components/d2l-quick-eval/behaviors/d2l-siren-helper-behavior.js
test/d2l-quick-eval/behaviors/d2l-siren-helper-behavior.js

Problem: Search is not persisted when you go QE -> Evaluate -> Back to QE
Solution: Send search params to the evaluation page
This is only half the battle, we need an LMS change to echo the search params back to QE.
FYI @amauryperez since you will be reviewing the LMS change

US109690 - send collectionSearch param to evaluation page

---

components/d2l-activity-evaluation-icon/d2l-activity-evaluation-icon-base.js
test/d2l-activity-evaluation-icon/d2l-activity-evaluation-icon-base.js

Should be no visual change. Screen readers should now read the tooltip when navigating to the draft icon.

Screen readers should read tooltip text for draft icon.

---

components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js

The flow for both keyboard users is new-submissions --> toggle-button --> evaluate-all --> submissions-list --> publish-all --> next card
The flow for screen-readers would be similar:
title --> subtitle --> completed-meter --> evaluated-meter --> published-meter --> new-submissions --> toggle-button --> evaluate-all --> submissions-list --> publish-all --> next card

Moved the toggle button in dom to improve accessiblity flow

---

components/d2l-quick-eval/d2l-quick-eval.js

Problem: Activities does not work when you dynamically set `activitiesHref` because the `_activitiesHref` function is only called when one if its parameters change
Problem: This was preventing auth-me (the dev tool I'm creating to automatically fetch keys) from working with activities
Solution: force polymer to recalculate `_activitiesHref` when `activitiesHref` changes

Allow quick eval to dynamically respond to activitiesHref changes

---

components/d2l-quick-eval/behaviors/d2l-hm-search-behavior.js
components/d2l-quick-eval/d2l-quick-eval-activities.js
components/d2l-quick-eval/d2l-quick-eval-submissions.js
test/d2l-quick-eval/behaviors/d2l-hm-search-behavior.js

Problem: we want to be able to persist search state during evaluation
Problem: search state is persisted, but upon load the search state is not displayed to the user
Solution: use the new `initialValue` property of `d2l-hm-search` from https://github.com/BrightspaceHypermediaComponents/common/pull/32
FYI @jeroach since you found the bug in the first place

US109690 - display currently searched term on initial load

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
components/d2l-activity-editor/d2l-activity-editor.js

This PR makes the `d2l-activity-assignment-editor` a `PendingContainer` so it tracks the loading of all it's child components.
It uses the `_hasPendingChildren` state to set a property on the `d2l-activity-editor` to control whether the `d2l-activity-editor` renders a loading placeholder (will soon be replaced with a skeleton image so not bothering to localize it for now) or renders the actual editor detail.
I considered making the `d2l-activity-editor` itself the `PendingContainer` so that we don't have to add that to every other activity editor instance, but it really needs to be on the top level so that it can also take into account the loading of the initial activity usage URL.

Integrate PendingContainerMixin into activity editor

---

components/d2l-quick-eval/d2l-quick-eval.js
test/d2l-quick-eval/d2l-quick-eval.html

Problem: QE was behaving weirdly when you returned back to QE after doing evaluation and you had search/filter criteria. It would filter the list based on the criteria but not display that you had criteria active
Solution: After digging in a bit, I saw 2 problems:
1. after loading a page, we would set the href to `''` when we toggled and set it back to `href` when it was active again. However, this was causing the page to load again. The fix here is to keep `href` the same if `href` has already been loaded
2. There was a small period of time where the 2 variables that controlled which page was active did not match. Rather than handle this case specifically, I just unified the variables.
So now `_showActivitiesView` no longer exists, and the page is solely controlled by `toggleState`.

US110688 - fix lazy loading regression

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/error-handling-mixin.js

When we have the tooltip conditionally render, the tooltip will not initially show. The easiest way to work around that is to manually call `show()` on the tooltip.
If the tooltips did not conditionally render, we wouldn't need to do this. But due to possible impacts on performance, we should have it conditionally render.

Create error handling mixin for setting and clearing errors

---

components/d2l-activity-admin-list/d2l-activity-admin-list.js
demo/d2l-activity-admin-list/d2l-activity-admin-list-demo.html
test/d2l-activity-admin-list/d2l-activity-admin-list.js

- Load list items using the `siren-sdk` `ActivityUsageCollectionEntity`
- Add basic styling for the header and body sections of the page

d2l-activities-admin-list siren-sdk integration

---

components/d2l-quick-eval/behaviors/d2l-hm-filter-behavior.js
components/d2l-quick-eval/behaviors/d2l-hm-search-behavior.js
components/d2l-quick-eval/behaviors/d2l-siren-helper-behavior.js
components/d2l-quick-eval/d2l-quick-eval-activities.js
components/d2l-quick-eval/d2l-quick-eval-submissions.js
test/d2l-quick-eval/behaviors/d2l-siren-helper-behavior.js
test/d2l-quick-eval/d2l-quick-eval-clear-on-intial-load.html

Previous PR: https://github.com/BrightspaceHypermediaComponents/activities/pull/385
Problem: In test, sometimes the filters would not be loaded before `_loadData` ran. This meant that `filtersApplied` was `undefined`. Thus in this case, the criteria would not be reset on an empty response.
Solution: Instead of waiting for `/filters` to load, just detect if the query string param is present in the `href`.
Obviously this solution breaks our design because now the UI knows too much about the filters implementation. But I can't think of any other way of doing it (short of the HM route returning this information - I think we should eventually do this). An advantage of this solution is that if we do go forward with lazily loading the filters then the features that rely on `filtersApplied` will …

US105733 - add method to detect if search or filter is applied immediately

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-html-editor.js

In #436 I moved the `d2l-activities-html-editor` component up one level, but didn't update this value. Strangely, changing it to just `../../` instead doesn't work, and is likely related to LitElement and `resolveUrl` not being friends. However, using `import.meta.url` does indeed work, and surprisingly also works for the demo! Confirmed that this works with a bundled and unbundled version of BSI.
This also removes the addition of `this.token`, which was thought to be required, but is not.

US110196 Fix _resolveUrl path

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-html-editor.js

This adds a more predictable `change` event to the `d2l-activity-html-editor`, which is internally hooked up to both the `input` and `change` event from `d2l-html-editor`. This ensures the outer component generates an event for all changes within the HTML editor, whereas the previous implementation wouldn't pick up e.g. inserting an image or changing the text format until the input text was also changed. This means that the parent component (`d2l-activity-assignment-editor-detail` in this case) only has to listen for this `change` event, and can use that to drive auto-saving the instructions value.
This also updates the size of the editor to be a minimum of 3 rows, which matches the design.

US110196 Fixup: HTML editor change event

---

package.json

Due to magic I don't entirely understand, BSI requires all dependencies to only specify the major version. This change was introduced in #441, but breaks the BSI build when `activities` is updated there.
It seems like this was put in place to ensure getting at least a specific version of `siren-sdk` that presumably has some new functionality, but BSI will always get the newest version anyway (until a breaking/major version change).

Fix siren-sdk version

---

components/d2l-quick-eval/d2l-quick-eval.js

Adding this in preparation for the dismiss functionality so that the flag is ready to go once we're ready to start adding components.
Property is not yet hooked up to anything, as there are no components yet for dismiss that need to be hidden. Tests should come once we start adding components.

Adding dismiss flag property.

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/en.json
components/d2l-activity-editor/d2l-activity-due-date-editor.js
demo/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.html
demo/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.html
demo/d2l-activity-editor/d2l-activity-assignment-editor/data/assignmentActivity.json
demo/d2l-activity-editor/d2l-activity-assignment-editor/data/assignmentActivityUsage.json
package.json
polymer.json

This `d2l-datetime-picker` control will show the current due date for the activity, and can be used to set a new due date for the activity. There are a few caveats to this currently that are worth noting:
- The `d2l-datetime-picker` component in use here is obsolete, and is going to be replaced in the near future, but there is not currently a timeline for this change. Once a new component exists, we should switch to use it.
- There is a change in the LMS to pull in `moment.js` to allow this component to work, as it doesn't do it itself. When we switch to a new picker component, this change can be removed, as it's two network calls to large-ish libraries that we won't need to make anymore.

US110582 Add due date editor

---

components/d2l-activity-editor/d2l-activity-due-date-editor.js

It's `documentElement.dataset.intlOverrides`, not `documentElement.intlOverrides`!

US110582 Fixup: pass config in correctly

---

activities.serge.json
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/en.json
components/d2l-activity-editor/d2l-activity-due-date-editor.js
components/d2l-activity-editor/lang/en.json
components/d2l-activity-editor/localization.js

In #440, a Serge config was added for the `assignmentActivityEditor`, but there will be several components within `d2l-activity-editor` that are not specific to assignments. To address this (based largely off [this thread](https://github.com/BrightspaceHypermediaComponents/activities/pull/446#pullrequestreview-306128414)), this adds a new config for the generic `activityEditor` langterms. There will likely be overlap in these terms, but this is the cleanest way to keep the domain-specific and domain-generic terms from cluttering each other up. This also means that eventually, when there are other specialized activity editors (e.g. `d2l-activity-survey-editor` or something), we'll have to add new Serge configs for them as well.
In order to support this, and use the same …

Add Serge config for generic components

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-due-date-editor.js
components/d2l-activity-editor/save-status-mixin.js
polymer.json

Previously, for saving name/instructions/due date, we were getting the Siren action from the `siren-sdk`, building the field values, and calling `SirenFetchMixinLit._performSirenAction`. However, the purpose of the `siren-sdk` is to abstract out Siren almost entirely, so that there is an easy to use interface on a given entity type that can be used by consumers - e.g. just call `setName(newName)`. There are two main benefits to this:
1. The UI code becomes cleaner - ideally, to the point where the UI code knows nothing about Siren at all, and only knows how to speak in the language of `siren-sdk`.
2. Consistency - first, because ideally all clients only speak `siren-sdk` and therefore changes to the actual details of the flow need to only be changed in one place. In addition, this reduces …

Use new siren-sdk functionality

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/en.json
components/d2l-activity-editor/select-styles.js
demo/d2l-activity-editor/d2l-activity-assignment-editor/data/assignmentActivity.json

This adds a styled `select` element that presents the options for `submissionType` on the assignment. There are two caveats to this change:
1. The `completionType` dropdown is not included, which means the On Paper and Observed in Person submission types can't be used correctly (they will both just use "Automatically on due date" as the completion type for now)
2. The styles for the `select` have just been copy+pasted into a `select-styles` file, but are planned to be separated out somewhere common.
Both of these should be rectified soon - the first by another US, and the second once some further discussions occur with Gaudi et al.
This also includes some minor changes to not access `super._entity` directly for getters, which is somewhat bad form it turns out - instead, it's better to use …

US110198 Add Submission Type select list

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/en.json

Most of the logic for this selector is done in `siren-sdk`, so all it needs to do is call `setCompletionType`. This change also removes the debounce autosave from these dropdowns, as it causes odd UI behaviour and lags the showing/hiding of the completion type selector.
Requires https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/84

US111526 Add completion type selector

---

activities.serge.json

In the most recent translation run, we got back output that included translated `context` strings, which is not what we want. Turns out, this is due to the lack of this plugin, which translates the `context` into the expected description field for translation by Serge. This should mean that, after the next translation run, our translated files should no longer have the `context` strings in them at all, and instead be a fairly flat list of `langterm: "translation"` as expected.

Add Serge plugin for context

---

components/d2l-activity-editor/d2l-activity-due-date-editor.js
components/d2l-activity-editor/lang/en.json

Came from Erin during review that this should have placeholder text when cleared to make it apparent that when unset, this means no due date.

Add "No due date" placeholder

---

activities.serge.json

I saw @ryantmer do a thing and its pretty cool.
So i wanted to pilot an experimentation new serge integration that pulls us only js files. I shamelessly stole this code from https://github.com/BrightspaceHypermediaComponents/activities/pull/468.
@ryantmer is there a way to test this? Do I have to submit a lang term, then wait and see? Any modifications do i need to get this running?

added experimental serge parsing

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
components/d2l-activity-editor/d2l-activity-text-editor.js
demo/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.html
demo/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.html

This passes down a user config setting to determine whether to use the HTML editor or a plaintext editor for the instructions. This could be represented in an API response somehow, but after some thought and trying to flesh that out, this was a much simpler solution. It's unfortunate that the interim components needs to pass down an attribute that they don't really care about (`htmlEditorEnabled`), but it's not all that much more code or complexity, and the presence of other text editing fields in the future would be easy to support.
The new `d2l-activity-text-editor` acts more-or-less the same as the HTML editor did, but now will display a `d2l-input-textarea` when the user doesn't want to use richtext editing.
Requires https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/86

US111620 Add plaintext instructions editor

---

components/d2l-activity-editor/d2l-activity-assignment-editor/lang/ar.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/de.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/en.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/fr.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/ja.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/ko.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/nl.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/pt.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/sv.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/tr.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/zh-tw.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/zh.js
components/d2l-activity-editor/lang/en.js
components/d2l-activity-editor/lang/fr.js
components/d2l-activity-editor/lang/nl.js
components/d2l-activity-editor/lang/pt.js
components/d2l-activity-editor/lang/zh-tw.js
components/d2l-activity-editor/lang/zh.js

Sadly, support for single quotes and non-quoted keys was only added to Serge's `parse_js` parser in evernote/serge@8d42a5d#diff-ab91cf35eb431bb9c7e44e833b0a724f (in August), and hasn't yet been released - despite the documentation saying it's supported. So, we need to use the double-quotes-everywhere syntax for now.

Fix lang file format

---

components/d2l-quick-eval/LitQuickEvalLocalize.js

Here is a screenshot of a lit components working in different lang terms, tested under different lang terms.
Testing for this helper would be through the quick diff test I wrote in https://github.com/BrightspaceHypermediaComponents/activities/pull/471.
Thanks to @dbatiste and @ryantmer for their input.
The design of this component is derived straight from the documentation https://github.com/BrightspaceUI/core/blob/master/mixins/localize-mixin.md
It's not the most elegant design. I had an idea of changing `QuickEvalLocalize` to give you localization based on the component being polymer or lit. That idea was discarded because it was too risky.

created a localization mixin helper for Lit components in QE

---

components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
package.json

- Learning path Title and Description are now editable. Users may select and edit the text of the title and description of the activity collection editor in-place by clicking them.
- Hovering over either item will change their text colour to blue and the mouse to a pointer to denote the functionality.
- Long, one word titles shouldn't overflow. Long titles won't compress the `visible` icon and label over top each other.
- The header's margins have been compressed to more correctly match the design sample.

Integrated Edit-In-Place into title and description of activity collection editor

---

activities.serge.json
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-editor.js
components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js
components/d2l-activity-editor/d2l-activity-attachments/lang/en.js
demo/d2l-activity-editor/d2l-activity-assignment-editor/data/assignmentActivity.json
demo/d2l-activity-editor/d2l-activity-assignment-editor/data/attachmentsCollection.json

This adds the first phase of components that provide the ability to add/remove attachments associated with an assignment. As of this change, the `d2l-activity-attachments-editor` is quite simple and bare, and intentionally designed such that it could be used with the concept of activity attachments (as well the existing assignment attachments).
What this does do:
- Display an attachment-picker component in FACE
- Show action buttons with tooltips based on what types of (link) attachments are available to be added
What this doesn't do:
- Do stuff when you click on a button - coming soon (next user story), still figuring that out
- Do anything related to file attachments, as these are being handled separately (but should be compatible with these changes)
This was added as a new folder/Serge …

US111949 Add attachments editor

---

components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
demo/data/base/learning-path-activity-usage.json

This pull request replaces the visibility toggle with the `d2l-activity-visibility-editor` component to allow the toggle to properly trigger the action to update the visibility status when changed.

US108929: Integrate the draft / publish toggle

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-assignment-turnitin-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/en.js
components/d2l-activity-editor/d2l-activity-release-conditions-editor.js

[US111919](https://rally1.rallydev.com/#/detail/userstory/350454972296?fdp=true)
This PR adds the turnitin editor, which calls into the LMS to do the thing via a legacy dialog to the existing control. It doesn't currently display anything about the turnitin state, nor does it trigger a refresh of the assignment entity, both of which will happen in a follow-up when the designs catch up.
I also added an `if (!entity) { ... }` guard because I learned that it sure can be null or whatever, here and in the release conditions editor.

US111919 Add turnitin dialog launcher

---

components/d2l-activity-collection-editor/d2l-activity-collection-editor.js

Activity collection editor:
- Description is now limited to 280 characters.
- The selection outline when tabbed onto the title's save or cancel button will no longer be cropped on the bottom.
- The italic text of the title will no longer be slightly cropped on the top rightmost letter.
- Extremely long words will no longer overflow the description beyond the right margin.

Limited description length, removed title cropping

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachment.js
components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-editor.js
components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-list.js
demo/d2l-activity-editor/d2l-activity-assignment-editor/data/attachment1.json
demo/d2l-activity-editor/d2l-activity-assignment-editor/data/attachment2.json
demo/d2l-activity-editor/d2l-activity-assignment-editor/data/attachmentsCollection.json
package.json

This adds a list view of (link) attachments in the editor, as well as support for removing them.
Thanks to the entity store and a small change in the LMS that adds `Link` headers to the add/delete attachment routes, this approach automatically re-renders the list when an attachment is added or removed without any additional effort. It's likely that once autosave is figured out a bit more, we'll have to add better interim states, but that remains to be seen.

US112016 Add attachment list

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
components/d2l-activity-editor/d2l-activity-editor.js

This adds support for attachments being able to unfurl themselves into rich previews via the AF unfurling service. This is done using the newish Requester/Provider approach, which allows the top-level `d2l-activity-editor` component to provide the configuration necesssary for the nested `d2l-labs-attachment` component via the `d2l-request-provider` event.
The behaviour that is currently being encompassed in `d2l-activity-editor`'s constructor (via `addEventListener`) will soon be provided via `BrightspaceUI/core`, but until that is merged and released, this is a simplified version of it that unblocks this change. This also relies on the LMS setting the `unfurlEndpoint` attribute on the `d2l-assignment-activity-editor` that it renders, which has now been merged.

US112016 Unfurling support

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachment.js
components/d2l-activity-editor/d2l-activity-editor.js

This is a method of determining whether or not a given link attachment is a trusted site or not. Sadly, the actual Trusted Sites tool doesn't have its own API, but we can instead engage the HTML Editor API to determine if a link is trusted. The approach is a bit hackish, but it more-or-less mimics the behaviour provided by the `filterHtml` ifrau service.

US112016 Add trustedSitesEndpoint

---

components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js

Screen reader was not properly identifying the disabled publish all menu item. Should now list the item as "unavailable" when it's set to disabled.
Also changed the actual `disabled` assignment from an attribute to a property as the menu item has a disabled property.

aria bool attributes should be strings.

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js
components/d2l-activity-editor/d2l-activity-text-editor.js
demo/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.html

- Fix alignment of tooltip: The "Add link to existing activity" tooltip was being cut off, due to the boundary not being set. This applies the boundary to each tooltip - not strictly necessary, but this means that the order doesn't really matter. (If the styling were applied using CSS, we could `first-of-type`, but that doesn't allow for the computation that `d2l-tooltip` does with `boundary`.)
- Make QuickLink insertion work in Edge: For an unidentifiable reason, Edge doesn't like the call to `super._entity` within the `async` callback here. The other, non-`async` callbacks work fine, but this one seems to think `super._entity` is undefined within the callback. To avoid this, we can just create a reference to it.
- Fix HTML Editor in Edge: Sadly, the root cause here was weird DOM stuff …

Trello fixes

---

components/d2l-quick-eval/d2l-quick-eval-activities.js
components/d2l-quick-eval/d2l-quick-eval-submissions.js
components/d2l-quick-eval/d2l-quick-eval.js
components/d2l-quick-eval/dismiss/d2l-quick-eval-dismissed-activities.js

My approach here is to use events. We can fire global events when refreshes are needed and the controllers can listen for them. I was going to write this as a behaviour, but since that's polymer 1 stuff and we're on Lit now I decided rather than entangle myself in a framework I'd just get it done.
While testing this I noticed a weird bug where the UI does not match what the API is returning. Peggy reported a similar defect in slack. I'm wondering if we're not making observable changes to `this.entity`.

Add refresh capabilities to all 3 controllers

---

components/d2l-quick-eval/behaviors/d2l-hm-search-behavior.js

This fixes `undefined` showing up in the search box under these conditions (https://rally1.rallydev.com/#/238990806412d/detail/userstory/355308987036), but I'm still not sure why it's happening.

Fixed undefined search default.

---

components/d2l-quick-eval/dismiss/d2l-quick-eval-ellipsis-menu.js

Context is here: https://d2l.slack.com/archives/C0PHG3QB0/p1576179194361700
Basically, we were passing token as a string instead of an object. And token is an object in the LMS which is why it worked locally (where we use string tokens) but not in QUAD.

pass property as property instead of attribute

---

components/d2l-quick-eval/d2l-quick-eval-submissions.js

I could not figure out why submissions does not work but activities and dismissed do. However, the workaround is relatively simple, just manually update `this.entity` when the response comes back.
I'm not a huge fan of this change but we can mitigate the risk by continuing to manually test things. Tomorrow we should take another look at this to determine the root cause to judge the riskiness of the release. For now, let's just let the testers be able to test the workflow.

Manually update entity

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-editor.js
components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-list.js

The property binding is not required here, and just adds some confusion. It is still required for the token, as that can be a string, object, function, or undefined.

.href -> href

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js

This was introduced in https://github.com/BrightspaceHypermediaComponents/activities/pull/545, or more accurately was surfaced by it. HTML attributes are strings, and LitElement properties are `undefined` by default - which, when stringified, is `"undefined"`. This can result is us trying to fetch weird URLs with "undefined".
To remedy this, it's a safe idea to initialize our strings in the constructor. Not required for everything, and not really needed for booleans (unless they should default to true), but a good practise to be in.

Fix undefined hrefs

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachment.js

With BrightspaceHypermediaComponents/siren-sdk#109, we can now more precisely control partial re-renders of the page as things load. This change makes it so that when the page is first loading, we show the "Loading" text in place of the full editor. Once the page has finished loading once (which we know by `d2l-pending-resolved` being fired), we won't ever show that text again. This allows for lower-level components on the page to re-fetch data without the whole page looking like it's reloading.
This approach is also more compatible with lower-level `PendingContainer` elements - previously, when we were fetching a new attachment, the whole page would go to the "Loading" state, which meant we wouldn't even see the nice attachment skeleton that `d2l-labs-attachment` has!

Allow for better partial re-rendering

---

components/d2l-quick-eval/dismiss/d2l-quick-eval-action-dismiss-dialog.js

I don't exactly love the way we are doing this. We are essentially calling the resize function at specific points where we know that the layout of this dialog changes.
This is due to the way that the dialog is designed. @dbatiste recommended that we do not overuse the resize function, but I don't see another way to fix this issue.

resized dialog on _onDatetimePickerDatetimeChanged

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js
components/d2l-activity-editor/d2l-activity-attachments/lang/en.js

Similar to change made in #500 for link attachments, this adds and connects a button to open a file picker dialog. Also similar to #500, this required getting deep into LMS dialog JavaScript, which is ugly and not very maintainable.
This approach assumes we are living on an LMS page that has this JS available - fine since that is currently the case, but not great. The code is also very finicky, with a bunch of mystery parameters and such. A better solution, which is currently in the works, is for us to have a `d2l-dialog` that supports a filepicker and use that - in the short term, it will likely still mean this code exists somewhere (within the `d2l-dialog`), but for our use case here, it will mean we're just interacting with a WC with a clean API.

US112361 Add file selector dialog for attachments

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js

Change to reflect the change to `siren-sdk`, which itself was a change to reflect a change to the API. When adding files other than uploaded files, we need to be able to specify where the file we're attaching comes from, via `fileSystemType`. Fortunately, this info comes back from the dialog along with the file ID.

US112361 Fixup

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js

If we use the QuickLink directly, copying the assignment to another course will end up causing issues as the copied assignment will have attachments in another course. Instead, we can use the QuickLinkTemplate so that when an assignment is copied to another course, the attachments will refer to the new org unit.

Use QuickLinkTemplate to allow for copying

---

components/d2l-activity-collection-editor/d2l-activity-collection-editor.js

'Overflow: hidden;' on the title resulted in the highlight box being thinner on the top and left side.
`Overflow: hidden;' on the description resulted in description's Save and Cancel button having a cropped highlight ring when using tab navigation.
To fix this, Overflow handling has been moved to encompass the entire header of the component, which should be sufficient, and text shouldn't be able to grow out of bounds.

DE37102 - Highlight boxes of Title and Description no longer cropped

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachment.js

Issue: when adding a new link, there is a brief flash of the generic-link icon, before switching to the attachment skeleton, then finally the unfurled link. This is because of a mismatch in behaviour between `d2l-activity-attachment` and `d2l-labs-attachment` - the former expects the latter to be able to handle null attributes/inputs, and the latter expects the former to never provide null attributes/inputs!
This fix changes `d2l-activity-attachment` to never pass a null `attachment` to the `d2l-labs-attachment` component, instead opting to just not render anything. This is probably a good approach to take in general, actually - it results in a faster (no-op) render when the component is first created.

Fix flash of generic link icon

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js

This sets the allow-multiple parameter to allow for multiple uploads, which matches the existing experience in the assignment editor.
This also removes two options that weren't being set by the old editor - no noticeable impact in this, but figured it's better to be consistent.

Align dialog params to existing ones

---

components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card-subtitle.js
components/d2l-quick-eval/dismiss/d2l-quick-eval-action-dismiss-dialog.js
components/d2l-quick-eval/dismiss/d2l-quick-eval-dismissed-activities-list.js
package.json

I've made some improvements to our Intl library such that it's a lot easier to call into its date/time/number formatting and parsing functions.
Since these aren't free to load on every page, I want to move them out of the `LocalizeMixin` (which many many components extend) and just have components import them only when they need to. So this change just calls into Intl directly.
Once the 4 places that are using `LocalizeMixin`'s Intl stuff (of which this is one) are calling Intl directly, I'm going to remove the functions from `LocalizeMixin`.

Use Intl instead of LocalizeMixin for dates

---

components/d2l-activity-editor/d2l-activity-editor.js

There is JavaScript in the LMS that calculates where to place the opt out tabbie so that it sits under the immersive nav bar. When FACE is loading, the editor (including the immersive nav) is hidden and has a height of 0. Thus, it is unable to calculate where to place the opt-out tabbie. This commit changes it so that the loading screen becomes a fixed overlay over the editor and the editor compoonents render beneath it.

Allow opt-out tabbie to calculate its position

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js
components/d2l-activity-editor/d2l-activity-attachments/lang/en.js

This change is possible due to a server-side change that makes the functions to open the various dialogs available via the `ObjectRepository` on the page. This still relies on magic keys to retrieve these opener functions, but this removes the majority of the deep-LMS-knowledge code from the UI side, which is an improvement.
This is functionally identical to what already existed.

US111908 Refactor dialog openers

---

components/d2l-activity-editor/d2l-activity-score-editor.js

This addresses:
https://trello.com/c/m2iseQGI/55-ungraded-text-field-button-paddin
https://trello.com/c/Xh6IOgdm/49-typography-and-padding-around-points-next-to-the-numerical-entry-field
https://trello.com/c/DBOZlShj/50-divider-line-between-points-and-the-button
https://trello.com/c/HbunTVF1/51-in-grades-button-alignment-with-sort-menu
https://trello.com/c/gJa1SFZl/53-left-align-menu-with-in-grades-button
And part of:
https://trello.com/c/KryvT8X3/54-button-text-field-are-not-yet-responsive

Us111489 ui tweaks

---

components/d2l-activity-editor/d2l-activity-score-editor.js

Edge was not getting the `change` event, but it does get the `blur` event. Debouncer is used to avoid 2 api calls for browsers that handle both events. Fixes https://trello.com/c/M6haUaoT/59-edge-only-add-to-grades-doesnt-autosave

US111489 fix score not saving in Edge

---

components/d2l-activity-collection-editor/d2l-activity-collection-editor.js

- Add Activities Dialogue: Already added courses are misaligned from those that haven't already been added to the LP.
- Add Activities Dialogue: The Clear Selection link is not accessible when using keyboard navigation. It also isn't read out by a screen reader.
- Add Activities Dialogue: Clicking on the Add button with nothing actually selected results in a 400 error being sent. This button should probably be disabled until something is selected.
- Add Activities Dialogue > Search for Activities: Selecting activities, search for more, select more activities, click Add > The first set of activities doesn't get added to the LP.
- Add Activities Dialogue > The 'Load More' button highlight (While using keyboard navigation) has the bottom part of the border cut off:
- Loading styles have been …

Polish the Add Activity Dialogue

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
components/d2l-activity-editor/d2l-activity-editor.js
components/d2l-activity-editor/lang/en.js

- Localize the "Loading..." message when the page first loads (this isn't the final loading state, but this was 30 seconds to fix so figured might as well)
- Move the providing of `unfurlEndpoint` and `trustedSitesEndpoint` up one level, so that `d2l-activity-editor` doesn't need to know about it

Small fixes

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js
components/d2l-activity-editor/d2l-activity-attachments/lang/en.js

Per title, this adds the "Record Video" button to the attachments picker, and hooks up the dialog opener and dialog callback. This workflow is very similar to the workflow for adding files.

US111908 Add Record Video button

---

components/d2l-quick-eval/d2l-quick-eval-activities.js
components/d2l-quick-eval/d2l-quick-eval-submissions.js
components/d2l-quick-eval/d2l-quick-eval.js
test/d2l-quick-eval/d2l-quick-eval-activities.js

Problem: In course mode it doesn't really make sense to have a course filter (since activities are sourced from 1 course by design)
Solution: Get the valid filters from the LMS and use that as the whitelist

US112481- Get filter whitelist from the LMS

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js
components/d2l-activity-editor/d2l-activity-attachments/lang/en.js

This functionality is pretty much identical to the video note - in fact, most of this code could be exactly the same for both, but it is possible for the audio note functionality to be available without the video note functionality, so better to keep them as completely distinct workflows.
Requires https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/120 and the backend change.

US111909 Add audio note functionality

---

components/d2l-activity-collection-editor/d2l-activity-collection-editor.js

Guard has been introduced around the `edit-in-place` components.
Currently, the title and description are reset each time a property is assigned due to being rendered asynchronously via promise fulfillment.
To the user, adding activities, saving either the title or description, or toggling visibility, would close any other open edit mode title or description.
This guard prevents re-rendering and resetting the components except when the page has finished loading, ensuring the edit in place editors do not close unexpectedly during use.

Guarded editors from closing on property change

---

components/d2l-quick-eval/d2l-quick-eval-activities.js
components/d2l-quick-eval/dismiss/d2l-quick-eval-dismissed-activities.js

Part 2 of: [US112559](https://rally1.rallydev.com/#/detail/userstory/356908493924?fdp=true): [Dismiss][UI] A11y Quick Eval Toast message when activity is dismissed is not being read by screen readers
Part 1 is over here: https://github.com/BrightspaceUI/alert/pull/34

Use new announce-text attribute for all d2l-alert-toast tags

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js

Fixes https://trello.com/c/K6rYX68v/71-a11y-attachments. Note that in chrome/nvda this issue was not noticeable because the tooltips are read out. However in Firefox/nvda the tooltips are not read out so the buttons need to be labeled for the screenreader. 
This PR also disables focus-lock on the tooltips so that if you hover over one tooltip while another has focus you don't see both tooltips overlapping.

add labels to attachment buttons, and disable focus lock on tooltips

---

components/d2l-activity-editor/d2l-activity-visibility-editor.js
components/d2l-activity-editor/lang/en.js

Fixes https://trello.com/c/WDvmeiLc/74-a11y-label-of-visibility-control. The text needs to be more descriptive for screen reader users, as it is unclear what is "hidden".

make visibility text more descriptive

---

components/d2l-activity-editor/d2l-activity-html-editor.js
components/d2l-activity-editor/lang/en.js

Addresses https://trello.com/c/mrm60BMG/69-facea11y1-the-instructions-html-editor-toolbar-appeared-to-be-at-the-end-of-the-page-and-the-toolbar-doesnt-have-a-skip-link-cap by adding instructions on how to enter and exit the toolbar when using a screenreader.

add aria instructions for editor toolbar use

---

components/d2l-activity-editor/mixins/d2l-activity-editor-container-mixin.js
components/d2l-activity-editor/mixins/d2l-activity-editor-mixin.js
test/d2l-activity-editor/mixins/d2l-activity-editor-container-mixin.html
test/d2l-activity-editor/mixins/d2l-activity-editor-container-mixin.js
test/d2l-activity-editor/mixins/d2l-activity-editor-mixin.html
test/d2l-activity-editor/mixins/d2l-activity-editor-mixin.js
test/index.html

These two mixins are intended to allow us to start co-ordinating the save behavior in FACE.
The `ActivityEditorContainerMixin` will be applied to the top level editor component (e.g. `d2l-activity-assignment-editor`) for Assignments. It handles listening on the `d2l-activity-editor-save` event which will be dispatched from the Save button where ever that happens to be rendered. It also includes an implementation to allow child editors to be registered so that when the Save button is clicked, child editors can be notified.
The `ActivityEditorMixin` will be applied to each component that supports editing capabilities.
It includes a `save()` method that will be called by the `ActivityEditorContainerMixin` when a Save is initiated. It's unlikely that every editor component will need to …

Activity Editor mixins

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js

Fixes https://trello.com/c/OH0fyVUE/82-a11y-previous-tooltip-is-announced-when-tabbing-through-attachments

hide tooltip from screenreader since it already has button descriptions

---

components/d2l-activity-collection-editor/d2l-activity-collection-editor.js

[DE37544](https://rally1.rallydev.com/#/detail/defect/363034010104?fdp=true)
Spacing and flex alignment has been added to the selection count in add activity dialogue to fix ugliness in mobile.

Added spacing and flex alignment to selection count

---

components/d2l-activity-collection-editor/d2l-activity-collection-editor.js

[DE37520](https://rally1.rallydev.com/#/detail/defect/362778356136?fdp=true)
This is a solution to the issue where deleting all activities from a learning path resulted in a locked visibility toggle, including when the LP was visible. This caused empty learning paths to be viewable by a learner, which is currently undefined behaviour.
The visibility will now always be set to hidden after all activities are deleted.

Visibility set to hidden when the last activity is removed

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachment.js

https://trello.com/c/N6eVNFLU/98-face-lms-file-attachment-should-not-be-unfurled
Flag 'file' attachments as 'Document', so they are rendered as intended by attachments-ui.

Fix assignment editor file attachments rendering

---

components/d2l-activity-editor/d2l-activity-editor.js

Fixes https://trello.com/c/54WLoPqc/89-edge-only-face-page-doesnt-load
Turns out the problem was that when `this.loading` was true, the editor slot wasn't rendered, so in edge that meant it also wasn't receiving / handling any events. Using `hidden` instead ensures the elements are present in the dom and able to handle events, even when not visible.

fix assignment activity not loading in edge

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-html-editor.js
components/d2l-activity-editor/d2l-activity-text-editor.js

During work on the Save/Cancel changes, I was experimenting with skipping rendering of components when things like the the assignment and activity properties were not yet initialized.
Currently we always just render which means we are rendering with lots of properties with undefined values. Whilst this isn't necessarily bad (and sometimes it can even improve eventual perceived render performance) it requires all components to handle the `undefined` values correctly and it was making it clunky to destructure the MobX properties.
So I tried skipping rendering until the activity was loaded, but this bizarrely broke the HTML editor. It turned out that the HTML editor initialization basically depends upon initially being called with an `undefined` `value` property. If you call it initially …

Make HTML editor initialization more deterministic

---

components/d2l-activity-collection-editor/d2l-activity-collection-editor.js

This PR will resolve the loading black boxes in Edge, setting them to animate and pulse like in other browsers.
In Edge pre-Credge, if: 
- A css animation contains a css var, and 
- the animation is played in an SVG shape like a rect, 
Then there must also be a `fill:` css property applied to the SVG rect, and the fill colour must be assigned by a css variable, though the chosen variable doesn't seem to matter.
Using a basic color will block the animation, but using no fill property at all will render as a black box.

Added background fill to skeletons to fix Edge

---

components/d2l-activity-collection-editor/d2l-activity-collection-editor.js

[DE37493](https://rally1.rallydev.com/#/detail/defect/362514237868?fdp=true)
Visiting the edit learning path page while using a screen reader resulted in the entire page contents being read. This was due to the aria-live="polite" set on the main web component. This attribute will read the contents to the user once aria-busy is false, which in VoiceOver's case, means _all_ of the contained content.
Setting the aria-live to off prevents this.

Set aria-live to off for activity-collection-editor

---

components/d2l-activity-editor/d2l-activity-attachments/state/attachment-collection.js
components/d2l-activity-editor/d2l-activity-attachments/state/attachment-collections-store.js
components/d2l-activity-editor/d2l-activity-attachments/state/attachment.js
package.json
test/d2l-activity-editor/d2l-activity-attachments/state/attachment-collection.spec.js
test/d2l-activity-editor/d2l-activity-attachments/state/attachment.spec.js

Just supports loading collections and attachments for now.
Integration with web components will follow in later PR.
The store supports caching both collections and attachments so that resource based web components for the attachment list and attachments can each reference their associated entities.
The collection object contains observable properties for:
* the list of entity hrefs (not to be confused with attachment target urls), for each attachment in the collection.
* permissions for each attachment type that will be used to determine what buttons are enabled in the picker.
The attachment object contains observable properties for:
* the status (editing, creating, deleted) - used to determine whether we have a remove button/undo button etc
* the name/url of the attachment used to …

Initial attachment collection MobX store. 

---

components/d2l-activity-list-item/d2l-activity-list-item.js

`d2l-activity-list-items` used a regex replace to parse the content from the description: `/<[^>]*>/g, ''`
This is insufficient to deal with a few other scenarios such as html entitites.`&nbsp;` would not be caught by this, nor would `&lt;`.
This has been resolved by using a temporary div to strip html out of the content, resulting in it being displayed with the entities properly parsed and all tags removed. 
Sample string:
`<p>Lorem <p>ipsum &nbsp; </br> dolor <b>sit</b> amet, con<>ectetur&lt; /test&gt; adipiscing </p> elit. Donec u<span>ltricies</span> ligula libero, eu dapibus`
Before:
After:
Edit: Kept regex tag removal in addition to changes to prevent execution of javascript.

List items display only text content of description

---

components/d2l-activity-editor/d2l-activity-availability-dates-editor.js
components/d2l-activity-editor/d2l-activity-due-date-editor.js
components/d2l-activity-editor/state/activity-usage.js
test/d2l-activity-editor/d2l-activity-availability-dates-editor.js
test/d2l-activity-editor/state/activity-usage.spec.js

Replaces checking for `canEditStartDate`, `canEditDueDate`, and `canEditEndDate` with `canEditDates` based on the new aggregate save dates action.
Depends on a new helper methon in the siren-sdk: https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/132

Use combined dates action to check edit dates permissions in editors

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-availability-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-secondary.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/en.js
components/d2l-activity-editor/d2l-activity-availability-dates-summary.js
components/d2l-activity-editor/lang/en.js

[US111888](https://rally1.rallydev.com/#/detail/userstory/350128946056?fdp=true)
This PR moves the availability dates and release conditions into the accordion from the design. I yanked them from the editor secondary guy into a new element because it's more readable this way. I stubbed out the summary for release conditions, and the summary and editor for special access, neither of which can be implemented yet.
Screenshots:
- [closed](https://user-images.githubusercontent.com/30184468/74379900-96f13c00-4db6-11ea-812b-17dde8b5b809.png)
- [open](https://user-images.githubusercontent.com/30184468/74379901-96f13c00-4db6-11ea-9ddc-f8ab06e85496.png)

US111888 Availability Dates are progressively disclosed in the right panel

---

.vscode/launch.json
components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachment.js
components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-editor.js
components/d2l-activity-editor/d2l-activity-attachments/state/attachment-collection.js
components/d2l-activity-editor/d2l-activity-attachments/state/attachment-collections-store.js
components/d2l-activity-editor/d2l-activity-attachments/state/attachment.js
components/d2l-activity-editor/state/object-store.js
test/d2l-activity-editor/d2l-activity-attachments/state/attachment-collection.spec.js

This is the final PR for save/cancel of attachments. Once this is approved I will merge the 2 branches into the `mbayly/save-cancel-attachments-2` branch, and then request a final approval on that merged PR in order to push to master.
The bulk of this PR is adding the polymorphic save methods to each of the attachment types, and adding the attachment collection save method, which determines which attachments are new/deleted/discarded based on analyzing the `creating` and `deleted` flags. The attachment collection tells each changed attachment to either delete or save itself, passing in the current `AttachmentCollectionEntity` into the `save` method so the attachment can call the specific attachment save action (e.g. link, google, onedrive, file etc).
You'll see that I had to add a …

Implement save of attachments

---

components/d2l-activity-editor/d2l-activity-availability-dates-editor.js
components/d2l-activity-editor/d2l-activity-due-date-editor.js
components/d2l-activity-editor/d2l-activity-editor.js
components/d2l-activity-editor/lang/en.js
components/d2l-activity-editor/mixins/d2l-activity-editor-container-mixin.js
components/d2l-activity-editor/mixins/d2l-activity-editor-mixin.js
components/d2l-activity-editor/state/activity-usage.js
test/d2l-activity-editor/mixins/d2l-activity-editor-container-mixin.js

When saving, it will first run the new `validate` method on all editors that implement it. If any validations fail, the LMS will return a 400 with details on the type of error. The error props can be used by components to determine if the error is relevant to them, and which lang term to use for the error tooltip.
Depends on https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/134
The datetime pickers are in flux right now, so I just added some pretty ugly tooltips for now, just to demonstrate that the errors and langterms are working. They should ultimately be replaced by the incoming new datetime input component.

Integrate validation requests with mobx state 

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/en.js
components/d2l-activity-editor/d2l-activity-editor-alert.js
components/d2l-activity-editor/state/activity-usage.js
test/d2l-activity-editor/d2l-activity-editor-alert.html
test/d2l-activity-editor/d2l-activity-editor-alert.js
test/d2l-activity-editor/index.html

Adds a new generic `d2l-activity-editor-alert` component, which is toggled by `ActivityUsage.isError`.
When instantiated by `AssignmentEditorDetail`, we also give it the assignment-specific langterm.

US113175 Display alert on validation error

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-availability-editor.js

This wires the availability dates editor component with the accordion into the activity usage state, so that it can check if any errors that pertain to the accordion are set.
In this case it cares about the start and end dates, which are known to be in error state when the respective `*DateErrorTerm` property is truthy.

US113175 Open availability dates accordion on error

---

components/d2l-activity-editor/d2l-activity-score-editor.js
components/d2l-activity-editor/state/activity-score-grade.js
components/d2l-activity-editor/state/activity-usage.js
test/d2l-activity-editor/d2l-activity-score-editor.js
test/d2l-activity-editor/state/activity-score-grade.spec.js

[US113166](https://rally1.rallydev.com/#/29180338367d/detail/userstory/362987616496)
This builds on 
https://github.com/BrightspaceHypermediaComponents/activities/pull/716
It moves the validation from the web component to the MobX state class so that it can also be called when the Save button is clicked. Some of the validation is still done immediately when the state of the score out of field changes. e.g. if someone enters in a non-numeric value, or if someone clears the score out of field when 'In Grades' is selected. But we also need to do the validation when Save is clicked in case they have not resolved the errors, or for the scenario where they select 'Graded' but never actually enter a score out of.
The MobX state class actions for setting the score out of and the various grade …

Part 2: Activity Score/In Grades - Refactor validation to support Save/Cancel

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-submission-and-completion.js
components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.js

Fixes a bug where the submission and completion types were not being saved correctly
Depends on https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/140

Fix submission and completion types saving

---

components/d2l-activity-editor/d2l-activity-assignment-editor/activity-summarizer-styles.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-availability-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-secondary.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-submission-and-completion.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-evaluation-editor.js

Screenshot: https://user-images.githubusercontent.com/3785788/75496655-ae175880-5976-11ea-85e6-ac82ccf155eb.png
@pureooze: note the header and summary classes are used in summarizers (d2l-activity-assignment-availability-editor.js , d2l-activity-assignment-editor-submission-and-completion.js, and d2l-activity-assignment-evaluation-editor.js).

Update secondary panel w/ styled summarizer + background color

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-availability-editor.js
components/d2l-activity-editor/d2l-activity-availability-dates-editor.js
components/d2l-activity-editor/d2l-activity-availability-dates-summary.js
components/d2l-activity-editor/d2l-activity-due-date-editor.js
components/d2l-activity-editor/mixins/d2l-activity-editor-container-mixin.js
components/d2l-activity-editor/state/activity-dates.js
components/d2l-activity-editor/state/activity-usage.js
test/d2l-activity-editor/d2l-activity-availability-dates-editor.js
test/d2l-activity-editor/state/activity-dates.spec.js
test/d2l-activity-editor/state/activity-usage.spec.js

Adds a new `ActivityDates` class that encapsulates most of the dates-related functions and properties.
Relies on https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/141
Also implements focusing on first element in error after a validation error.

Extract activity dates mobx state from activity-usage

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-availability-editor.js

Previously the accordion would open on error, but then close when the error is cleared. Now it will leave it open when the error is cleared.
To do this we need to know if the accordion is currently open: Either track the open state in a prop via the accordion state change events, or check the dom via `this.shadowRoot.querySelector('d2l-labs-accordion-collapse').opened`. I went for the former, using `this._opened`.

Fix availability dates editor accordion closing on error clear

---

components/d2l-quick-eval/build/lang/ar.js
components/d2l-quick-eval/build/lang/sv.js
components/d2l-quick-eval/lang/ar.json
components/d2l-quick-eval/lang/sv.json

This PR fixes both stories:
* https://rally1.rallydev.com/#/42960320374d/detail/userstory/336778594020
* https://rally1.rallydev.com/#/42960320374d/detail/defect/367913252916
The problem with the `ar` file is there was an invisible character which threw off the parser. This was ungodly difficult to figure out. We really need automatic validation of these langterm files because no way a human was gonna catch it.
The problem with the `sv` file was simpler, the translator just mangled the variable name by adding a space.

DE37770 US110507: fix langterm file formatting

---

components/d2l-activity-editor/d2l-activity-assignment-editor/lang/en.js

This PR reverts the lang term deletion that broke the Turnitin dialog.
[Broken dialog](https://user-images.githubusercontent.com/30184468/76252578-5d79e800-621f-11ea-9e8e-58571166e3e0.png)

Revert lang term deletion

---

components/d2l-activity-editor/d2l-activity-attachments/state/attachment-collection.js
test/d2l-activity-editor/d2l-activity-attachments/state/attachment-collection.spec.js

Currently we refetch attachments on save and also clean up removed/temporary attachments.
However, this causes components referencing those attachments to re-render which is causing the flicker. So until we need to support in-place saves, I am removing the extra handling that managed the refetching and attachment cleanup.

do not refresh attachments on save to prevent flicker

---

components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.js
test/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.spec.js

For https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/157 we need to remove these usages of the completionTypeOptions method.
The variable is used to hold the current visible completionTypeOptions in the UI. So we now populate it using the `_setValidCompletionTypeForSubmissionType` method.

Remove usage completionTypeOptions method

---

components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grade-candidate-selector.js

Throws when there are no grade candidates. We're actually not going to be rendering the dropdown when there are no grade candidates, so the code that is throwing these errors won't be executed in the future and so these errors won't happen. But it's probably safer to check if `selected` is undefined in case there are future changes to this that could potentially render the dropdown.

Fix undefined selected grade candidate error

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-availability-dates-editor.js

Problem:
On first render and after setting a date/time, the datetime picker has 20px extra bottom padding. After clearing the date/time, the picker has no bottom padding. This results in spacing being too much initially, and then not enough after clearing the date/time.
This fix forces the container elements of each datetime picker to compensate by simply setting the min-height to the height of the containing elements (either just the picker, or picker & label) + 20px (which is the desired spacing/padding).
Using min-height as opposed to height so the container can still expend for the timezone label which appears below the picker when a date is set.

Fix assignment editor datetime picker spacing

---

components/d2l-activity-editor/d2l-activity-conditions-editor.js

[US114762](https://rally1.rallydev.com/#/detail/userstory/376876593184?fdp=true)
This PR tweaks the rc dialog width/height to account for an API difference between legacy and mvc: in legacy, the width/height is for the content frame, in mvc it is the entire dialog chrome.

US114762 Fix rc dialog width/height to account for dialog chrome

---

components/d2l-activity-editor/d2l-activity-grades-dialog.js
components/d2l-activity-editor/d2l-activity-grades/state/grade-candidate-collection.js
components/d2l-activity-editor/d2l-activity-score-editor.js
components/d2l-activity-editor/state/activity-score-grade.js
components/d2l-activity-editor/state/activity-usage.js
test/d2l-activity-editor/d2l-activity-grades/state/grade-candidate-collection.spec.js
test/d2l-activity-editor/state/activity-score-grade.spec.js
test/d2l-activity-editor/state/activity-usage.spec.js

When the `Create and link to new grade item` radio button is selected, the appropriate data will be included so that when the `activity-usage` `siren-sdk` save is called, it will be able to call the `associate-new-grade` action extracted from the `scoreAndGrade.gradeCandidateCollection` entity.
The `activity-usage` save will now include sending the `associate-new-grade` action and `gradeName` of the assignment activity as data to the `siren-sdk` `activity-usage` save method.

Call to Associate New Grade

---

components/d2l-activity-editor/d2l-activity-grades-dialog.js
components/d2l-activity-editor/state/activity-score-grade.js
test/d2l-activity-editor/state/activity-score-grade.spec.js

The code being removed checked if the linked grade didn't change when we clicked 'OK' in the dialog, and if it didn't change, we would not change the assignment `out of` value in the input. We are removing this check so that if the user doesn't change the `link to existing grade` and click 'OK', we will still override whatever assignment `outOf` value the user has entered.

Remove linked grade didn't change check.

---

test/d2l-quick-eval/perceptual/d2l-quick-eval-action-dismiss-dialog.visual-diff.js
test/d2l-quick-eval/perceptual/d2l-quick-eval-ellipsis-dismiss-dialog.visual-diff.js
test/d2l-quick-eval/perceptual/d2l-quick-eval-view-toggle-button.visual-diff.js
test/d2l-quick-eval/perceptual/utils.js

I added periods of sleep to each of the visual difference tests that were frequently failing. The reason for doing this is because the screenshots were being taken before the CSS animations were finishing, which caused the tests to frequently fail as this introduced a race condition. I am hoping this PR will allow these tests to become more stable.
Unfortunately, the `HTMLElement` API that we are using for things like `click`, `focus`, `hover` etc. does not return an obvious `Promise` that resolves when the CSS animations are complete. The next best solution was to just give a small amount of time for the CSS animations to complete before taking the screenshot.
Let me know if there are any other possible solutions to this problem to explore.

Improve Visual Diff Tests Stability

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js
components/d2l-activity-editor/d2l-activity-score-editor.js

1. Removed from `d2l-activity-attachments-picker` boundaries because they were originally added to prevent viewport overflow which is now handled by the tooltip.
1. Replaced `d2l-activity-score-editor` boundaries with start align because the left boundary of `5px` caused it to be left aligned anyway and the right bound of 400px will never be reached because the max width is 350px.

Remove unnecessary usages of boundary due to improved d2l-tooltip

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
components/d2l-activity-editor/d2l-activity-outcomes.js

Also switched to declarative events in the component, simplified setting up the lang terms, and simplified the styling rules for the consumer.
https://rally1.rallydev.com/#/29180338367d/detail/userstory/382763326196

US115415 Use correct outcome tags tooltip langterm via requestProvider

---

components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-container.js

The overlay was closing when dialogs were used for rubric creation. This stops that from happening.

No longer close the rubric create overlay when clicking dialogs

---

components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-container.js

When closing the overlay or using the floating buttons, the href for the current rubric is removed. This along with rendering empty html when there is no href set, fixes the issues we were seeing when switching rubric types.

Clear out the rubric href after editing and update render

---

components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-container.js

Same setting of rubric href, just on using ESC. Follow up from Uzair's comment in last PR.

Set the rubric href when closing the overlay with esc

---

.travis.yml

Travis recently made a change to no longer update the case of the first letter of stage names.  Their change is behind the "enable build config validation" flag which appears to be enabled for this repo in Travis settings.  In `core` we do not have this flag enabled because it apparently causes other issues as we well, which explains why the hook still works there.
Unfortunately, currently the visual-diff bot looks for that to determine whether or not to hook into the Travis PR pipeline.  The short-term sol'n is to update the stage name to match what we expect it to be. When time permits we will update the bot to be more insensitive to the case.

Update Travis stage names to get visual-diff bot hook working again

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-evaluation-editor.js
components/d2l-activity-editor/d2l-activity-competencies-summary.js
components/d2l-activity-editor/d2l-activity-competencies.js
components/d2l-activity-editor/lang/en.js
components/d2l-activity-editor/state/activity-usage.js
test/d2l-activity-editor/state/activity-usage.spec.js

Adds a "Manage Learning Objectives" button (and supporting summary components) as part of the "Evaluation & Feedback" accordion when legacy competencies are available (as determined by the API).
Relies on siren-sdk changes https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/185
Flagged behind FACE milestone M3.

US115941 Render manage competencies button and summary

---

components/d2l-activity-editor/state/activity-usage.js

Sync props were being set after an `await` outside of a `runInAction`, thus being set outside of an action and throwing an error. This sets up all sync props ahead of time, and then only runs one _or_ the other async workflow to avoid wrapping large code blocks in `runInAction`.

Fix activity-usage mobx loading of competencies vs outcomes

---

components/d2l-activity-editor/state/activity-usage.js

Check for competencies link first, and only show alignments (learning outcomes) if there is no competencies link. This is to account for the case where the alignments _and_ competencies link are present, which only happens when both tools are enabled but there are no intents in the course. In that case we want to display competencies.

Adjust visibility of outcomes vs competencies

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-secondary.js

Safari and legacy Edge were throwing 500 errors when trying to load the sub-components of `d2l-activity-assignment-evaluation-editor` that relied on the `activityUsageHref`. It is `undefined` when passed as an attribute, causing the sub-components to try and fetch the activity on the route `activity/edit/undefined`.

Fix undefined load errors: Set secondary href on component as prop

---

components/d2l-activity-collection-editor/d2l-activity-collection-editor.js

This prevents the server from returning a 502 and not reloading activities when adding and reloading a large number of activities within the Edit My Learning page with a single call to getExecuteMultipleAction(), which seemed to happen on 17 or 18 activities maximum previously.

Adding new activities to an LP will now asynchronously batch in groups of 5.

---

components/d2l-activity-editor/d2l-activity-visibility-auto-editor.js
components/d2l-activity-editor/d2l-activity-visibility-editor-toggle.js
components/d2l-activity-editor/d2l-activity-visibility-editor.js
test/d2l-activity-editor/d2l-activity-visibility-editor.js

**Context**
[DE38928](https://rally1.rallydev.com/#/detail/defect/389129634532?fdp=true)
Fixes a bug that prevents Edge users from toggling visibility for any activity, including activity collections and assignments.
**Before (Edge only)**
**After**
**Quality**
- Existing tests for visibility editor altered

Fixing visibility editor in Edge

---

components/d2l-activity-editor/d2l-activity-competencies.js
components/d2l-activity-editor/state/activity-usage.js
components/d2l-activity-editor/state/fetch-entity.js
test/d2l-activity-editor/state/activity-usage.spec.js

Reloads the competencies entity when the competencies dialog closes. This requires forcing the fetch to bypass the entity store and cache, else it will not actually refetch. To that end I added the `bypassCache` option to the `fetchEntity` helper, which passes it on to the `EntityStore.fetch`.

US115948 Refresh competencies summary info on competencies dialog close

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-submission-and-completion.js

https://trello.com/c/ewwk53Id/188-radio-buttons-do-not-cleanly-render-in-rtl-mode

render radio buttons correctly in rtl languages

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-evaluation-editor.js
components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-container.js
components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-wrapper.js

Fixes the issue in attaching existing rubrics in Edge where an `undefined` href was being coerced into the string `undefined` which then caused the request to go 💥

Prevent undefined href from being coerced into a string

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-due-date-editor.js

Moved the label into component so it can be hidden along with the date picker.

Hide due date label when no permissions

---

components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.js

https://trello.com/c/aHg7U2Ua/184-submission-dropdown-should-be-disabled-when-submission-present

submission and completion stuff

---

components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.js
test/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.spec.js

Because the dirty/equals check sits in siren-sdk, it doesn't know that we are substituting an undefined completionType value with String(0) in activities, so the dirty check always fails. Instead, let's add a get `completionTypeValue` function to siren-sdk that can be used by both activities and the siren-sdk dirty/equals check.

DE39197 - get completionTypeValue from siren-sdk

---

components/d2l-activity-editor/d2l-activity-html-editor.js

https://rally1.rallydev.com/#/29180338367d/detail/task/394082462304
Fixes `ou={orgUnitId}` query params in the `src` of iframes (added via html editor embed) not resolving by including the `d2l_replacestring` plugin.

DE39243 Fix orgUnitId resolution for embedded iframes in HTML editor

---

components/d2l-activity-editor/lang/en.js

https://trello.com/c/LGiMTCRD/202-competencies-too-much-use-of-learning-objective-when-accordion-is-open

reduce overuse of learning objectives in competencies langterms

---

components/d2l-activity-editor/state/activity-usage.js
test/d2l-activity-editor/state/activity-usage.spec.js

Ensure FACE only displays directly associated rubrics, excluding those associated via Learning Objectives, by using the new `direct-associations` href.
Relies on:
https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/192
https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/11835/overview
https://rally1.rallydev.com/#/29180338367d/detail/userstory/391870800084

US116718 Use new direct-associations href to only get direct-associated rubrics

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js

We replace {orgUnitId} that is present in QuickLink hrefs with the actual orgUnitId.
The orgUnitId is provided by activities.

DE39243 - make orgUnitId available to be DI by d2l-labs-attachment

---

components/d2l-activity-editor/d2l-activity-competencies.js

https://trello.com/c/knoNv87x/197-competencies-edge-no-learning-objectives-not-left-aligned

align no learning objectives summary

---

components/d2l-activity-editor/d2l-activity-competencies-summary.js
components/d2l-activity-editor/lang/en.js

https://trello.com/c/LGiMTCRD/202-competencies-too-much-use-of-learning-objective-when-accordion-is-open

change collapsed learning objectives summary

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js

We replace {orgUnitId} that is present in QuickLink hrefs with the actual orgUnitId.
The orgUnitId is provided by activities.
(cherry picked from commit b2d97b5a7194b45bb3a74d67b84349be456301f1)
https://rally1.rallydev.com/#/29180338367d/detail/defect/394066581232

[Cert] DE39243 - make orgUnitId available to be DI by d2l-labs-attachment

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js

Looks like these were left over from when the save-status component was removed. It was causing some (non-breaking) console errors.

Clean up save-status component listeners

---

.dependabot/config.yml

To make visibility better, and easier to update the config settings I want to move the dependabot config into this repo, rather than relying on the dependabot UI. This will hopefully also make it easier to keep settings consistent between repos.
This is something similar to what we do in the lms https://github.com/Brightspace/lms/blob/master/.dependabot/config.yml

Added dependabot config file

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js

Remote plugin attachments were not getting the special handling that they require. 
The basic logic in this change is taken from the [AppLoader LMS code](https://git.dev.d2l/projects/CORE/repos/apploader/browse/D2L.LP.AppLoader/Apps/Loaders/IFrame/V1/Picker.js#118).
https://rally1.rallydev.com/#/29180338367d/detail/defect/394851792936

DE39307 Fix remote plugin Quicklink URL formatting

---

components/d2l-activity-editor/d2l-activity-competencies.js

Remove reliance on `margin-inline-end` which is not supported by legacy Edge.

Fix competency summary spacing on legacy Edge

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
components/d2l-activity-editor/d2l-activity-editor.js
components/d2l-activity-editor/mixins/d2l-activity-editor-container-mixin.js

Uses the `d2l-background` component as a shim to obscure the editor while saving is in progress. The shim will enable after 0.8s and fade in over the following 1.2s. It will disable instantly when a validation or save error occurs.
Due to the multitude of editors, the save action is coordinated in `d2l-activity-editor-container-mixin`. This is used in `d2l-activity-assignment-editor`, which in turn embeds the assignment-independent `d2l-activity-editor`. For the backdrop to remain independent of assignments, I added it to `d2l-activity-editor`, but in return need to tell that component when a save action is in progress. For that purpose I added a new prop, `isSaving`, to the `d2l-activity-editor-container-mixin.`, which is passed to `d2l-activity-editor` via the …

US116960 Add saving shim to activity-editor

---

components/d2l-activity-card/d2l-activity-card.js

`fastdom` is used elsewhere in this repo, but not in this component, so importing it isn't necessary.

removing unnecessary fastdom

---

components/d2l-activity-editor/d2l-activity-assignment-editor/activity-summarizer-styles.js

Running accessibility tests in https://github.com/BrightspaceHypermediaComponents/activities/pull/948 revealed a failure on an accessibility test case:
```
d2l-activity-assignment-editor-submission-and-completion
× passes accessibility test
Chrome Headless 83.0.4103.106 (Windows 10)
Error: Accessibility Violations
---
Rule: color-contrast
Impact: serious
Elements must have sufficient color contrast (https://dequeuniversity.com/rules/axe/3.5/color-contrast?application=axeAPI)
Issue target: d2l-activity-assignment-editor-submission-and-completion-editor,li:nth-child(2)
Context: <li>first submission type</li>
Fix any of the following:
Element has insufficient color contrast of 3.4 (foreground color: #868c8f, background color: #ffffff, font size: 8.4pt (11.2px), font weight: normal). Expected …
```

Fix for failing color-contrast test

---

components/d2l-activity-editor/d2l-activity-outcomes.js

Missed a case where `this.hidden` should be set to `true`. Without it, `d2l-activity-outcomes` does not have the `hidden` attribute set, and that causes the element to take up space due to padding.
`hidden` needs to be `true` when there are no alignments and we cannot update/edit alignments.
https://trello.com/c/RhZ3MjRM/211-outcomes-tag-takes-up-ui-space-when-not-visible

Fix `d2l-activity-outcomes` taking up space when nothing is rendered

---

components/d2l-activity-editor/d2l-activity-editor.js
components/d2l-activity-editor/mixins/d2l-activity-editor-container-mixin.js
components/d2l-activity-editor/state/activity-usage.js

If the alignments collection has a submit action on it, the collection is dirty.
However, checking the collection for the action involves fetching it from the entity store, which is async. Thus the `dirty` prop in the activity-usage has to become an `async dirty()` function, and requires the callers to handle promises rather than plain values.
Relies on changes to siren-sdk: https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/195
https://rally1.rallydev.com/#/29180338367d/detail/userstory/391701599076

US116679 Check for dirty alignments by checking presence of submit action on AlignmentsCollectionEntity

---

components/d2l-activity-editor/d2l-activity-html-editor.js

This should resolve the `Syntax error` issues in legacy-Edge with unbundled BSI builds.
@ryantmer I'm including you here as you worked on the [bit that originally switched this over](https://github.com/BrightspaceHypermediaComponents/activities/commit/c44b63592ec0fde96375a589c77e5d8cfbe36a05#diff-576a2f50ff8ed912df2d89abc0499942).
@dbatiste FYI as I'm hoping the new HTML editor can just use normal ES6 imports and not rely on this path-passing-around stuff.
Here's what was happening:
* This `resolveUrl` business is trying to send down an `app-path` attribute to the HTML editor, which should be something like `https://hostname/node_modules/d2l-activities`. The HTML editor then uses that to find its own assets like CSS files and such.
* Before this change, the `_resolveUrl` function was …

DE39632: resolving app root to support query-strings in import.meta.url

---

components/d2l-activity-editor/d2l-activity-conditions-editor.js
components/d2l-activity-editor/lang/en.js

[US112250](https://rally1.rallydev.com/#/110294864140d/detail/userstory/354235320832?fdp=true)
Note: I don't actually know what's considered "bad practice" these days for CSS, so let me know if anything looks bad...
Updating the styles of the RC pane in FACE to look more similar to the Rubrics pane. Screenshots after the changes:

US112250: updating FACE RC styles

---

components/d2l-activity-editor/d2l-activity-grades-dialog.js
components/d2l-activity-editor/d2l-activity-score-editor.js
components/d2l-activity-editor/state/activity-dates.js

With the new lang term loading, terms in files that are using the `d2l-activity-editor-lang-mixin.js` for i18n are referencing [this lang file](https://github.com/BrightspaceHypermediaComponents/activities/blob/master/components/d2l-activity-editor/lang/en.js) (or a respective translation). The terms in that file are prefixed, and some prefixes were missed in the original conversion.

Fix lang term keys based on changes to lang term loading for activity editor

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-annotations-summary.js

Annotation summarizer text wasn't showing up because `localize` wasn't defined.

DE39920 fix annotation summarizer text

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-type-editor.js

Fixes:
https://trello.com/c/46OKspKm/236-submission-state-individual-assignment-hide-help-text
https://trello.com/c/SxvAWIJW/237-submission-state-group-assignment-hide-help-text

remove hint text about creating groups when submissions are present

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-anonymous-marking-summary.js
components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.js
test/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.spec.js

Applies to the checkbox and the summary text.
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F407977501928

US118882 Hide anonymous marking options when submission type is in-person or on-paper

---

components/d2l-activity-editor/d2l-activity-conditions-editor.js
components/d2l-activity-editor/lang/en.js

Similar to what I did for Rubrics before... but RCs seems to work much nicer.  Tested in FF and Chrome with NVDA so far, and both seem to work reliably.

DE39843: announcing when RCs are added or removed from FACE for screenreaders

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-evaluation-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-assignment-turnitin-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.js
components/d2l-activity-editor/d2l-activity-html-editor.js
components/d2l-activity-editor/state/activity-usage.js
test/d2l-activity-editor/state/activity-usage.spec.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F399772334476
This PR implements a view when "Add/Edit Assignment Submission Folders" permission is missing.
- Read-only rich-text and non rich-text instructions
- Hide Competencies
- Hide Outcomes (hack)
- Hide Turn it in

US117892 - Part 2 - Fixing assignment read-only view (Instructions, hide competencies, hide outcomes, hide turnitin)

---

components/d2l-activity-editor/state/activity-score-grade.js

https://trello.com/c/ss2PQ5ho/232-points-string-not-translated-for-assignments-not-originally-in-grades
Defaults to the (translated) title of the numeric gradeType if the gradeType is not set initially. Previous default value was the hard-coded value `Points`.
siren-sdk PR: https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/208

Use numeric gradeType title if no gradeType is selected initially

---

components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-summary.js

[DE39269](https://rally1.rallydev.com/#/110294864140d/custom/110851118712?detail=%2Fdefect%2F394449702920&fdp=true)
Hide the summary for rubrics if the user doesn't have any permission to see rubrics 
Testing:
- Try to edit an assignment with and without an existing rubric attached but with a user that has no permissions for rubrics. The rubrics summary is hidden
- Try to edit an assignment with and without an existing rubric but with a user with full permissions for rubrics, the rubrics summary is shown

hide the rubrics summary if the user doesn't have any permissions for rubrics

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
components/d2l-activity-editor/mixins/d2l-activity-editor-container-mixin.js
components/d2l-activity-editor/mixins/d2l-activity-editor-mixin.js

This `saveOrder` property will be used to determine the order of validation and saving when the save event is triggered.
The default order will be 1000.
This PR sets the activity-assignment-editor to have a `saveOrder` of 2000 and so the assignment PATCH/save will occur after the other activity-editors.
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fdefect%2F405157847512
The problem we were having was that there was a corrupted assignment that was associated to a grade, but had no `score-out-of` value. Even when we fixed the `score-out-of` value, the assignment failed to save, because the assignment PATCH request occurred before the `score-out-of` POST, and would throw up because it saw that the assignment was associated to a grade but had no score. So this ordering …

DE39814 - Allow a `saveOrder` property to be set for each editor

---

.stylelintrc.json
components/d2l-activity-admin-list/d2l-activity-admin-list.js
components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/activity-summarizer-styles.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-annotations-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-anonymous-marking-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-availability-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-footer.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-secondary.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-submission-and-completion.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-evaluation-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-type-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-assignment-turnitin-editor.js
components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js
components/d2l-activity-editor/d2l-activity-competencies.js
components/d2l-activity-editor/d2l-activity-conditions-editor.js
components/d2l-activity-editor/d2l-activity-editor-buttons.js
components/d2l-activity-editor/d2l-activity-grades-dialog.js
components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grade-category-selector.js
components/d2l-activity-editor/d2l-activity-html-editor.js
components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-container.js
components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-editor.js
components/d2l-activity-editor/d2l-activity-score-editor.js
components/d2l-activity-editor/d2l-activity-special-access-editor.js
components/d2l-quick-eval/dismiss/d2l-quick-eval-action-dismiss-dialog.js
components/d2l-quick-eval/view-toggle/d2l-quick-eval-view-toggle-button.js
components/d2l-subtitle/d2l-subtitle.js
package.json

Adds the new [`@brightspaceUI/stylelint-config`](https://github.com/BrightspaceUI/stylelint-config) integration and makes the existing files compliant. More info in the [blog post](https://blog.d2l.dev/2020/08/04/style-linting/).
Most of the changes are reordering styles to be in alphabetical order, and renaming classes to have the required `d2l-` prefix.
One other change is to use the shared core styles for the html editor. We were previously using a copy of them from before their conversion to Lit.
There are a couple of files with the eol char has changed, so ignoring white space might make the diff more manageable.

Add stylelint integration

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-annotations-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-annotations-summary.js
components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.js
test/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.spec.js

Previously the annotations editor was being hidden completely if the edit actions is not available. With the new read-only design, this should change to show a disabled editor.

US119006 Disable annotations editor if action is not available

---

components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-container.js
components/d2l-activity-editor/d2l-activity-score-editor.js

User is required to have See and Manage ASFs and Edit Evaluation Properties permissions to modify score out of, grades, and rubrics create/add existing, and Default Scoring Rubric.
When permission is missing, this PR makes it so that out-of input is disabled, 'ungraded' button is disabled, In Grades / Not In Grades dropdown is disabled, rubrics Create New / Add Existing dropdown is disabled.
I did not need to make any changes to make remove 'x' rubric hidden or make Default Scoring Rubric dropdown disabled as that was already the behavior when the permission is missing.
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F408759753408

US119007 - FACE view when Edit Evaluation permission is missing

---

components/d2l-quick-eval/d2l-quick-eval-activities.js
components/d2l-quick-eval/d2l-quick-eval-submissions.js
package.json

This will fail until https://github.com/BrightspaceHypermediaComponents/common/pull/36 is merged and the major version bump is done - just getting the PR ready.

US114853 - Use the new d2l-hm-filter in Quick Eval

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-availability-editor.js
components/d2l-activity-editor/state/activity-usage.js
test/d2l-activity-editor/state/activity-usage.spec.js

[DE339958](https://rally1.rallydev.com/#/110294864140d/custom/110851118712?detail=%2Fdefect%2F408302156092&fdp=true)
Hide the RC header when the user doesn't have manage delivery permissions
Testing:
- remove manage delivery permissions and see that the RC header doesn't show under Availability on FACE
- give manage delivery permission and see that the RC header does show under Availability on FACE

hide the RC header when the user doesn't have manage delivery permission

---

components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-container.js

[DE39269](https://rally1.rallydev.com/#/110294864140d/custom/110851118712?detail=%2Fdefect%2F394449702920&fdp=true)
Hide the rubrics label when the user doesn't have any permissions for rubrics and there is no existing association
Tested:
- edited an assignment with an instructor that only has "See Rubrics" permission and there is no existing rubric association, the rubrics header is correctly hidden
- edited an assignment with an instructor that only has "See Rubrics" permission but there is an existing rubric association, the rubrics header is correctly shown
- edited an assignment with an instructor that has no permissions, the rubrics header is correctly hidden
- edited an assignment with an instructor that has all permission, the rubrics header is correctly shown

Kapatel/user/de39269 hide rubrics label when the 

---

components/d2l-activity-collection-editor/d2l-activity-collection-editor.js

[DE39933](https://rally1.rallydev.com/#/detail/defect/407518702772?fdp=true)
- Positions the spinner in the center of the page, regardless of the length of activities
In the future, we should also consider doing this when users add activities as well, which is why I moved the spinner to beside the list of items. This made sense to me.
- Tested on Chrome with local BSI and LMS instance

Adding greyscale filter and adjusting positioning of spinner

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-submission-and-completion.js

https://trello.com/c/5lCEIcvV/13-face-email-validation-error-always-shows-on-top

email notification error tooltip should not always be on top

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-anonymous-marking-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment-anonymous-marking.js

Two bugfixes for stuff that got missed when I moved things into their own classes (found these as I was adding tests).
I did a search through the code for any usages of `.property` to make sure there were not any others left like this (so they were all prefixed with the prop object, for example `submissionAndCompletionProps.assignmentHasSubmissions`)

Mobx refactor bugfix

---

components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
components/d2l-activity-collection-editor/lang/en.js

Context:
DE39907 - https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F407158647016
Remove in context menu for a course in a learning path does not read course name in screen readers.
Went from `Remove` to `Remove <name>`.
Testing:
Tested locally with Chrome and Windows Narrator.

updated remove button to read course name by screen reader

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.js
test/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.spec.js

[US120115](https://rally1.rallydev.com/#/detail/userstory/423726609188?fdp=true): Refactor AssignmentEditorDetail to use activity usage href and remove EntityMixinLit
~Todo:~ Done:
✔️ `attachmentsHref` should be added to the Assignment MobX state
✔️ fix the no undeclared var usage on line 165 of `d2l-activity-assignment-editor-detail.js`
https://rally1.rallydev.com/#/detail/userstory/423726609188/tasks?fdp=true

US120115 Refactor AssignmentEditorDetail

---

components/d2l-activity-collection-editor/d2l-activity-collection-editor.js

Context: 
DE39907 - https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F407158647016
https://github.com/BrightspaceUI/core/pull/815/files#diff-92c305760d9314097acce5f7b54b292bR75 adds `drag-handle-text` to get the item's name. 
Quality:
Tested locally with demo page.

DE39907 Add drag-handle-text to list-item-accumulator

---

.travis.yml

This fixed things in the my courses repo for me - everything worked locally on node 12, but failed when CI ran with node 11.

Try node 12

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F423713964720
I'm having trouble seeing the issue below, but this change may result in the issue below, where...
> the skeleton is initially being rendered before tinymce has initialized the div we provide to it to create it's contenteditable. That div is initially only about 42px and then when tinymce intializes it grows maybe because we set minrows or something on tinymce.
We shall see how this performs on QUAD.

US120109 - skeletize instructions

---

test/d2l-activity-editor/d2l-activity-availability-dates-editor.test.js

I was noticing some test flakes on these tests which I introduced a few days ago. The extra `await elementUpdated(el);` were not helping after all, but using the `waitUntil(successPredicate, failText)` helper seems to do the trick for the problematic tests.

Improve test stability for d2l-activity-availability-dates-editor

---

components/d2l-activity-editor/d2l-activity-assignment-editor/mixins/d2l-activity-assignment-lang-mixin.js
components/d2l-activity-editor/mixins/d2l-activity-editor-lang-mixin.js

Update overrides resolver to use the name/collectionName for collections instead of the resource path
This helps with resolving the issue where the cache resource path includes the BSI version which causes multiple entries in CacheStorage when using different BSI versions.
Jordan is making change in the lms to use the name or collectionName when matching with these instead of what it does currently which is to match on the resource path

US119264 OSLO: use name instead of the resource path in lang mixins

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-editor.js
components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-list.js
components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js
components/d2l-activity-editor/mixins/d2l-skeletize-mixin.js

- Based on comments in the [user story ](https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F423713966144), I made `<d2l-activity-attachments-list>` display conditionally depending on the value of `this.skeleton`. 
- In `<d2l-activity-attachments-picker>` I had to move the padding from :host to `.d2l-button-container` to get the skeleton view to take up all of the attachments container

US120110 skeletize attachments

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js
components/d2l-activity-editor/d2l-activity-availability-dates-editor.js
components/d2l-activity-editor/d2l-activity-conditions-editor.js
components/d2l-activity-editor/d2l-activity-due-date-editor.js
components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card-action-button-more.js
components/d2l-quick-eval/dismiss/d2l-quick-eval-ellipsis-menu.js

Uses new attribute on `input-date-time` to set the default time to 11:59 PM. Also cleaned up some legacy imports that were flying around.

Set date inputs default time to be end-of-day

---

components/d2l-activity-editor/d2l-activity-editor.js

https://rally1.rallydev.com/#/detail/userstory/408693111172?fdp=true
**This removes the logic that shows the "Loading..." text and shim** to observe the `skeleton` behaviour

US118988 Disable assignment loading shim to see skeleton loading

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js

Allow immediate rendering of editor before any data has loaded.
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F423713959428

Enable immediate render of assignment editor for skeleton behaviour

---

.travis.yml

it was there before so i could get a pulse on how the build was going

no longer notify me via email

---

components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment-type.js

The `entity.isAssignmentTypeReadOnly` is always `undefined`, because it's supposed to reference `canEditAssignmentType` instead.
https://trello.com/c/IAuUOFA2/2-assignment-type-not-properly-disabled-when-submission-present-or-user-lacks-permission

CanEditAssignmentType was always incorrectly being set to true

---

.gitignore
components/d2l-activity-editor/mixins/d2l-activity-editor-container-mixin.js

https://trello.com/c/eaKbY60m/252-new-date-time-inputs-do-not-get-focus-on-validation-error
The new validation workflow delays the setting of the aria-invalid property by a little bit, so we need to wait for the editor to finish updating before checking the invalid state.

Fix date pickers not being focused on after error

---

components/d2l-quick-eval/d2l-quick-eval-submissions.js
package.json
scripts/remove_attest_from_project.js
test/d2l-activity-card/d2l-activity-card-test.js
test/d2l-activity-evaluation-icon/d2l-activity-evaluation-icon-base.js
test/d2l-activity-evaluation-icon/d2l-activity-evaluation-icon.js
test/d2l-activity-list-item/d2l-activity-list-item-test.js
test/d2l-quick-eval/behaviors/d2l-quick-eval-siren-helper-behavior.js
test/d2l-quick-eval/behaviors/d2l-quick-eval-telemetry-behavior.js
test/d2l-quick-eval/behaviors/d2l-siren-helper-behavior.js
test/d2l-quick-eval/d2l-quick-eval-activities.js
test/d2l-quick-eval/d2l-quick-eval-submissions-table-sorting.js
test/d2l-quick-eval/d2l-quick-eval-submissions-table.js
test/d2l-quick-eval/d2l-quick-eval.html

`eslint` version is behind and Dependabot pull request  #1107 failed because of unnecessary `var` instantiations. These have been converted to `const` and `let`.

Remove references to var keyword

---

components/d2l-activity-card/d2l-activity-card.js

For DE39598
https://rally1.rallydev.com/#/357252275780d/custom/367300408400?detail=%2Fdefect%2F399579266472
Card Metadata now centers because the overflow caused by long strings now was solved by wrapping the content to the next line.
See difference below
Before:
After:

Strings that are too long for a card now wrap

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js

The file type returned is `D2L.LP.Web.UI.Files.File`.
The RecordVideoDialogCallback used to return the file type `D2L.Files.FileInfo`.
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fdefect%2F435554744700

DE40565 - handle callback after adding video or audio

---

components/d2l-quick-eval/behaviors/d2l-siren-helper-behavior.js
test/d2l-quick-eval/behaviors/d2l-siren-helper-behavior.js

This changes affects the information that is send back from the evaluation pages when they return to Quick Eval, allowing Quick Eval to maintain the previous selected sort, filter and search.
It will allow the new evaluation routes to handle query string params easily.
Before:
?filter=eyJmMmIzMmYwMy01NTZ&sort=eyJTb3J0cyI6W3s0&collectionSearch=eddie
After
?cfi=filter_eyJmMmIzMmYwMy01NTZ-sort_eyJTb3J0cyI6W3s0-collectionSearch_eddie
Legacy LMS pages are been changed at the same time to handle the new single param

US120338 - Group filter, sort and search extra params inside one single query string param

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js

The file type returned is `D2L.LP.Web.UI.Files.File`.
The RecordVideoDialogCallback used to be `D2L.Files.FileInfo`.
(cherry picked from commit aa9cc591c15c06dafd57ae044da7b56f3b21c33e)

[cert 20.20.10] DE40565 - handle callback after adding video or audio

---

components/d2l-activity-editor/d2l-activity-html-editor.js
components/d2l-activity-editor/d2l-activity-text-editor.js

Related to [US120640](https://rally1.rallydev.com/#/388869855380d/dashboard?detail=%2Fuserstory%2F436813346276)
`d2l-activity-text-editor` does not respond to value changes because the html editor maintains it's own state. 
With the addition of the unique `key` property, we can use it to track whether the component should be updated or not.

Add key identifier for component to update

---

components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js

Same thing we did in LX [here](https://github.com/BrightspaceHypermediaComponents/sequences/pull/271), just applying similar logic to new face content editor.

Override scroll property in content-editor so we don't get unnecessary scroll bar

---

components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-availability-editor.js
components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-footer.js
components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
components/d2l-activity-editor/lang/en.js
components/d2l-activity-editor/state/activity-score-grade.js

Integrating our content editor with `activity-store.js`. This file/store gives us boilerplate access to standard `activity-usage` properties in the store so that we can integrate with shared components like `d2l-activity-availability-dates-editor` and `2l-activity-availability-dates-summary`. These components integrate with `activity-store.js` to both access and set values on the activity usage entity. Gives us a lot of functionality with doing almost no work! 
**Note** had to fix an error being thrown when loading a new `activity-usage` into the store that naively assumed the `activity-usage` entity would always have score/grade information. This needed to be fixed for the `ObjectStore` to properly load the entity into state so that other components could access it. I know this is …

Integrate content editor with activity store to get visibility and availability features for free

---

components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js

Adjusting `css` so that the primary slot can scroll when description gets larger. Also setting `body.overflow` to `auto` so that when the window re-sizes and the `secondary` slot gets added below the `primary` slot, the user can scroll the body tag and still see all the content. If it was set to `hidden` the user would not be able to scroll and see any of the content in the `secondary` slot of the FACE template. (where the availability dates stuff is)
Related to [this issue](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fdefect%2F438541484248) where editing the description to make it very long hides the name field.

Allow primary slot and body tag to scroll

---

components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-container.js

This PR closes:
> [DE40535](https://rally1.rallydev.com/#/detail/defect/435207584720?fdp=true): Floating buttons in rubric no longer float
There is a problem where after the 20.20.8 release the rubric buttons would not "float" and stick to the bottom of the page as you scroll. This issue was fixed by including the necessary imports for the components used.
1. Navigate to `Assignments > New Assignment > Add rubric > Create New`
2. Observe buttons are not visible.
1. Navigate to `Assignments > New Assignment > Add rubric > Create New`
2. Observe buttons are visible. Behaviour matches 20.20.7 behaviour
Speaking with Dave Lockhart:
> Starting in 20.20.8, BSI builds went unbundled. Before that, we built all our components together and producing just a few very large (~700 KB) files that our …

DE40535: Floating buttons not floating in rubrics

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor.js

Based on [US119464](https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F413205972020). `ActivityEditorTelemetryMixin ` is already implemented in` d2l-activity-editor` so it seems to just be a matter of passing through type/telemetryId.
Tested the endpoint manually on postman with the following payload (received 201 response which matches response on quad assignments):
`{
"EventType": "PerformanceEvent",
"SourceId": "quiz",
"Date": "2020-10-07T20:04:06.088Z",
"EventBody": {
"EventTypeGuid": "02a00ca0-e67d-4a6c-908b-ee80b8a61eec",
"Action": "LoadView",
"Object": {
"Id":
"https://beb93036-1642-437f-8460-2db5fbdf1e65.activities.api.dev.brightspace.com/activities/6606_51000_231/usages/6606",
"Type": "quiz"
},
"UserTiming": [
{
"name": …

Added values for telemetry performance

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-annotations-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-annotations-summary.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-anonymous-marking-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-anonymous-marking-summary.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-submission-and-completion.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-evaluation-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-type-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-type-summary.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-submission-email-notification-summary.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-assignment-turnitin-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-assignment-turnitin-summary.js
components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment-store.js
components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-container.js
components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-editor.js
components/d2l-activity-editor/state/activity-usage.js
test/d2l-activity-editor/state/activity-usage.spec.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Ftask%2F440737138828
By using the specialization rel to get the assignment href from the activity usage we no longer need to use the `AssignmentActivityUsage` siren-sdk entity which means we can simplify the loading of the `d2l-activity-assignment-editor` and the `assignment-store`. 
Most of the changes are just updates to dependent classes to change calls from `store.getAssignment(href)` to just `store.get(href)` and to update imports of the store object.
**Just pay attention to the second commit on this PR - This was branched from a previous PR which has now been merged, so I'm confused why the commits from that original PR are still showing up on this one. I thought Github was smart enough to handle this. I'm sure I've …

Part 2: Use activity usage specialization rel to get assignment href from activity and simplify mobx assignment store

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js

This is used by the consistent eval save logic

send file detail on video and audio note recorded events

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-secondary.js
components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-availability-editor.js
components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor-secondary.js
components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor.js
components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js

This adds the accordion for availability dates & conditions according to [US121271](https://rally1.rallydev.com/#/29180338367ud/iterationstatus?detail=%2Fuserstory%2F440730104040). 
Note it does not skeletize yet, as it needs to be able to load something for the skeleton to disappear, so that will be added with the story that actually loads/saves the dates info.

Us121271 add availability accordion for quiz

---

components/d2l-activity-editor/d2l-activity-availability-dates-editor.js
components/d2l-activity-editor/d2l-activity-due-date-editor.js
components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-availability-editor.js

As per Joseph, for quizzing (and eventually for assignments) the default start time should be 12AM.
I'm not a big fan of this approach as it's quite specific to just start date. What happens if we want to make the end date dynamic for example? Do we keep adding new properties? 
I believe this is just a temporary solution as eventually assignments will also adopt this default start time and it will no longer need to be dynamic.
Also wondering if it's better to have a fallback time e.g. `${this.startDateDefaultTime || 'endOfDay'}` or if it would be preferred to avoid the fallback and explicitly set the start time for each component?

Updated default quiz date/ times to 12am

---

components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
components/d2l-activity-editor/lang/en.js

- When creating a new content item, the user should see the subtle button saying "Add Due Date". Once clicked, the due date field will appear.
- When editing, the user should see the "Add Due Date" button if a due date has not yet been added. Otherwise, the due date field should appear and show the selected due date. Note that this has not properly been tested yet since we haven't implemented loading in the edit view. Will be confirmed and fixed if necessary once this is implemented.
- The due date field does indeed appear to save on the activity-usage entity and should be visible in areas where implemented. 
UPDATE: refactored some logic so we see loading skeletons until content entity is loaded into state so you don't see a weird delay before the field value appears. Also had to set …

Add due date to face create view for content modules + edit description and loading skeleton fix

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-availability-editor.js

Based on [US121708](https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=/userstory/448686592196).
I had thought of removing the `startDateDefaultTime` property completely and having the default start time set at the activity level to ensure consistency across all current/future activities however the content tool has their default set to 11:59pm and I did not want to introduce any changes that affect other teams.

Added 12am as start date for assignment date picker

---

components/d2l-work-to-do/d2l-work-to-do-activity-list-item-basic.js
components/d2l-work-to-do/d2l-work-to-do-activity-list-item-detailed.js
package.json

Once this is merged, we can remove the `actionHref` and link stuff that's currently baked directly into `ListItemMixin`.

Use ListItemLinkMixin for custom work-to-do list item.

---

components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/state/content.js

Deletes the module when canceling the creation of a new item. 
**Related PRs**:
- https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/226
- https://github.com/Brightspace/lms/pull/3414

Delete module on cancel

---

components/d2l-activity-editor/mixins/d2l-activity-editor-container-mixin.js

This allows us to display the opaque saving overlay for the entirety of saving, closing, and navigating away from the editor.

Dont reset isSaving to allow for saving state to persist beyond save function

---

components/d2l-activity-editor/d2l-activity-availability-dates-editor.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fdefect%2F458394411452
When a user has their font size set to small the date picker inputs render side by side instead of stacked which causes them to be misaligned. 
This fix forces a single column, stacked layout regardless of font size which corrects this defect. I ran this change by Joseph to ensure it met the design doc and he was happy with it.
I had thought of applying media queries but this seemed like the simplest fix.
With this styling applied the layout should always display in a single column:

Force date pickers to render in a column to avoid spacing bug

---

components/d2l-activity-editor/d2l-activity-accordion-collapse.js

Defect fix based on this trello item https://trello.com/c/pXTHX0jK/266-fix-summarizer-spacing.
I believe this defect was introduced during [a refactor](https://github.com/BrightspaceHypermediaComponents/activities/pull/1152/files) to create an accordion wrapper which meant that the css selectors were no longer targeting the slotted `li` elements. From a quick [bit of reading](https://developer.mozilla.org/en-US/docs/Web/CSS/::slotted)/experimenting with the `::slotted()` selector I tried this approach which seems to correctly target the `li` elements. 
Not sure if there's a preferred way to target slotted elements. 
Before 
After

Changed css selectors to target slotted elements

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-availability-editor.js
components/d2l-activity-editor/d2l-activity-availability-dates-editor.js
components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-availability-editor.js

Setting start time to 12am for all availability editors. Removing unnecessary property as we all use the same start time now. 
Related PR: https://github.com/BrightspaceHypermediaComponents/activities/pull/1181
Rally ticket: https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F459132218232
@ronan-f adding you as reviewer as you recently set the start time for assignments/quizzes to 12am. Tested it in assignments and it works fine. 
Content experience:
Assignment experience:

Set default start time to 12am for all availability editors

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-disable-pager-and-alerts-summary.js
components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-timing-and-display-editor.js
components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js

[US121861](https://rally1.rallydev.com/#/detail/userstory/449846810872?fdp=true): [ui] Summarizer: block alerts
```
Summarizer text displays, "Alerts and communication blocked" when block alerts and communications is checked.
Rules below:
Accordion:  Timing & Display
Not active / default text:  Show nothing
Active state:
"Alerts and communication blocked"
Other:
Ensure summarizer text is skeletonized on load
"Alerts and communication blocked" will be the third summary text item on the accordion.
Summary text order should match field ordering i.e. should appear beneath "Hints allowed" and/or "Right clicks disabled" if they are shown.
```

US121861 Quizzes: Add summarizer for disable pager and alerts

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-annotations-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-anonymous-marking-editor.js
components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-disable-pager-and-alerts-editor.js
components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-disable-right-click-editor.js
components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-hints-editor.js
components/d2l-activity-editor/styles/checkbox-styles.js

Clean up before adding another checkbox to quizzing.
Refactored shared checkbox styles following the pattern [documented by LitElement ](https://lit-element.polymer-project.org/guide/styles#sharing-styles).

Refactored shared checkbox styles

---

.github/workflows/ci.yml
.github/workflows/release.yml
.travis.yml
README.md
package.json
wct.conf.json

As discussed in Slack, this converts the Test & Release workflows from Travis CI -> GitHub Actions. @svanherk is still working on a visual-diff action, but I think this can run in hybrid mode (most things in GHAs, Visual Diff in Travis) temporarily. We shall see!
Look over the instructions in the README to make sure everything is clear. `semantic-release` is going to be a change from your current workflow where the patch version increases automatically each time you merge. You'll need to start including `feat: blah blah` or `fix: blah blah` in your commit messages or squash merge commits to trigger releases.
Also your workflow for release branches will need to change slightly as the branch names semantic-release uses need to be of the form `1.x` or `1.5.x` so keep that in mind.

Switch test & release to GitHub Actions

---

.travis.yml

For the visual-diff "Regenerate Goldens" button to work, it searched for "Stage 2: Visual-difference-tests" -- which means it can't be the first and only stage. 🤦 
This is just a temporary measure until the visual-diff GitHub Action is ready.

adding empty stage

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor-detail.js
components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.js
test/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.spec.js

Part of https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F459179692392
For now it's assumed that users can always view a quiz preview...in future stories this will be restricted by permissions etc.
The siren-sdk PR that exposes preview href can be found [here](https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/238).

US122707 Add quiz preview href

---

components/d2l-activity-editor/d2l-activity-notification-email-editor.js

The host passes a value to this component as notification value comes from the quiz or assignment store and not from the activities store. And so this component doesn't actually retrieve any values from stores. The import was left over from when I was moving it around from quizzing to the more generic activity folder.

Cleanup unused store

---

components/d2l-activity-editor/d2l-activity-conditions-editor.js

I initially made the "Add Release Condition" button hidden when user doesn't have permissions to add conditions, but it's supposed to be visible but disabled, so this PR fixes that.

feat: US119477: make add button readonly when can't edit

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-outcomes.js

Based on [this trello card](https://trello.com/c/Yx8JT17F/7-face-standards-link-has-an-extra-delay-in-showing-up-exceeding-testcafe-timeout).
This PR is designed to address the skeleton loading of standards and ensure we the assignment detail component stays in "skeleton mode" until alignments have finished loading.
This is accomplished by dispatching a 'pending' event which is handled by the `asyncContainerMixin` so that the detail component knows to continue displaying the skeleton view.
After a discussion with @emil-furniss we also thought that it made sense for `d2l-activity-assignment-editor-detail` to control the hidden state of `d2l-activity-outcomes` and have that based on the skeleton state rather than `d2l-activity-outcomes` trying to manage it's own hidden state internally. …

Dispatching async event when loading alignments

---

components/d2l-quick-eval/d2l-quick-eval-submissions-table.js
components/d2l-quick-eval/d2l-quick-eval-submissions.js

[DE36105](https://rally1.rallydev.com/#/detail/defect/336288465200?fdp=true): A11y - Quick Eval Submissions Table - Screen reader is not reading out the header names when more than one sortable object in the header (e.g. First name, Last name)

add hidden span for name column

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js

See: https://trello.com/c/9r5lB48J/274-face-assignments-audio-video-fails-to-attach
> I think it's because this is storing the file in an array in `files`
https://github.com/BrightspaceHypermediaComponents/activities/pull/1205/files#diff-bfdd45cba209e9d6b9a6c4035f88d0893b72255673353a34b4fd39f33d3cd951R131
and this is looking for it in
`e.detail.file` https://github.com/BrightspaceHypermediaComponents/activities/pull/1205/files#diff-8fb51195a645ae0ccaf34162ad052073e0ab93377c35b6b42001687672f2228aR82
It needs to be `const file = e.detail.files[0]`
Same for video
The change was merged in December, so the defect will appear in 20.21.1 builds, but not 20.20.12

Fix audio and video attachments not attaching

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-type-editor.js

https://trello.com/c/0kvcVuBm/3-course-with-no-groups-missing-no-groups-exist-create-new-groups-in-the-groups-tool-under-assignment-type
Should always show `No groups exist. Create new groups in the Groups tool.`, unless Groups exist.
Also nudged the `Create new groups in the Groups tool` to align with the Group Category dropdown selector.

Fix: FACE Assignments - no help/info text below 'Individual Assignment'

---

components/d2l-work-to-do/d2l-work-to-do-activity-list-header.js

Previously we allowed the fullscreen view count to go above 99 (completely unbounded, but for consistency we would like for the count to stop at 99 just like it does in widget view.
See rally story: https://rally1.rallydev.com/#/357251704080ud/custom/367300408400?detail=%2Fuserstory%2F460541049668

Activity header count should read "99+" in both views

---

components/d2l-activity-editor/d2l-activity-usage-conditions-editor.js

Fix defect which always renders dirty check dialog

Returning entity.dirty() instead of entity.dirty

---

components/d2l-activity-editor/mixins/d2l-activity-editor-dialog-mixin.js
test/d2l-activity-editor/mixins/d2l-activity-editor-dialog-mixin.js

@dustxd and I noticed that certain buttons had a default action attached depending on how they were rendered which caused funky behaviour especially with the checkboxes. In our case we rendered a "?" button as a child of a `d2l-input-checkbox` component. This meant that it inherited a click handler which caused the value of the checkbox to change when clicking on the "?" button. Preventing the default action and instead only running the dialog open open code fixed the problem. 
An alternative to this would be to change the how our elements are rendered/structured but we found that meant we'd have to write a bunch of custom css to get things to look the same. This _seemed_ like a simpler solution.
We don't need the same thing on the close handler as the close event is predictably managed …

Added prevent default to skip default behaviour

---

components/d2l-work-to-do/d2l-work-to-do-activity-list-item-basic.js

[DE41702 - Links are not clickable in the widget](https://rally1.rallydev.com/#/357251704080ud/workviews?detail=%2Fdefect%2F463973680764&view=1dbdf7ff-337f-4c24-b34a-19155082c9dc)
It looks like Linking was moved to a separate mixin recently: https://github.com/BrightspaceUI/core/commit/cb806eb6347b3331a024ebb63ca588d463a6252b
So this should restore the original behavior. Demo:

Fix for DE41702 - make links clickable in work-to-do widget

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-disable-pager-and-alerts-editor.js
components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-disable-right-click-editor.js
components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js

* Added help dialog using Mixin for state management
* Laid out `d2l-input-checkbox` and `d2l-icon-button` side by side to fix alignment issues caused by the height of icon button being taller than the text
* Added custom css
(Credits to @ronan-f for looking into this with me!)
* This solution does not work well with long lang terms (see this [PR](https://github.com/BrightspaceHypermediaComponents/activities/pull/1267)) as it lays out the question mark icon button side by side instead of wrapping it to the end of text
* There's extra spacing on the top and bottom due to the height of the icon button being taller
https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F461234386024

Added help dialog for quizzing disable right click editor

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js
components/d2l-activity-editor/d2l-activity-attachments/state/attachment-store.js
components/d2l-activity-editor/d2l-activity-attachments/state/attachment.js
test/d2l-activity-editor/d2l-activity-attachments/state/attachment.spec.js
test/d2l-activity-editor/d2l-activity-attachments/state/attachment.store.spec.js

Current audio/video attachment experience is:
- user clicks on a video and must download an html file
- file contains a link, which they must click
- link takes them to a page in the lms to view the media
This PR adds support for handling links which store a URN which points to an audio or video resource. The new experience is:
- user clicks on a video and is taken to the media player in a new tab
Future work will add audio/video embedded player. Storing the media as URNs decouples the storage from the mode of playback.
Related: https://github.com/Brightspace/lms/pull/4695

US123107: Support handling Audio/Video attachments as links which store URNs

---

components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker-presentational.js

Fix issue where Primary-Secondary template separator would cut off the tooltip of the add-attachment button
Before:
After:

fix: Add alignment to tooltip for ActivityAttachmentsPickerPresentational

---

components/d2l-work-to-do/d2l-work-to-do-activity-list-item-detailed.js

Replicated fix from #1280 to fullscreen view. Tested by going to `/d2l/le/worktodo/view` manually on my test environment and confirmed that links (other than Content, known/separate issue) were working.
Rally case for context: https://rally1.rallydev.com/#/357251704080ud/custom/367300408400?detail=%2Fdefect%2F463973680764

Fix: links were not clickable in fullscreen view

---

components/d2l-activity-editor/mixins/d2l-activity-editor-container-mixin.js

https://trello.com/c/bsg7Fb6D/290-save-in-place-saved-assignment-gets-deleted
The `isNew` property needs to be set to false on save-in-place, so that a net-new activity does not get deleted after clicking cancel or back _after_ saving-in-place.

US123218 Do not delete new activity after save-in-place

---

components/d2l-work-to-do/d2l-work-to-do.js

Immersive navbar was overlapping the title of the fullscreen view instead of pushing the content down, so I added padding to compensate. I'm sure there's a cleaner way to do this, but I couldn't think of one and wanted to get this out ASAP.
See rally story: https://rally1.rallydev.com/#/357251704080ud/custom/367300408400?detail=%2Fuserstory%2F460369362992

Immersive navbar top padding

---

components/d2l-work-to-do/d2l-work-to-do.js

See rally: https://rally1.rallydev.com/#/357251704080ud/custom/367300408400?Name=Full%20page%20padding&Priority=Normal&Project=%2Fproject%2F357251704080&Requirement=%2Fhierarchicalrequirement%2F463435916636&detail=%2Fdefect%2F482551412748&iteration=u&parentRef=%2Fhierarchicalrequirement%2F463435916636&rankTo=BOTTOM
I moved the immersive navbar to be at the top level of fullscreen view instead of having a duplicate for each collection component, which was causing it to set aside extra space for the navbar for each of these components. This also undoes #1318 , because now that we're putting the immersive navbar in the correct spot, it allocates its own space at the top of the page and we no longer need to add extra padding there ourselves.

W2D: fix/remove extra padding for fullscreen view

---

components/d2l-activity-editor/d2l-activity-outcomes.js

https://trello.com/c/F5wKvedY/287-face-assignments-outcomes-editor-taking-up-page-space-when-not-displayed
When there are no alignments and user lacks permissions to update alignments, hide the activity-outcomes component to prevent styles (`padding-bottom: 20px`) being applied to an editor component with no content. This fixes the spacing problem it otherwise creates.

fix: FACE Assignments activity-outcomes rendering

---

components/d2l-work-to-do/d2l-work-to-do-activity-list-item-basic.js

On hover, w2d list items should have blue text, icon, and underline.
There seems to be a bug with list item mixins that always attaches the `action-href` attribute to items regardless of the value of `actionHref`. It also looks like it should be a string but is acting like a boolean. Very possible the issue is on the w2d side and it's not just keeping it in sync properly. This will be investigated separately.
Fixes:
https://rally1.rallydev.com/#/357251704080/custom/367300408400?detail=%2Fuserstory%2F464524577208&fdp=true?fdp=true
Follow-up:
https://rally1.rallydev.com/#/357251704080/search?detail=%2Fdefect%2Fa485c086-0783-44b4-9c8c-67d820148a06&keywords=background%20hover&fdp=true?fdp=true

Fix hover state of w2d list items

---

.github/workflows/ci.yml
test/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js

Undo changes needed to get a hotfix in: https://github.com/BrightspaceHypermediaComponents/activities/pull/1359

fix: Skip failing attachment tests & add back Saucelabs tests

---

components/d2l-work-to-do/d2l-work-to-do-activity-list-item-basic.js
components/d2l-work-to-do/d2l-work-to-do-activity-list-item-detailed.js

Rally ticket: https://rally1.rallydev.com/#/357251704080ud/workviews?detail=%2Fuserstory%2F480172231796&view=b064b584-6337-43c1-b9a9-28047568284d
tl;dr some items (e.g. course content, surveys) have a `title` instead of a `name`, so we should check for that before defaulting to the `type`
I changed the ternary operators to if statements because there was yet another condition to check for, which made it more complex - this seems easier to follow, if also more wordy.

W2D: use title property instead of name for content

---

components/d2l-work-to-do/d2l-work-to-do-activity-list-item-basic.js
components/d2l-work-to-do/d2l-work-to-do-activity-list-item-detailed.js

https://rally1.rallydev.com/#/357251704080ud/workviews?detail=%2Fuserstory%2F480173614388&view=b064b584-6337-43c1-b9a9-28047568284d
Context is in the Rally case as well, but broadly: we now have 3 different `text/html` links, so `getLinkByType` wasn't narrowing down enough to get us the link we actually want. I _think_ the one I get here, with the `alternate` href, is correct because in testing clicking that link would go directly to the piece of content.

W2D: content links now go directly to content

---

components/d2l-activity-editor/d2l-activity-content-editor/constants.js
components/d2l-activity-editor/d2l-activity-content-editor/web-link/state/content-web-link.js

Now that the [serializer returns an empty url](https://github.com/Brightspace/lms/pull/5624), we no longer need to check in the front end if the link is the default link.
Initial PR with discussion: https://github.com/BrightspaceHypermediaComponents/activities/pull/1403
PR modifying the serializer: https://github.com/Brightspace/lms/pull/5624

DE42132: removing all traces of defaultPlaceHolderLink

---

components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
components/d2l-activity-editor/d2l-activity-editor.js

https://rally1.rallydev.com/#/29180338367ud/iterationstatus?detail=%2Fuserstory%2F483572068152&fdp=true
This moves the setting of the body's overflow style to the activity-editor, since we want this fix in all activity-editor pages, not just activity-content-editor.

fix: US124019 remove scroll bar from all activity-editor pages

---

components/d2l-activity-editor/d2l-activity-content-editor/module/state/content-module.js
components/d2l-activity-editor/d2l-activity-content-editor/web-link/state/content-web-link.js

This is something I noticed for both weblinks and modules while [making this PR](https://github.com/BrightspaceHypermediaComponents/activities/pull/1403) for [this defect](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fdefect%2F486166661432&fdp=true) (which was specific to new weblinks).
If you go to an existing weblink OR module, modify it in someway, hit 'Save', then press 'Cancel' or 'Back', a popup launches saying "Are you sure you want to discard your changes?", even though there are no changes to be discarded.
This is because the loaded entity doesn't have the updated saved values. Any comparison done (which, if there is a difference found between the saved values and values in the inputs, launches the popup) will always be with the values on page load, not …

DE42132: Clicking Back/Cancel on modified saved weblinks/modules launches warning popup

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor-detail.js

After the addition of a `disabled` property, the new html editor was not rendered correctly on FACE pages. This happened because the value of the passed-in disabled property was based on a property that is initially `null`, which caused disabled to be initially true, which meant tinymce didn't have the proper component rendered on `init`. Ensuring disabled is initially set to false allows tinymce to initialize correctly.

fix: US123716 new html editor was not rendering correctly in FACE pages.

---

components/d2l-activity-editor/d2l-activity-score-editor.js

On save-in-place, the activity-usage entity is reloaded which re-instantiates the ActivityScoreGrade (from [here](https://github.com/BrightspaceHypermediaComponents/activities/blob/4af04474a3b577b096853529283f81446763b24f/components/d2l-activity-editor/state/activity-usage.js#L39)). This clears the state, so that the `ActivityScoreGrade.newGradeName` is `undefined` if the score-out-of is [saved](https://github.com/BrightspaceHypermediaComponents/activities/blob/4af04474a3b577b096853529283f81446763b24f/components/d2l-activity-editor/state/activity-usage.js#L187) after that.
Calling save with an undefined `newGradeName` throws a 400 error.
Since no props on the components are actually changing, this resets the `newGradeName` when the d2l-activity-score-editor component is updated without …

DE42174 Fix score-out-of throwing error on save after save-in-place

---

components/d2l-activity-editor/d2l-activity-html-new-editor.js
package.json

We introduced a breaking change here to align how labeling works with our other input components. Once this is merged, BSI will be updated accordingly to minimize violent explosions. 😅

Update @brightspace-ui/htmleditor component to v1

---

components/d2l-activity-editor/d2l-activity-editor.js

Had to set the overflow of the `html` tag for FF to pick it up on initial load of Assignments page.

US124019 fix FF issue

---

components/d2l-activity-editor/d2l-activity-outcomes.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=/defect/486581000692
Implemented Martin's solution for standards/alignments loading. Looking at the network tab I cannot see this adding any additional requests. 
The result is that the standards button renders in sync with the end of the skeleton loading but the tags are still slightly delayed:

Moved management of _alignmentsHref to outcomes component

---

components/d2l-activity-editor/d2l-activity-availability-dates-editor.js
components/d2l-activity-editor/d2l-activity-due-date-editor.js
test/d2l-activity-editor/d2l-activity-availability-dates-editor.test.js

Based on this trello card: https://trello.com/c/79bACFo0/301-when-missing-delivery-permissions-date-fields-are-hidden-instead-of-disabled
The idea is that if a user doesn't have permissions to edit dates then it will show as a read only picker instead of not rendering at all. 
Without content:
With content:
I noticed `d2l-activity-availability-dates-editor` is being used by Assignments, Quizzing and Content so should probably get someone from the Content team on this PR as well.

Changed date pickers to render as disabed if user lacks permissions

---

components/d2l-quick-eval-widget/d2l-quick-eval-widget-controller.js

Fix for 500 errors when clicking on discussions in quick-eval-widget

Identify links from quick-eval-widget as coming from quick-eval

---

components/d2l-activity-editor/d2l-activity-content-editor/web-link/d2l-activity-content-web-link-url-preview.js

fix: I am so smart! SMRT!
This small indent fix will create a new patch release that includes the changes from https://github.com/BrightspaceHypermediaComponents/activities/pull/1402

fix: preview web links skeleton

---

components/d2l-quick-eval-widget/d2l-quick-eval-widget-controller.js

Using the same weird workaround from [this function in quick-eval](https://github.com/BrightspaceHypermediaComponents/activities/blob/6269ee819b7d718abcd626037ff851a209d4f394/components/d2l-quick-eval/behaviors/d2l-quick-eval-siren-helper-behavior.js#L175) to add a search param to a relative url. Fixes it throwing an error because the `URL` constructor expects a base for relative paths.

Using placeholder to format evaluation href

---

components/d2l-work-to-do/d2l-work-to-do-activity-list-item-basic.js
components/d2l-work-to-do/env/index.js

https://rally1.rallydev.com/#/357251704080d/custom/367300408400?detail=%2Fdefect%2F486936639864&fdp=true?fdp=true
Allow for a list of rels to sequentially follow when fetching an item's entity.
This is to allow for following entities like user enrollments that link to an organization.
Added linkRel to environment to specify a REL that the item's href should use.
Added config to hide org information for some entity classes, and hide the information for course offerings.

fix: DE42230: Allow rel path for w2d entity fetch.

---

components/d2l-work-to-do/d2l-work-to-do-activity-list-item-basic.js
components/d2l-work-to-do/d2l-work-to-do-activity-list-item-detailed.js
components/d2l-work-to-do/lang/en.js
components/d2l-work-to-do/lang/es.js
components/d2l-work-to-do/lang/fr.js
components/d2l-work-to-do/lang/ja.js
components/d2l-work-to-do/lang/ko.js
components/d2l-work-to-do/lang/nl.js
components/d2l-work-to-do/lang/pt.js
components/d2l-work-to-do/lang/sv.js
components/d2l-work-to-do/lang/tr.js
components/d2l-work-to-do/lang/zh-tw.js
components/d2l-work-to-do/lang/zh.js

For context, we want to show "Starts (Month) (Date)" for items that start in the future, because otherwise people who see them in W2D would be confused why they aren't clickable. 
See: https://rally1.rallydev.com/#/357251704080d/workviews?detail=%2Fuserstory%2F483215752572&view=b064b584-6337-43c1-b9a9-28047568284d&fdp=true?fdp=true
Note: the `d2l-status-indicator` component doesn't exactly match the mockups (note that the production version has the text in all caps). I'm inclined to use the component as-is because it's probably consistent with other, similar places in Brightspace

W2D: show Start Dates in the future

---

components/d2l-work-to-do/d2l-work-to-do-activity-list-item-basic.js
components/d2l-work-to-do/d2l-work-to-do-activity-list-item-detailed.js
components/d2l-work-to-do/d2l-work-to-do.js

Somewhat dependent on https://github.com/BrightspaceUI/core/pull/1076
Refactors the way links and icons are styled, `actionHref` is set, and restores the link background color on hover.

Clean up w2d styles and actionHref logic

---

components/d2l-work-to-do/d2l-work-to-do-activity-list-header.js

I used `resizeObserver` to listen to size changes on the list header and show long or short month names accordingly. I did not use the [polyfill](https://www.npmjs.com/package/resize-observer-polyfill) as it was not already part of the repo and this is not critical functionality. This means it will not work in legacy Edge and Firefox on Android only. Tested in Chrome, Edge (Chromium), and Firefox and seems to work fine. Safari should be tested, though any failure should fall back to existing long month names.
It's possible that doing calculations on the width to convert to `rem` would be beneficial, though I did not see any evidence of this in my tests.

Abbreviate months when header is too narrow

---

components/d2l-activity-editor/d2l-activity-content-editor/shared-components/d2l-activity-content-editor-title.js
components/d2l-activity-editor/d2l-activity-content-editor/web-link/d2l-activity-content-editor-link.js
components/d2l-activity-editor/error-handling-mixin.js

[Rally defect link](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fdefect%2F486456166756&fdp=true?fdp=true)
The `ErrorHandlingMixin.setError()` function lets you provide a `tooltipId` that it will show even if the input no longer has focus and isn't being hovered. This means that the tooltip is rendered before the `d2l-activity-editor` re-renders itself and adds the alert, so the tooltip stays in the spot it was originally rendered.
Here I'm not passing in the `tooltipId` to the `ErrorHandlingMixin.setError()` function so that the tooltip is not rendered if the user isn't focused on the input or hovering over it. When the error happens, the `d2l-activity-editor` component (through the `ActivityEditorContainerMixin`) still focuses on the input on save when …

DE42177 - tooltip is out of position when saved and there is an error

---

components/d2l-activity-editor/d2l-activity-content-editor/web-link/d2l-activity-content-editor-link.js
components/d2l-activity-editor/d2l-activity-content-editor/web-link/d2l-activity-content-web-link-url-preview.js
components/d2l-activity-editor/d2l-activity-content-editor/web-link/helpers/url-validation-helper.js

If the user enters a url and then deletes it, the preview should disappear.
The way this is all configured, is that preview will update when the url is valid. However, an empty link: `""` is technically an "invalid" url. This is condition is weird, however in that we don't want to show this error to the user right away, and I assume they will also know if they delete the url, it is invalid. So I removed the error when the user deletes the link. The error _will_ still show when they try to submit.
This allows `""` to be considered valid as long as the user is not submitting the form, and the preview will disappear.

Preview should only be visible when user has entered a URL

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-attempts-editor.js
components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-retake-incorrect-only-editor.js
components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js

UI components added: 
- Attempts Allowed select
- Overall Grade Calculation select
- RIO checkbox
- RIO help info dialog
- Add Attempts Conditions button
Values for selects are hardcoded for now, Eventually these will be read from Attempts Entity
[US123706](https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F478977336380&fdp=true?fdp=true): [ui] Attempts: Conditions entities
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F478977336380&fdp=true?fdp=true

US123706 added selects, rio checkbox, button

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor-detail.js

Don't show the alert if the description is empty. Note that if the description contains whitespace characters that is NOT considered empty and the alert will show (if toggle is off). This is acceptable by Joseph since non-trivial to detect (since description is html and empty still contains html characters).

fix: don't show the alert if the description is empty

---

components/d2l-work-to-do/d2l-work-to-do.js

This turned out to be optional, so we're removing it - the background of the page clashes with the list items themselves when you mouse over them.
https://rally1.rallydev.com/#/357251704080ud/workviews?detail=%2Fuserstory%2F492516077212&view=b064b584-6337-43c1-b9a9-28047568284d

W2D: remove background gradient

---

components/d2l-work-to-do/d2l-work-to-do-activity-list-header.js
components/d2l-work-to-do/d2l-work-to-do-activity-list-item-detailed.js
components/d2l-work-to-do/d2l-work-to-do.js

context: some of our headers were divs with `d2l-heading-X` classes applied to them, instead of actual `h1`/`h2`/`h3` elements, which meant that they looked like headers but didn't behave like them when being read out by a screen reader. This fix should remedy that without any changes to how they look visually.
https://rally1.rallydev.com/#/357251704080ud/workviews?Name=01.%20Update%20Widget%2FFull%20Page%20Headers%20to%20be%20accessible&Priority=Normal&Project=%2Fproject%2F357251704080&Requirement=%2Fhierarchicalrequirement%2F463435916636&detail=%2Fdefect%2F492428081372&iteration=u&parentRef=%2Fhierarchicalrequirement%2F463435916636&rankTo=BOTTOM&view=b064b584-6337-43c1-b9a9-28047568284d

W2D: Change header divs to headers where appropriate

---

components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/lti-link/d2l-activity-content-lti-link-detail.js

This PR adds the due date component to the LTI link FACE page following the pattern of weblinks and modules

US124065 - adding due date component to lti link FACE page

---

components/d2l-activity-editor/d2l-activity-html-new-editor.js

"full" is the default type, so leaving out the type gives us the full editor.

use full editor instead of inline

---

components/d2l-quick-eval-widget/d2l-quick-eval-widget-controller.js
components/d2l-quick-eval-widget/d2l-quick-eval-widget-submission-icon.js
components/d2l-quick-eval-widget/d2l-quick-eval-widget.js
components/d2l-work-to-do/d2l-work-to-do-activity-list-item-basic.js
demo/d2l-quick-eval-widget/data/evaluation-status-quiz.json

Fixed a problem where items with no submissions were using the regular icon component instead of the submission icon component, causing misalignment in the list. 
Before:
After:

Set work-to-do-activity-list-item-basic to always use submission-icon in quick-eval widget

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-ip-restriction-editor.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F465115111280
I was testing the IP dialog and realized this condition wasn't correct. `entity.errors` defaults to an empty array which I thought was a falsy value. Turns out it's truthy and so in the case that there was an empty array of errors the dialog would never close. 
With this change the dialog should close if `entity.errors` is a falsy value or if it's an empty array.

Fixed dialog close logic

---

components/d2l-work-to-do/d2l-work-to-do-activity-list-header.js

https://rally1.rallydev.com/#/357251704080ud/workviews?detail=%2Fdefect%2F490418219912&view=b064b584-6337-43c1-b9a9-28047568284d
When the page is in skeleton view, we show an empty string for the activity count, but it styles the same round red circle around the empty string, which we should just be hiding entirely.

W2D: fix red count element appearing when showing skeleton

---

components/d2l-work-to-do/d2l-work-to-do-activity-list-item-basic.js
components/d2l-work-to-do/d2l-work-to-do-activity-list-item-detailed.js
components/d2l-work-to-do/d2l-work-to-do.js

Slack thread: https://d2l.slack.com/archives/G0150CJ3SB1/p1613151652045800
tl;dr if an activity has no start date, it should act as if it _has_ started - my prior code assumed the opposite, this should fix that.

W2D: Activities without start dates should still work

---

components/d2l-work-to-do/d2l-work-to-do-activity-list-item-basic.js
components/d2l-work-to-do/d2l-work-to-do-activity-list-item-detailed.js
components/d2l-work-to-do/d2l-work-to-do.js

Corresponding rally ticket: https://rally1.rallydev.com/#/357251704080ud/workviews?Name=Activities%20are%20no%20longer%20clickable%20&Priority=High&Project=%2Fproject%2F357251704080&Requirement=%2Fhierarchicalrequirement%2F459574112788&Severity=Major%20Problem&detail=%2Fdefect%2F499184063304&iteration=u&parentRef=%2Fhierarchicalrequirement%2F459574112788&rankTo=BOTTOM&view=b064b584-6337-43c1-b9a9-28047568284d&fdp=true?fdp=true

fix: [Cert fix 20.21.3]W2D: Activities without start dates should still work

---

components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js

Updated lang term as per Patrick for consistency across tools. The copy on the subtle button will now read:

feat: Updated lang term as per design

---

components/d2l-work-to-do/lang/en.js

Bug with serge confuses it if you have the same context comment, even if the key is different.

fix: Make w2d langterm context comments unique

---

components/d2l-work-to-do/env/index.js
components/d2l-work-to-do/lang/ar.js
components/d2l-work-to-do/lang/cy-gb.js
components/d2l-work-to-do/lang/cy.js
components/d2l-work-to-do/lang/da.js
components/d2l-work-to-do/lang/de.js
components/d2l-work-to-do/lang/en.js
components/d2l-work-to-do/lang/es-es.js
components/d2l-work-to-do/lang/es.js
components/d2l-work-to-do/lang/fr-ca.js
components/d2l-work-to-do/lang/fr.js
components/d2l-work-to-do/lang/ja.js
components/d2l-work-to-do/lang/ko.js
components/d2l-work-to-do/lang/nl.js
components/d2l-work-to-do/lang/pt.js
components/d2l-work-to-do/lang/sv.js
components/d2l-work-to-do/lang/tr.js
components/d2l-work-to-do/lang/zh-tw.js
components/d2l-work-to-do/lang/zh.js

Serge bug is _actually_ with the key names. View without whitespace changes to see the actual changes.
`myKey`, `MyKey`, `mykey` ✅ 
`Mykey` ❌

Fix unparsable w2d language keys

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-ip-restriction-editor.js
components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-ip-restrictions-container.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F465115111280
Fixes requested by Joseph:
1. Moved action buttons to slot="footer" so that they would behave consistently with the attempts dialog i.e. the action buttons stick in place even when new elements force scroll bar. This meant lifting the actions buttons up to `d2l-activity-quiz-ip-restrictions-editor` so that I could set the slot attribute correctly. 
2. (Edit: this change has been removed as Joseph didn't like the janky behaviour but if anyone has any thoughts on this I'm still interested so leaving here) Added an event listener for `d2l-dialog-open` to focus on the first instance of `d2l-input-text`. Prior to this change it focused on the "help" button on open as the core dialog component [forces …

Added quick fixes for focus and footer

---

components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
components/d2l-activity-editor/d2l-activity-content-editor/module/d2l-activity-content-module-detail.js

This PR replaces the previous html editor with the new html editor.
The new html editor relies on two attributes: `htmlEditorEnabled` and `htmlNewEditorEnabled`. If both are `true`, users can see the new html editor. If `htmlEditorEnabled` is true and `htmlNewEditorEnabled` is false, the users will see the previous editor. If both are false, the user will see a textbox.
The corresponding lms PR which adds the `htmlEditorEnabled` and `htmlNewEditorEnabled` attributes [can be found here](https://github.com/Brightspace/lms/pull/6849).
**Note**: These two attributes are set by config variables. To see the new editor, set `d2l.Preferences.TurnOffWYSIWYG=false`
and `d2l.Tools.WYSIWYG.NewEditor=true`. Setting the LD flag `F15913-html-editor-alignment` to `false` will also turn off the new …

US124894: Adding new html editor

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-ip-restriction-editor.js
components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-ip-restrictions-container.js

I did some refactoring earlier and realized that `this._validate` had now been moved to parent component so it is no longer being triggered on delete. To handle this I added logic to emit a "deleted" event and run the validate logic from the parent component.

Validate IPs on delete

---

components/d2l-quick-eval-widget/d2l-quick-eval-widget-submission-icon.js
components/d2l-quick-eval-widget/d2l-quick-eval-widget.js
components/d2l-work-to-do/d2l-work-to-do-activity-list-item-basic.js

Items in Quick-Eval widget will not render until fully loaded
Also changes the style of skeleton to be more detailed

Quick Eval Widget Skeleton Fix

---

components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz-timing.js

Only refetch entity if no entity is returned. If entity is returned, update the timing entity, but don't reload it to avoid janky UI updates.
See: https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/276

US123360 - Change to improve quiz timing entity optimistic loading jank

---

components/d2l-activity-editor/d2l-activity-content-editor/module/d2l-activity-content-module-detail.js

[DE42620](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fdefect%2F502153333324&fdp=true): Lessons FACE > Changes made in the new HTML editor are not always saved
The new html editor dispatches events on `blur` instead of on `change`. Typing into the new html editor then immediately clicking `Save` or `Save and close` created a race condition between setting the description (triggered by the `blur` event - this is also behind a 0.5 second debouncer) and the asynchronous api call which saves the description.
This PR makes sure the description is set first (if in the debouncer) before saving.

DE42620: Flush debouncer when saving

---

.eslintrc.json
components/d2l-work-to-do/mixins/d2l-work-to-do-localization-mixin.js
package.json

Uses the new `localize-dynamic-mixin` for true dynamic imports. Also enables OSLO.
~Dependent upon https://github.com/BrightspaceUI/core/pull/1146~

Move w2d to dynamic locale imports

---

components/d2l-work-to-do/d2l-work-to-do-activity-list-item-basic.js
components/d2l-work-to-do/d2l-work-to-do.js
components/d2l-work-to-do/env/index.js
components/d2l-work-to-do/lang/ar.js
components/d2l-work-to-do/lang/cy-gb.js
components/d2l-work-to-do/lang/cy.js
components/d2l-work-to-do/lang/da.js
components/d2l-work-to-do/lang/de.js
components/d2l-work-to-do/lang/en.js
components/d2l-work-to-do/lang/es-es.js
components/d2l-work-to-do/lang/es.js
components/d2l-work-to-do/lang/fr-ca.js
components/d2l-work-to-do/lang/fr.js
components/d2l-work-to-do/lang/ja.js
components/d2l-work-to-do/lang/ko.js
components/d2l-work-to-do/lang/nl.js
components/d2l-work-to-do/lang/pt.js
components/d2l-work-to-do/lang/sv.js
components/d2l-work-to-do/lang/tr.js
components/d2l-work-to-do/lang/zh-tw.js
components/d2l-work-to-do/lang/zh.js
components/d2l-work-to-do/mixins/d2l-work-to-do-localization-mixin.js

Backported work-to-do changes for 20.21.3

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-timing-container.js
components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.js
components/d2l-activity-editor/mixins/d2l-activity-editor-working-copy-dialog-mixin.js

Like the validation, the setting of `isError` is again inspired by the `activity-editor-container-mixin` https://github.com/BrightspaceHypermediaComponents/activities/blob/b7db0429ed7039258ed8d0e8270a229215c2ebdd/components/d2l-activity-editor/mixins/d2l-activity-editor-container-mixin.js
The timing/workingcopy component needs to include a `d2l-alert` that uses the `isError` and `errorTerm` properties to determine what to display. The `isError` and `errorTerm` are set in the mixin based on whether the input validation and the `checkin` succeed or fail. The error term is set to the `validationErrorTerm` if the input validation check fails or `serverErrorTerm` if the `checkin` fails. The `validationErrorTerm` and `serverErrorTerm` properties are set in the `firstUpdated` function of the …

US123692 - Add error handling to working copy dialog mixin

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-ip-restriction-editor.js
components/d2l-activity-editor/d2l-activity-quiz-editor/helpers/ip-validation-helper.js
components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js

Shifted IP restrictions validation client side to avoid losing track of IDs when sending network requests.

Shifted validation client side to prevent losing track of IDs

---

components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.js
components/d2l-activity-editor/mixins/d2l-activity-editor-working-copy-dialog-mixin.js

The checked out working copy of a base quiz needs to be re-fetched when it is checked-in as the working copy should theoretically no longer have a check-in action anymore (and to make sure everything is in sync).
https://trello.com/c/LbKqk61x/327-face-quiz-timing-saving-twice-causes-a-500-error

Ensure check-in entity is refetched

---

components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
components/d2l-activity-editor/d2l-activity-content-editor/module/d2l-activity-content-module-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/shared-components/d2l-activity-content-editor-styles.js
components/d2l-activity-editor/d2l-activity-editor.js
components/d2l-activity-editor/d2l-activity-html-new-editor.js
components/d2l-activity-editor/d2l-activity-text-editor.js
package.json

[DE42624](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fdefect%2F502198563680&fdp=true): Lessons FACE > new HTML editor default size too small
**Actual behaviour**:
When editing/creating a module, the default size of the HTML editor size is really small.
**Expected behaviour**:
When editing/creating a module, the HTML editor should take up all available vertical space/dynamically resize with the window.
**Note**: This requires `@brightspace-ui/htmleditor` version 1.2.6 or higher.

DE42624: Increasing editor size to take up all available vertical space

---

components/d2l-activity-editor/state/activity-score-grade.js

`bug`: mobX error being thrown when `Save & Close` or `Save` was being clicked on FACE Quiz.
Wrapped setters in `fetch` function with `runInAction` because observable properties can only be modified by mobX actions. 
[US125529](https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F505601651720&fdp=true?fdp=true): [ui] Display total points for a quiz
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F505601651720&fdp=true?fdp=true

fix: US125529 wrap activity-score-grade setters with runInAction

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-timing-container.js
components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz-attempts.js
components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz-ipRestrictions.js
components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz-timing.js
components/d2l-activity-editor/mixins/d2l-activity-editor-working-copy-dialog-mixin.js

Problem: When a `PATCH` is made to the timing entity, the existing quiz working copy in the store is not updated, so we do not know if it has a `check-in` action or not.
Solution: Refetch the working copy prior to check in.
The code fix is a bit more complicated because we need to wait for the `PATCH` to the timing endpoint to complete before refetching the quiz working copy, and the timing entity and the quiz working copy are in different stores.
These are the steps of how things will be processed...
1. Say focus is currently on input, and we click OK to check in the dialog
2. The input focus out event causes a `PATCH` request to be sent. This promise is set to the `saving` property in the `quiz-timing` MobX object.
3. The OK click on the dialog causes a call to the `_checkin` function, …

Refetch wc before checkin

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-retake-incorrect-only-editor.js

Help button doesn't open dialog because dialog mixin was removed 👀

fix: RIO help dialog

---

components/d2l-activity-editor/d2l-activity-html-new-editor.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F508303488440
Fix for above story. This attribute should have been set as a conditional attribute to ensure it only gets added when permissions evaluate to truthy.

Conditionally add paste-local-images attribute

---

components/d2l-quick-eval-widget/lang/es-es.js

`es-es.js` was deleted in https://github.com/BrightspaceHypermediaComponents/activities/pull/1612 because it was untranslated (because of a bad serge rewrite config). That PR made it fall back to `es` (effectively `es-mx`) instead of delivering english strings, but because quick-eval-widget does not use dynamic imports, the BSI build tried to bundle `es-es` and failed.
Serge will replace this with proper `es-es` strings when the pending round of translations come back.

Temporarily copy quick-eval-widget es.js to es-es.js

---

components/d2l-activity-editor/d2l-activity-html-new-editor.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F508303488440
I need to add this event before moving files etc as otherwise if there are no files present on the HTML editor property then this line will evaluate to false and the changes won't be persisted.
```js
if (!editor || !editor.files || !editor.files.length || !editor.isDirty) return;
```

Fire update event on save to ensure correct state

---

components/d2l-activity-editor/d2l-activity-content-editor/module/d2l-activity-content-module-detail.js
components/d2l-activity-editor/d2l-activity-html-new-editor.js
components/d2l-activity-editor/d2l-activity-text-editor.js

Previously, we were passing data down as attributes but treating them like properties. This had no visible real negative impact, but cluttered things up with several attributes showing up as `undefined`. Also, there was an instance of a boolean attribute that was not prepended with the `?` so it was not treated like a true boolean attribute.
This pr makes the attributes look more like attributes (lowercase kebab case) and uses `ifDefined` to prevent attributes from being rendered if they don't exist.

DE42834 Content > Fix attributes and properties on new html editor

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-timing-summary.js
components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js

The Timing summarizers should use sentence case, ie. `Recommended time limit` instead of `Recommended Time Limit`. Made 2 new lang terms which are conditionally selected by the `d2l-activity-quiz-timing-summary` for this fix.
[US125926](https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F509674996592&fdp=true?fdp=true): [ui] Sentence case summary text for Timing
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F509674996592&fdp=true?fdp=true

US125926 added new lang terms and changed labels to sentence case

---

components/d2l-quick-eval-widget/d2l-quick-eval-widget-controller.js
components/d2l-quick-eval-widget/d2l-quick-eval-widget.js
demo/d2l-quick-eval-widget/d2l-quick-eval-widget.html
demo/d2l-quick-eval-widget/data/activity-collection.json
test/d2l-quick-eval-widget/data/activity-collection-many-items.json
test/d2l-quick-eval-widget/perceptual/d2l-quick-eval-widget.visual-diff.html

Currently if a single unexpected activity type is returned for the QE widget it will display an error message rather than loading the list.
This change has the widget display activities of valid types even if it receives unexpected ones and output an error message containing the unexpected type to the console for easier identification of further issues.

Quick Eval Widget handle unexpected activity types

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-attempts-container.js

[US123706](https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F478977336380&fdp=true&fdp=true?fdp=true): [ui] Manage Attempts (Attempts allowed, RIO, Attempt conditions)

US123706 Fix: restore attempts dialog height

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-categories-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-submission-and-completion.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/en.js
components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment-categories.js
components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment-store.js
components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.js
test/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.spec.js

https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F519563556284
Added basic component for rendering a categories dropdown in assignments.
Edit: I think this will always fail CI until this is merged https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/310

US126777 Add existing categories

---

components/d2l-activity-editor/d2l-activity-score-editor.js

I think overriding the save function caused the changes to not save properly. Also fixed something in the update function to make sure it doesn't return too soon.

fix: don't override save in score editor

---

components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
components/d2l-activity-editor/d2l-activity-content-editor/state/content.js
components/d2l-activity-editor/d2l-activity-content-editor/web-link/d2l-activity-content-web-link-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/web-link/state/content-web-link.js
test/d2l-activity-editor/d2l-activity-content-editor/state/content-web-link.spec.js
test/d2l-activity-editor/d2l-activity-content-editor/state/content.spec.js

[US126672](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F519007142480&fdp=true?fdp=true): Modify activities saveHref to handle new working copy items
NOTE: Requires https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/313 and https://github.com/Brightspace/lms/pull/9275
Adds logic to notify and update the parent content activity usage when a web link is persisted and the activity usage href may have changed.
Additionally, adds logic to use the new `lesson-view-page` href when navigating back to the lessons page.
The `lesson-view-page` link will allow the FACE UI to navigate back to the correct topic after saving (especially useful for creating a new topic). Currently when creating a new weblink and choosing "Save And Close" the user …

Handle redirecting to the lesson view page from the updated activity usage

---

components/d2l-activity-editor/d2l-activity-grades/state/grade-candidate-collection.js
components/d2l-activity-editor/state/activity-score-grade.js

The bug comes down to the `gradeCandidateCollection` being set when the dialog is opened. And when we save, we do not re-fetch the collection. So when we open the dialog again after save, it shows old data.
We had the right idea to set the `gradeCollectionCollection` mobX property to `null`. But when the dialog is re-opened, it does not bypass the cache to re-fetch the entity, instead it retrieves our stale candidate collection from the store.
This also fixes a problem where when we "Create new grade" and "save", the `gradeCandidateCollection` isn't re-fetched, so the grade we just created and linked to does not appear in the "link to existing dropdown" even though the assignment is linked to it.
https://trello.com/c/IPhZb0hO/5-choose-grades-incorrect-selected-existing-grade-item-showing-a …

Fix incorrect existing grade displayed after saving

---

.github/workflows/visual-diff.yml

Added an option to turn off the draft PR feature for visual-diff, since it makes more sense in this repo for code owners to be notified immediately.

ci: Turn off draft PRs for visual-diff

---

components/d2l-activity-editor/mixins/d2l-activity-editor-telemetry-mixin.js

Removing the endpoint for PBMM clients causes the client creation to fail and throw (see [here](https://github.com/Brightspace/brightspace-integration/blob/master/web-components/bsi-unbundled.js#L43)), so this catches that error so those clients don't get a bunch of console errors.
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F600523947568

US127307 Catch telemetry error when missing endpoint

---

components/d2l-quick-eval/d2l-quick-eval-submissions-table.js

As part of the Lit migration for `d2l-table`, I'm also simplifying things and removing variables that aren't needed. These two default to "white", and Quick Eval is on a page with a white background anyway, so setting them to transparent isn't necessary.
I've tested this and did not notice any visual change.

fix: removing unnecessary table variables

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js

Debouncing the name input changes means that the state update could happen _after_ hitting "Cancel" - if the user is fast enough. Fix is to flush the debouncer after the first change.
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fdefect%2F602484583664

DE43392 Assignment name cancel dirty-check race condition

---

test/d2l-quick-eval/perceptual/d2l-quick-eval-activity-card.visual-diff.js

Fairly certain this is what caused [this run](https://visual-diff.d2l.dev/screenshots/BrightspaceHypermediaComponents/activities/activity-card/2021-05-05-16.20.28.364-90b39eadd3325003ae766c8fadedcd3cf6b28f8d-report.html) to flake.

Always await page.hover

---

components/d2l-activity-card/ActivityCardLocalize.js
components/d2l-activity-collection-editor/localization.js
components/d2l-activity-evaluation-icon/ActivityEvaluationIconBaseLocalize.js
components/d2l-activity-list-item/ActivityListItemLocalize.js
components/d2l-quick-eval-widget/lang/localize-quick-eval-widget.js
components/d2l-quick-eval/QuickEvalLocalize.js

In https://github.com/BrightspaceHypermediaComponents/activities/pull/1612 I added `fr-on` files for all components in this repo, but I left enabling it up to the teams responsible for each component. I don't think I was very clear about that, so for any components not using the dynamic localization mixin I've manually enabled `fr-on` here. Though I have done a cursory check to make sure the files exist and the correct patterns were followed, 🚨  _I have not tested these_.
Please test these components if your team is responsible for them, or tag someone you know is.
I have no reason to believe any of the affected components required `fr-on` in the May release, or even had any differences from `fr-ca` yet, so I don't see why a hotfix would be necessary, but if you believe it is please let …

Enable fr-on

---

components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-controller.js
components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-editor.js
components/d2l-activity-editor/lang/en.js

Rally: [US125198](https://rally1.rallydev.com/#/57732444928d/dashboard?detail=%2Fuserstory%2F5022
We want to warn users of FACE using a confirmation dialog if they are about to detach a rubric which has evaluated assessments for the activity, since these assessments will be deleted along with the association.

Add dialog to confirm detaching rubrics in FACE

---

components/d2l-activity-editor/d2l-activity-content-editor/module/d2l-activity-content-module-detail.js
components/d2l-activity-editor/d2l-activity-text-editor.js

~~Because of the recent addition of the `live()` [directive on the new-html-editor component in this repo](https://lit-html.polymer-project.org/guide/release-notes/1.2.0.html#live-directive), the initial text was not getting updated from it's initial state of `undefined` to `""`. I'll be honest, I don't understand why not as `live` claims it does a strict equality check to update and so it should be updating. I suspect something is not setup quite right for how some other editors want to update (or not update) their content. This is also only happening for new content which makes this lifecycle all the more confusing.~~
~~This is a bit of a band-aid fix, as we should still be respecting `moduleEntity.descriptionRichText` (which is empty string) but for whatever reason the initial render …

Content module editor: Description field text defaults to "undefined" for new modules

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js

https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fdefect%2F603493211252
I believe [this](https://github.com/BrightspaceHypermediaComponents/activities/pull/802/files) is the original PR which added this feature. Getting removed as it's causing too many headaches.

Removed attachment links feature

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/state/content-file.js

- [DE43452](https://rally1.rallydev.com/#/289692574792d/dashboard?detail=%2Fdefect%2F603408374512&fdp=true?fdp=true): FACE HTML/Files > Clicking Back/Cancel on unmodified files causes "Discard changes?" warning to popup
The Siren SDK `equals` implementation checks title and file href currently, but here we only include the title when making the object for comparison. The file href should never change for now, but eventually we will implement replace file functionality in which it will change. This is not HTML file specific.
The solution was to add the file href to the object being built for comparison. I chose this solution over the alternative of removing it from the equals check in the Siren SDK because eventually we will add the ability to replace the file (for all non-HTML file types) …

DE43452 Content files incorrectly marked as dirty

---

components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment-categories.js

https://trello.com/c/Mbb5PkHC/377-assignment-aligned-to-new-category-even-on-cancel
For this to work correctly we need to reset the initial category on save otherwise it will reset weirdly if a user saves in place followed by a cancel.

Added a reset to initial category on save

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-categories-editor.js
components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment-categories.js

https://trello.com/c/Mbb5PkHC/377-assignment-aligned-to-new-category-even-on-cancel
Follow up from last PR to cover the case where we need to reset the category on an assignment which loads with "No Category".

Handled reset case for assignments without categories

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-file-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
components/d2l-activity-editor/d2l-activity-content-editor/web-link/d2l-activity-content-web-link-detail.js
components/d2l-activity-editor/d2l-activity-editor.js
components/d2l-activity-editor/state/activity-usage.js

- [DE43265](https://rally1.rallydev.com/#/289692574792d/dashboard?detail=%2Fdefect%2F600684803540&fdp=true?fdp=true): Lessons FACE Weblinks >  Saving a new weblink sometimes causes a 500 error
- [DE43284](https://rally1.rallydev.com/#/289692574792d/dashboard?detail=%2Fdefect%2F600899688384&fdp=true?fdp=true): Lessons FACE Weblinks > Visibility status and dates are not saved when creating a new weblink with working copy enabled
We want to adjust the save flow for content FACE pages so that on saving a new activity we re-fetch the activity usage if we're not navigating away from the FACE page. 
The solution was to stop the editor from stopping the save complete event propagation and updating the `d2l-activity-content-editor` to handle the in place save complete event and set `this.href` to …

Updating the href on save complete, and awaiting the save of the activity usage

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-file-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/content-file/state/content-file.js
components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/module/d2l-activity-content-module-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/shared-components/d2l-activity-html-editor-styles.js
components/d2l-activity-editor/lang/en.js

Co-authored-by: @brissons
- https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F393033401500
The FACE HTML File Create/Edit pages are required to have an HTML Editor for the user to edit content.
This PR adds and hooks up the HTML Editor (Whether old editor vs. new/TinyMCE one is rendered is determined based on WYISWYG.NewEditor Config Variable). The hookup part of the code ensures loading of HTML content, Saving as well as Save and Close function properly.
- https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/320

FACE HTML file - Add HTML field via new HTML editor

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/state/content-file.js

- [US128071](https://rally1.rallydev.com/#/289692574792d/dashboard?detail=%2Fuserstory%2F604152072952&fdp=true?fdp=true): (FE) FACE HTML file - Don't load file usage link if not present, change where to check for type
To handle the fact that we don't want to have a file entity usage link when the file activity is new, we have removed the link from the entity response when it's a new entity. The goal is to update FACE to check if there is a file entity usage link before trying to load it, rather than checking the URL to determine if it's a new activity.
The solution here is just to get the `fileEntityHref` and check if it has a value before proceeding to load its content.
N/A
- https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/323 the SDK PR needs to be merged first
- In …

US128071 - don't load file entity if there's no link

---

components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js

​
When saving and closing a new weblink the actvities repo navigates you to a 404 page in lessons
​
So we originally tried to solve this one way by including the updated `lessonViewPageHref` on the activity-usage which gets fetched after committing the weblink, therefore having a 'proper' lessons URL with the newly saved topic id. Unfortunately do to async timing things that isn't super reliable. However in the meantime we also added in a bunch of logic in the LMS to track the persisted topic id against the original 'fake' activity usage, and so we were able to solve this LMS side via [this commit](https://github.com/Brightspace/lms/pull/10084/commits/cf2414010c141add93003294023145bd8e24d4ee#diff-997906e087c0689fbc237e3c896114462d24bea5e982ea408d75da08c68a78a9R227).
​
Anywho, that makes …

Remove unnecessary savehref logic from content editor

---

components/d2l-activity-editor/d2l-activity-content-editor/web-link/state/content-web-link.js

​
PR of Shame.
​
​
Release the thing that was [committed here](https://github.com/BrightspaceHypermediaComponents/activities/commit/5a23215e93b9d1742007350af58bf33eb3ea98a0).
​
n/a
​
n/a
​​
​
[DE43566](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fdefect%2F604759636596&fdp=true?fdp=true): Lessons FACE working copy > saving a new weblink/HTML topic results in a 404

fix: spacing changes just to trigger release for previous fix to saveHref

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-file-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/module/d2l-activity-content-module-detail.js
components/d2l-activity-editor/d2l-activity-html-new-editor.js
components/d2l-activity-editor/d2l-activity-text-editor.js

This pr will tell the content html editors to use a certain font family. They were not being applied as we set our editor to "fullPage" so we can take advantage of customization.
One unfortunate thing is that manually setting the font family like this does not make it select it from the drop down list, so even though I am typing in Lato by default, I still see a different Lato in the dropdown menu.
Note: I had the font flipped when I made these screenshots, Modules should be Lato, Files should be Verdana.
MODULE EDITOR:
HTML EDITOR:

Default to font families in Content editors

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/state/content-file.js

[DE43500](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fdefect%2F603973776280&fdp=true): FACE HTML > Head scripts are duplicated when saving html files
When editing an html file, the endpoint we were using was attaching head scripts to the file, which would show up in the html editor. If a user edited and saved, these scripts would also be saved in the file, resulting in duplicate scripts.
Calling the raw data endpoint will make it so that only the raw html file data will show up in the editor.
Before:
After:
- https://github.com/Brightspace/lms/pull/10645
- https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/324

DE43500: Use file data endpoint when editing html files

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/state/content-file.js

Cert fix of [this PR](https://github.com/BrightspaceHypermediaComponents/activities/pull/1733).

[cert] DE43500: use file data endpoint when editing html files

---

components/d2l-activity-editor/d2l-activity-html-new-editor.js

- [DE43589](https://rally1.rallydev.com/#/289692574792d/dashboard?detail=%2Fdefect%2F605074749528&fdp=true?fdp=true): [cert] FACE HTML > HTML file content saved as "undefined"
HTML file content is occasionally saved as "undefined". This is happening because the new HTML editor fires the `d2l-activity-html-editor-change` event only on save and the new editor's save order is 500, which is the same order as our content editors that use working copy. Due to this, these two saves happen in the same `Promise.all`, and so there's a chance that the content hasn't been retrieved from the HTML editor when we are saving the content file activity. This doesn't affect content modules because the save order for that editor is the default (1000).
This change implements 2 solutions:
1. Change the new …

DE43589 - fixing new editor content race condition

---

components/d2l-activity-editor/d2l-activity-content-editor/shared-components/d2l-activity-content-editor-styles.js

An oversight in #1716 resulted in [this rule](https://github.com/BrightspaceHypermediaComponents/activities/pull/1716/files#diff-61ede7520d7d792457b26925a2f88e6315341fc1ca5794d271e20b6a127c8ceaL35) being removed, causing the editor to get squished. It's back now.
I can't believe it took me a week to find this

DE43565 re-add content-description-container rule

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-file-detail.js

- [DE43589](https://rally1.rallydev.com/#/289692574792d/dashboard?detail=%2Fdefect%2F605074749528%2Fconnections&fdp=true?fdp=true): [cert] FACE HTML > HTML file content saved as "undefined"
In our debouncer map, we were storing the content debouncer at "description" and then flushing the debouncer at "pageContent". Since these don't match, the debouncer wasn't actually being flushed on save.
Renaming the debouncer to be consistently "htmlContent".
N/A
- https://github.com/BrightspaceHypermediaComponents/activities/pull/1738 lessened a lot of the reasons for a race condition, but because of the debouncer not being flushed, we were still "racing" against the debouncer when saving.
N/A

DE43589 - flush the correct debouncer on content file save

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-add-activity-menu.js

https://trello.com/c/kjd4oLi9/383-create-new-button-dropdown-shows-arrow-off-to-the-left-too-much

fix: hide dropdown pointer to work with start-alignment

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/state/content-file.js

- [DE43731](https://rally1.rallydev.com/#/289692574792d/dashboard?detail=%2Fdefect%2F600345601867&fdp=true?fdp=true): [cert] FACE HTML > HTML file content saved as "undefined" when using the rich text editor
The rich text editor fires its content changed event on input change rather than on save like the wrapper for the new HTML editor. Since in the `content-file` state object we were using `htmlContent` to store HTML content but initializing `fileContent`, with the rich text editor `htmlContent` was never set and so was undefined. This led to undefined being sent as the new content on save, rather than an empty string (or in the new HTML editor's case, an empty HTML doc).
The solution here is to replace all references to `htmlContent` with `fileContent`. There are checks that make sure …

DE43731 - rich text editor saves undefined if no content saved

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-file-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/content-file/state/content-file.js
components/d2l-activity-editor/d2l-activity-content-editor/module/d2l-activity-content-module-detail.js

[DE43733:](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fdefect%2F600359414369&fdp=true) FACE HTML > clicking 'back' with changes in editor does not trigger discard changes popup
Clicking back or cancel with changes in editor was not triggering the 'Discard changes? Are you sure you want to discard your changes?'. This was happening for two reasons:
1. The current `dirty()` method was only comparing the `ContentFileEntity` values, which is the title and the description of the file activity, not the actual file content in the html editor.
2. The html editor triggers the save event on `blur` rather than on `change`, which is being debounced. If the user is working on the html editor then immediately presses 'Cancel' or 'Back', the changes in the editor won't be …

DE43733: Clicking back or cancel with changes in editor does not trigger discard changes popup

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-ip-restrictions-editor.js
components/d2l-quick-eval/d2l-quick-eval-submissions-table.js

The new Lit version of tables is ready! That, combined with no longer supporting IE11 means we can just use normal table/tr/td elements instead of the crazy d2l-table/d2l-tr/d2l-td ones. 🙌 
These two solutions look slightly different because the way styles get shared is different in Lit (where it uses CSS literals that you apply to your Lit element) vs. Polymer (where it uses shared <dom-module>s). So Quizzing can just reference the new Lit table directly whereas Quick Eval because it's still a Polymer element needs to reference `d2l-table`'s wrapper that has the style module.

fix: switching quiz IP table and Quick Eval to use Lit tables

---

.gitignore
components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-editor.js

Rally: [US125198](https://rally1.rallydev.com/#/57732444928d/dashboard?detail=%2Fuserstory%2F502279656304)
On the FACE page rubric detachment dialog, NVDA consistently reads out "clickable Cancel button" instead of the dialog text.
This behavior is a symptom of a greater issue with the dialog component, which was addressed(?) in [BrightspaceUI/core#1330](https://github.com/BrightspaceUI/core/pull/1330), so this PR just bumps the UI core version to reflect the changes to the focus behavior.

fix: NVDA reads rubric detachment confirmation buttons instead of dialog text

---

components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/shared-components/d2l-activity-content-editor-due-date.js

[US128149](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F604435412380&fdp=true?fdp=true): FACE pages - due dates component - default to expanded state (but not on modules)
Add skeletons for due dates under expanded or not scenarios: https://github.com/BrightspaceHypermediaComponents/activities/pull/1771
​
We don't want to hide the due date field by default when creating or editing non-module content items. But for modules we still want to default to the subtle button which needs to be clicked to display the date/time fields.
​
​
I've replaced the internal `_showAddDueDateBtn` with a public `expanded` attribute. It defaults to false but then in the `_renderDueDate` function I'm passing in an override for the types that we want to default to expanded. …

Only show due date subtle button for modules, expand to show field for other content types

---

components/d2l-activity-editor/d2l-activity-content-editor/shared-components/d2l-activity-content-editor-due-date.js

[US128149](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F604435412380&fdp=true?fdp=true): FACE pages - due dates component - default to expanded state (but not on modules)
Only show due date subtle button for modules, expand to show field for other content types: https://github.com/BrightspaceHypermediaComponents/activities/pull/1770
​
Skeletons were not appearing on the due date control when it displayed the subtle button. This PR aims to fix that.
​
​
`d2l-subtle-button` does not natively support skeletons. To provide them I've added the `SkeletonMixin` to the `ContentEditorDueDate` web component and applied the `d2l-skeletize` class to the button.
This did not completely solve the problem, however, as there is a period of time between loading …

add skeletons for due dates under expanded or not scenarios

---

components/d2l-activity-editor/d2l-activity-grades-dialog.js
components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grade-category-selector.js
components/d2l-activity-editor/d2l-activity-score-editor.js

This PR switches the grades dialog from `ActivityEditorMixin` to `ActivityEditorWorkingCopyDialogMixin` which has a bunch of helpers to help open/close the dialog and checkout/checkin.
The PR also simplifies the showing of the "+ Grade Category" button a little.
This PR also tries to separate some of the working copy logic and non-working copy through if/else.
There are 2 issues with this PR.
1: the `async` state on the dialog should be `true` to show the loading spinner.
2: when the selectbox LD flag is off, it is still checking out because the entity contains a checkout action, although it doesn't patch or checkin or do anything with the checked out entity. But I should prevent that somehow probably.
https://rally1.rallydev.com/#/29180338367ud/dashboard?detail=%2Fuserstory%2F505562087036 …

US125507 - Check in dialog

---

components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grades-dialog.js
components/d2l-activity-editor/mixins/d2l-activity-editor-working-copy-dialog-mixin.js

Non working copy (i.e. `createSelectboxGradeItemEnabled` is `false`) will not be using the loading spinner in the dialog. It will open when it is ready just like the existing behavior.
Working copy (i.e. `createSelectboxGradeItemEnabled` is `true`) will be using the loading spinner in the dialog. The loading spinner still acts a bit funny and might disappear too soon before everything is loaded. I'll like to see how it performs on quad.

US125507 - Fix dialog height and async

---

components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grades-dialog.js
components/d2l-activity-editor/d2l-activity-score-editor.js
components/d2l-activity-editor/mixins/d2l-activity-editor-working-copy-dialog-mixin.js

It's magic.
We are only passing in the base activity usage as the `href` to the `grades-dialog`, and no other `href`s. The working copy will be checked out in the `score-editor` which is the parent of the `grades-dialog`. This 1st working copy `href` is stored as a property in the MobX object of the base activity usage.
With the selectbox flag on, aka using working copy, the `grades-dialog` component will mostly be making references to the `dialogHref`. The `dialogHref` which is a string set in the `workingCopyDialogMixin` via a checkout action off the first working copy. It knows the `href` of the first working copy because it can retrieve it from a …

US125507 - clean up all the hrefs!

---

components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grades-dialog.js
components/d2l-activity-editor/mixins/d2l-activity-editor-dialog-mixin.js
components/d2l-activity-editor/mixins/d2l-activity-editor-working-copy-dialog-mixin.js

This is due to it initially only calling `_cancel` on cancel button click. But that function also needs to be called if the dialog is closed via the 'x' or 'esc'. The only way to catch this is to listen to the `d2l-dialog-close` event. The change to not pass the event to our dialog mixin is because the mixin is doing `event.stopPropagation` which was preventing the `done` action in `ok` dialog button presses from being present in the `d2l-dialog-close` event.

US125507 - Fix cannot re-open dialog after an 'x' click to close dialog

---

components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-container.js
components/d2l-activity-editor/lang/ar.js
components/d2l-activity-editor/lang/cy.js
components/d2l-activity-editor/lang/da.js
components/d2l-activity-editor/lang/de.js
components/d2l-activity-editor/lang/en.js
components/d2l-activity-editor/lang/es-es.js
components/d2l-activity-editor/lang/es.js
components/d2l-activity-editor/lang/fr-fr.js
components/d2l-activity-editor/lang/fr-on.js
components/d2l-activity-editor/lang/fr.js
components/d2l-activity-editor/lang/ja.js
components/d2l-activity-editor/lang/ko.js
components/d2l-activity-editor/lang/nl.js
components/d2l-activity-editor/lang/pt.js
components/d2l-activity-editor/lang/sv.js
components/d2l-activity-editor/lang/tr.js
components/d2l-activity-editor/lang/zh-cn.js
components/d2l-activity-editor/lang/zh-tw.js
package.json

The d2l-simple-overlay component is being replaced with the d2l-dialog-fullscreen component. The functionality of the page should not be affected. 
Here's a gif of the new look: 
I noticed that the "Edit rubric" title is part of the body, rather than being in the header. We can move that to the header, but I decided to keep it as it was for this PR(the overlay header was also empty).

US118647 - Replaced simple-overlay with d2l-dialog-fullscreen component in rubrics list

---

components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-editor.js
components/d2l-activity-editor/d2l-activity-rubrics/state/association-collection.js

Save-in-place was throwing off the existing rubric state management, so this just re-fetches the associations on save-in-place so the UI reflects the correct state (equivalent to loading the assignment from scratch).
There was also a small bug where the rubric 'X' removal button was relying on the event to provide the rubric id, but if the focus was elsewhere when clicking the target event was an unexpected element and the button wouldn't respond. Since the association is available at the time of the click, this switches it to just use the known association href directly.
https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fdefect%2F600844552471&fdp=true

DE43805 Fix rubrics behavior on save-in-place

---

components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grades-dialog.js
components/d2l-activity-editor/state/associate-grade.js

Trying really hard to separate the code so that with the selectbox LD flag on, it uses the `associateGrade` store, otherwise it uses the `scoreAndGrade` store.

US125507 - With the selectbox flag on, use the associateGrade store

---

components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grades-dialog.js

On dialog cancel, it was not going back to the previous selected grade category or grade candidate
I broke it here: https://github.com/BrightspaceHypermediaComponents/activities/commit/5c51bea4cf7e9ac250908c94e654a36f9ab3ac6e#diff-3d1b7f638f1665079274762423219b3db399cf9d01e94426273861595da0d112L194-L211

US125507 - fix old functionality on dialog cancel

---

components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/lti-link/d2l-activity-content-lti-link-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/lti-link/d2l-activity-content-lti-link-external-activity.js
components/d2l-activity-editor/d2l-activity-content-editor/lti-link/d2l-activity-content-lti-link-options.js
components/d2l-activity-editor/d2l-activity-content-editor/lti-link/d2l-activity-content-lti-link-preview.js

- [US128152](https://rally1.rallydev.com/#/289692574792d/dashboard?detail=%2Fuserstory%2F604435426512&fdp=true?fdp=true): LTI page - Display link inside embedded display
We want to display the LTI link embedded in an iframe on the FACE page so that instructors can edit the activity from within the FACE page.
I've added another component that has only the iframe in it. The reason I've done this is because its skeleton is going to behave differently from the rest of the FACE page's skeleton in that it doesn't go away on entity load but rather on iframe load.
Below is a gif of editing an LTI link that can be embedded in an iframe without error, including showing the delayed skeleton and resizing capabilities:
Below is a gif of editing an LTI link that cannot be embedded in an iframe and …

US128152 embed link in iframe

---

components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-editor.js

Rally: [DE43913](https://rally1.rallydev.com/#/57732444928d/custom/373260458992?detail=%2Fdefect%2F601487122367)
Tiny fix to ensure that rubrics being previewed in the assignment editor are read-only as per the design spec

DE43913: FACE rubric preview tabulation

---

components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-container.js

The ending tag should be closing the d2l-dialog tag, not d2l-dialog-fullscreen. This was auto-fixed by the HTML, so it wasn't actually causing any errors or rendering problems.

Fix ending dialog tag typo

---

components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
components/d2l-quick-eval/dismiss/d2l-quick-eval-dismissed-activities-list.js

This PR adds labels to selectable d2l-list-items that will be required in the near future in order to support changes that are being made to lists for selection, multi-selection, and multi-actions.

Add required labels to selectable d2l-list-items.

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-file-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-file-loading.js

This pr creates a new component which just consists of a label and a full height div that will perpetually be in a loading state. On our file page, we use info from the entity to determine which elements to render as this page will eventually have multiple options based on the file type. As a result, before we got the entity the view would be blank so no loading skeletons would show. Now, before we receive and examine our entity we will default to this loading view.
Note: the loading state on the due date is not in sync with the other elements as we slot that in for some reason I can't remember. It's unrelated to this change, it happened before as well.

Fix loading skeleton on the HTML file type page

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-attempt-conditions-editor.js

[US129209](https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F601848854689&fdp=true?fdp=true): [ui] Update attempts condition field to d2l-input-percent

US129209 Quizzes: Switch to `d2l-input-percent`

---

components/d2l-activity-editor/d2l-activity-content-editor/lti-link/d2l-activity-content-lti-link-options.js
components/d2l-activity-editor/d2l-activity-content-editor/web-link/d2l-activity-content-editor-link.js
components/d2l-activity-editor/lang/en.js

- https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fdefect%2F470674608400
The FACE page for Creating Web Links should have the link option default to the 'open in new tab' option. This has already been done here: https://github.com/Brightspace/lms/pull/11192/files. The user should be let known the reason for recommendation/defaulting to this.
This PR adds a locale/statement to the help icon tooltip for the open in new tab option explaining why opening in a new tab is the better option.
- https://github.com/Brightspace/smart-curriculum/pull/1266

DE41878: Add tooltip locale explaining/recommending 'open in new tab' option

---

components/d2l-activity-editor/d2l-activity-grades/d2l-activity-edit-new-grade.js

Fixes https://trello.com/c/Fh9ceWDx/392-grade-category-and-type-selector-buttons-too-wide-for-mobile
Also, moves button position over so that button text is aligned instead of button border (Patrick's request)

fix: mobile view of buttons, and button position

---

components/d2l-activity-editor/d2l-activity-score-editor.js
components/d2l-activity-editor/lang/en.js

This fixes the issue where the units label of the grade becomes the grade type (i.e. "numeric" or "selectbox" instead of "points"). I'm sure there was a trello or defect logged somewhere but I could not locate it.

fix: label grade units correctly

---

components/d2l-activity-editor/d2l-activity-editor.js
components/d2l-activity-editor/state/activity-usage.js
components/d2l-activity-editor/state/working-copy.js

Fixes https://trello.com/c/JVZtua6s/393-creating-new-grade-creates-duplicate-numeric-grade-item
Goes with https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/352

fix: duplicate grade created

---

components/d2l-activity-editor/state/associate-grade.js

This was actually breaking your simplification in loading grade schemes because `existingGradeType` ended up being the same as the newly loaded grade type. Taking this out here doesn't hurt performance because the radio buttons in the UI just show what the user clicked anyway.

fix: grade scheme simplification

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-add-activity-menu.js
components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor-action-bar.js
components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor-detail.js
components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-question-editor.js

Receive activity usage hrefs of created questions and call the add-existing workflow in the hmc quiz editor with that information, then update the total points display. 
Related hmc PR: https://github.com/BrightspaceHypermediaComponents/foundation-components/pull/250
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F601851661777

US129210 Add existing questions

---

components/d2l-activity-editor/d2l-activity-content-editor/module/d2l-activity-content-module-detail.js

This pr removes the "full page" attributes when using the new html editor. This means that the font size and family that are selected by default will use the system settings when editing modules. The full page attributes are still present when editing html topics.
Removing these was necessary for modules as it would add extra template stuff which is not meant for modules. This was causing all those extra new lines to appear as they were added when the html content was filtered.
Rally: https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fdefect%2F601628066803

Remove fullpage attributes for content modules

---

components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-container.js

This is required for https://github.com/Brightspace/d2l-rubric/pull/819 to merge. Changing the dialogs to the best-practice web components allows them to fire the d2l-dialog-close events. The fullscreen dialog (that wraps the create rubric page) gets the bubbled event and turns the page blank. Checking that the event is intended for the fullscreen dialog will ensure it doesn't interpret any popup dialogs as a sign for it to close.

Prevent bubbling close event from popup dialogs to affect the fullscreen dialog

---

components/d2l-activity-editor/d2l-activity-content-editor/web-link/helpers/url-validation-helper.js
test/d2l-activity-editor/d2l-activity-content-editor/web-link/helpers/url-validation-helper.spec.js

Rally: https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fdefect%2F602348528019
This PR changes the URL validation to require the input to have either http:// or https:// at the beginning of the URL.
Before:
There would be no indication of an error, and when trying to save nothing would occur. Network tab would show a failure.
After:
The user is notified that the URL is invalid before trying to submit.

DE44122: FACE Weblinks > No error message shown when saving link that is missing http/https

---

components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grades-dialog.js
components/d2l-activity-editor/lang/en.js

Task https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Ftask%2F602375778941&fdp=true?fdp=true
for story https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F600744235069&fdp=true?fdp=true
When grades dialog 'OK' is pressed, announce one of the following:
- "Creating new {numeric|selectbox} grade item {name}"
- "Linking to existing grade item {name}"

US128779 - Announce what is saved when grades dialog OK is pressed

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-file-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/content-file/state/content-file.js
components/d2l-activity-editor/lang/en.js

https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F424774442084
As part of the new Feature work for HTML FACE pages, we would like to support HTML File Template selection. The first piece to this is to fetch the relevant Siren Entities for this, and and display the list of templates in a dropdown menu. (See Rally link for link to designs).
This PR adds a 'Select Template' subtle dropdown button, that displays 'Loading...' when clicked and then the list of templates once the template entities have been fetched.
- https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/355

FACE HTML file - Support Template Selection - Dropdown Menu

---

components/d2l-activity-editor/d2l-activity-score-editor.js

Avoids individual scheme, category, and grade items from being individually fetched when dialog is opened.
Task: TA154603 - Prevent /grade-candidates cache-primers from being fetched on every dialog open https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Ftask%2F601362328529&expandApp=486232622048
and TA155032 - Prevent /grade-schemes cache-primer from being fetched on every /grade-schemes GET
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Ftask%2F602157892421&expandApp=486232622048
from story: https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F600744235069&expandApp=486232622048&fdp=true?fdp=true
Whenever the dialog is opened, /grade-candidates needs to be re-fetched because it will have a different …

TA154603 - Prefetch schemes and candidates

---

components/d2l-activity-editor/d2l-activity-editor.js
components/d2l-activity-editor/d2l-activity-score-editor.js

Make sure main page is checked in BEFORE score-out-of api is called. This way, if we set to ungraded, then state will be not-in-gradebook (disassociating the grade) before setting score-out-of to empty. Fixes error "score out of must have a value when grade is associated".

fix: scoreOutOf error

---

components/d2l-activity-editor/state/associate-grade.js

https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F600744235069%2Ftasks&expandApp=486232622048&fdp=true?fdp=true

Don't need to re-fetch schemes if it was previously `undefined`

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-file-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor.js
components/d2l-activity-editor/lang/en.js

Co-authored with @quinnbudan 
- [US127570](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F602050357608&fdp=true?fdp=true): FACE HTML file - Support Sorting HTML Templates By Name 
This PR enables a config variable to sort HTML templates by name.
This PR enables a config variable to sort HTML templates by name. The config variable is passed into FACE by the LMS.
N/A
- https://github.com/Brightspace/lms/pull/12034

US127570 - sorting html templates by name

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-file-detail.js

- [DE44294](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fdefect%2F603490082955&fdp=true?fdp=true): FACE > HTML Template Selection dropdown cutoff in frame
When you expand the availability dates in FACE when creating an HTML file, the HTML template dropdown content will sometimes be slightly cutoff.
By changing the alignment on the dropdown, we can eliminate cases where the dropdown menu will be slightly cutoff
Bad Alignment:
Good Alignment: 
If applicable...

DE44294 - FACE > HTML Template Selection dropdown cutoff in frame

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-file-detail.js

- [US127570](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F602050357608&fdp=true?fdp=true): FACE HTML file - Support Sorting HTML Templates By Name
The first PR to sort templates did so in a less than ideal way (based on ASCII values for characters). This led to a sort that went:
1. Numbers
2. Uppercase letters
3. Symbols
4. Lowercase symbols
This PR fixes the sorting to perform the sort with the following order:
1. Symbols
2. Numbers
3. Letters 
Example of non-ideal sort:
Now:
The following was the first PR that was merged with a non-ideal sort
- https://github.com/BrightspaceHypermediaComponents/activities/pull/1860

US127570 - FACE HTML file - Support Sorting HTML Templates By Name

---

components/d2l-activity-editor/d2l-activity-content-editor/shared-components/d2l-activity-content-editor-title.js

- [DE43776](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fdefect%2F600734692385&fdp=true?fdp=true): FACE > Inconsistent error tooltips for Name and Dates
On FACE some face pages, the color and alignment of error tooltips is inconsistent.
This PR changes the state and alignment of error tooltips to ensure consistency.
Before:
After:

DE43776 - Inconsistent Error Tooltips for Name and Dates

---

components/d2l-activity-editor/d2l-activity-content-editor/web-link/d2l-activity-content-editor-link.js

- [DE43776](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fdefect%2F600734692385&fdp=true?fdp=true): FACE > Inconsistent error tooltips for Name and Dates
This is another instance of the fix from the following PR
https://github.com/BrightspaceHypermediaComponents/activities/pull/1871

DE43776: Inconsistent Error Tooltips for Weblink Name

---

components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-availability-editor.js

Brings the content dates editor inline with how assignments does it. That accordion component has an error property - so our content dates editor needed to add it's own error checking function and to use the MobxLitElement instead of LitElement so we can access the store.
Unfortunately there is a weird UI behavior where if the accordion is expanded with invalid dates and you attempt to save, it will close and then open. I think this is because the opened state is being controlled by that `hasError` value, which temporarily gets set to false while it is saving. This is in-line with how the Assignments Editor behaves as well so it might be best to leave it and ideally have the team that wrote the `d2l-activity-accordion-collapse` component to investigate.

Content with invalid dates can still be saved if you collapse the date controls first

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-file-detail.js

- [DE44349](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fdefect%2F603801138963&fdp=true?fdp=true): FACE > HTML Template Dropdown - Loading styled as a menu item
Loading in dropdown should not be styled as a menu item. The styling has been changed to match the "No content available" item.
Previous:
New:

DE44349: HTML Template Dropdown - Loading styled as a menu item

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-file-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/lti-link/d2l-activity-content-lti-link-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/lti-link/d2l-activity-content-lti-link-external-activity.js
components/d2l-activity-editor/d2l-activity-content-editor/lti-link/d2l-activity-content-lti-link-options.js
components/d2l-activity-editor/d2l-activity-content-editor/module/d2l-activity-content-module-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/shared-components/d2l-activity-content-editor-due-date.js
components/d2l-activity-editor/d2l-activity-content-editor/shared-components/d2l-activity-content-editor-title.js
components/d2l-activity-editor/d2l-activity-content-editor/web-link/d2l-activity-content-editor-link.js
components/d2l-activity-editor/d2l-activity-content-editor/web-link/d2l-activity-content-web-link-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/web-link/d2l-activity-content-web-link-url-preview.js

This pr sets out to improve the UX for the skeletons in the Content editors. 
It was noticed that the due date element was loading in way faster than everything else. This was because each component was handling it's own `skeleton` state by checking against their entity, and the due date was using the activity usage entity which is higher up the chain than everything else. 
As many of these components use the same entity, it made sense to let the `detail` part of the editor be in charge of the skeleton state and pass that down to each of the components. As `detail` is the one fetching the entity, the time for each sub-component refetching the same entity is negligible as it won't actually make another network request. The result of this is that each component will stop visual loading at …

Improve loading skeletons in Content editors

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-file-detail.js

- US127822: https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F602982229180
As part of our FACE initiative and revamp, we would like to support HTML template selection.
This PR makes the necessary changes to fetch the HTML template's contents, once one has been selected from the dropdown, and replaces the editor's contents with it (New HTML Editor, Old HTML Editor and NoWYSIWYG Text Editor).
- https://github.com/Brightspace/lms/pull/12252

FACE HTML file - Support Template Selection - Selecting a template

---

components/d2l-activity-editor/d2l-activity-content-editor/web-link/d2l-activity-content-web-link-detail.js
components/d2l-activity-editor/d2l-activity-content-editor/web-link/state/content-web-link.js
test/d2l-activity-editor/d2l-activity-content-editor/state/content-web-link.spec.js

Update naming for working copy stuff for weblinks, since they were updated [in this PR](https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/360).
Some code cleanup.
https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/360
We will need to merge the related PR first for the tests to pass.

Change weblink working copy methods

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-file-detail.js
components/d2l-activity-editor/lang/en.js

- [US129212](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F601858951433&fdp=true?fdp=true): FACE HTML - Add a browse button to the Template Selection Dropdown
Based on the Telemetry data, we will need a Browse option as well as the list of template HTML files. This PR adds functionality to browse for HTML templates in a dialog.

US129212: Add a browse button to the Template Selection Dropdown

---

.github/workflows/d2l-activities-backport.yml

Public repo cannot access self hosted runners on AWS
Updated runner to `ubuntu-latest` as this is a public repo
https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F603436954475&fdp=true?fdp=true

US129748 Updated runner to ubuntu latest

---

components/d2l-activity-editor/d2l-activity-html-new-editor.js

The "no-filter" property will tell the HTMLFilesController to not filter out scripts when previewing the HTML. This is necessary as we need to include MathJax as part of those scripts so that they can be properly rendered.

Do not filter scripts out when previewing HTML files

---

components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-file-detail.js
components/d2l-activity-editor/lang/en.js

- [US127819](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F602981033764&fdp=true?fdp=true): FACE HTML file - Support Template Selection - Text replacement confirmation dialog
When a user selects an HTML template (from dropdown or from browse) they should see a warning dialog about replacing content if the editor currently has any content. This PR creates said dialog to warn the user when they are going to replace content.

US127819 - Text replacement confirmation dialog

---

components/d2l-activity-editor/state/activity-usage.js

Needs updated activity usage entity, otherwise we will be comparing to the old entity which may be missing the `canCheckIn` action.
https://rally1.rallydev.com/#/10235005524d/dashboard?detail=%2Fuserstory%2F600744235069%2Ftasks&fdp=true?fdp=true

Fix dirty check in activity usage

---

components/d2l-activity-editor/state/working-copy.js

Recreating the entity meant the new entity had `this._checkedOut` set back to `null`, so the base `quiz/activity/assignment` would no longer know its `checkedOutHref`.
https://trello.com/c/wGtoz9Iz/430-after-a-change-to-quiz-timing-attempts-or-ip-restrictions-and-a-first-save-without-refresh-subsequent-changes-to-timing-attempts

Do not recreate the entity if it already exists

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-submission-and-completion.js
components/d2l-activity-editor/d2l-activity-assignment-editor/lang/en.js
components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment-submission-and-completion.js
components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.js
test/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.spec.js

[US128833 - [Restrict File Ext][UI] Add new dropdown for the restrict file extension options](https://rally1.rallydev.com/#/42960320374d/dashboard?detail=%2Fuserstory%2F600937249791)
Depends on [US128833 - adding support for update-allowable-filetype action for assignments](https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/362)

US128833 - adding allowable filetypes dropdown for assignments

---

components/d2l-quick-eval/d2l-quick-eval-submissions.js
test/d2l-quick-eval/d2l-quick-eval.html

After #1754, Quick Eval's "Load More" fails with an error as a query into the modified component's shadow DOM wasn't updated.

fix: Quick Eval load more breaking due to d2l-table changes

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-submission-and-completion.js
components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment-submission-and-completion.js
components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.js

Fixes related to [US128833 ](https://rally1.rallydev.com/#/42960320374d/dashboard?detail=%2Fuserstory%2F600937249791).
Now renders dropdown conditionally based on Submission Type.
Also fixing an error that was popping up when trying to save any submission types other than File submission.

US128833 - Allowable filetype fixes

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-submission-and-completion.js

https://rally1.rallydev.com/#/42960320374d/dashboard?detail=%2Fuserstory%2F606213375445
Added an extra undefined check for the assignment's `allowableFileType` property to avoid rendering anything when the d2l.Tools.Dropbox.RestrictFileExtensions ( Org ) config variable is off.

US130754 - adding undefined check for allowableFileType property

---

components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-submission-views-container.js

https://trello.com/c/IqtNwsoy/459-fixing-padding-on-submission-view-ui-story-us131579

fix: trello item, 131579 padding added

---

components/d2l-activity-editor/d2l-activity-score-editor.js

https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fuserstory%2F606249971567%2Ftasks&fdp=true
Face assignments was broken when not-in-gradebook. IsUngraded depends on ScoreOutOf so the latter has to be evaluated before the former.

fix: US130775 ungraded depends on scoreOutOf value

---

components/d2l-activity-editor/d2l-activity-score-editor.js
components/d2l-activity-editor/mixins/d2l-activity-editor-mixin.js
components/d2l-activity-editor/state/activity-usage.js

https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fuserstory%2F606249971567&fdp=true
This fixes the issue where the wrong grade was being updated. Now when we create a new grade, we fetch the new score value (which has already been updated by working copy) so that the `save` method within `scoring` doesn't think the maxGradePoints has been updated (and therefore doesn't do the PATCH on the old grade item).

fix: US130775 extra grade update

---

components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.js
components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-container.js
components/d2l-activity-editor/d2l-activity-rubrics/state/association-collection.js

[DE45687](https://rally1.rallydev.com/#/?detail=/defect/612303356763&fdp=true): [FACE] Removing indirectly associated rubrics may not store correct defaultScoringRubricId on an assignment
Todo:

DE45687 [FACE] Removing indirectly associated rubrics may not store correct `defaultScoringRubricId` on an Assignment

---

components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-submission-and-completion.js

[DE45521 ](https://rally1.rallydev.com/#/10153049633d/dashboard?detail=%2Fdefect%2F610904031713)
There is a defect where setting `allowableFyleType` to `.GIF` was not letting students submit ANY files to the assignment. 
Could not figure out why this only happens on `.GIF` during the investigation.
Saving the file ext. as lower case avoids this issue, this doesn't affect any other files as our file ext. comparisons are not case sensitive (eg. with `allowableFyleType` set to `.pdf`, students can submit both `.PDF` and `.pdf`)

DE45521 - Save custom allowable file types as lowercase

---

components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-container.js
components/d2l-activity-editor/d2l-activity-rubrics/state/association-collection.js
test/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.spec.js

[DE45687](https://rally1.rallydev.com/#/?detail=/defect/612303356763&fdp=true): [FACE] Removing indirectly associated rubrics may not store correct defaultScoringRubricId on an assignment
Previously the `defaultScoringRubric` dropdown would asynchronously add in the rubrics as they came in.
This change now causes the `defaultScoringRubric` dropdown to only re-render when all the rubrics that need to be fetched have returned.
May need to consider doing a disable and blur on the dropdown while that happens?

DE45687 Work with `async` default scoring rubric option loading
