BrightspaceHypermediaComponents/activities

- components/d2l-activity-list-item/d2l-activity-list-item.js
- demo/d2l-activity-list-item/index.html
- demo/index.html
- package.json
> Make the list item responsive

- components/d2l-activity-list-item/d2l-activity-list-item-enroll.js
- components/d2l-activity-list-item/d2l-activity-list-item.js
So I forgot to add what http method to use when assigning the course. This PR fixes that issue.
> Use the http method in the assign action.

- components/d2l-activity-list-item/ActivityListItemResponsiveConstants.js
- components/d2l-activity-list-item/d2l-activity-list-item.js
- demo/d2l-activity-list-item/index.html
- demo/data/base/activity.json
- test/d2l-activity-list-item/d2l-activity-list-item-test.html
- test/d2l-activity-list-item/d2l-activity-list-item-test.js
This adds responsive behaviour with proper breakpoints and styles for each breakpoint.
Optimizations to the description clamping has been made to speed up the process as well as make it more visually consistent.
The original 3 commits are splits up by functionality, demo and test code. 
Here is an image that shows each stage of the responsive behaviour. This is a screenshot of a modified demo page.
> Responsive behaviour

- components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/quizzes/quiz1.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/quizzes/quiz2.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/quizzes/quiz3.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/quizzes/quiz4.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/topics/topic1.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/topics/topic2.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/topics/topic3.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/topics/topic4.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/unassessedActivities.json
- test/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- test/d2l-evaluation-hub/data/quiz.json
- test/d2l-evaluation-hub/data/topic.json
- test/d2l-evaluation-hub/data/unassessedActivities.json
Adding in logic to pull quiz name for quizzes. Also changing `_headers` to an `Array` to better reflect the actual data.
> Fix for quizzes.

- components/d2l-evaluation-hub/build/lang/ar.js
- components/d2l-evaluation-hub/build/lang/de.js
- components/d2l-evaluation-hub/build/lang/en.js
- components/d2l-evaluation-hub/build/lang/es.js
- components/d2l-evaluation-hub/build/lang/fi.js
- components/d2l-evaluation-hub/build/lang/fr.js
- components/d2l-evaluation-hub/build/lang/ja.js
- components/d2l-evaluation-hub/build/lang/ko.js
- components/d2l-evaluation-hub/build/lang/nl.js
- components/d2l-evaluation-hub/build/lang/pt.js
- components/d2l-evaluation-hub/build/lang/sv.js
- components/d2l-evaluation-hub/build/lang/tr.js
- components/d2l-evaluation-hub/build/lang/zh-tw.js
- components/d2l-evaluation-hub/build/lang/zh.js
- components/d2l-evaluation-hub/lang/ar.json
- components/d2l-evaluation-hub/lang/de.json
- components/d2l-evaluation-hub/lang/en.json
- components/d2l-evaluation-hub/lang/es.json
- components/d2l-evaluation-hub/lang/fi.json
- components/d2l-evaluation-hub/lang/fr.json
- components/d2l-evaluation-hub/lang/ja.json
- components/d2l-evaluation-hub/lang/ko.json
- components/d2l-evaluation-hub/lang/nl.json
- components/d2l-evaluation-hub/lang/pt.json
- components/d2l-evaluation-hub/lang/sv.json
- components/d2l-evaluation-hub/lang/tr.json
- components/d2l-evaluation-hub/lang/zh-tw.json
- components/d2l-evaluation-hub/lang/zh.json
- package.json
- test/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
Surekha and Erin requested 2 minor updates.
> Update lang terms

- components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- test/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
This is just some cleanup that's cleaner to do now rather than weaved throughout my next PR.
> Indicate non-public functions with an underscore

- components/d2l-activity-list-item/d2l-activity-list-item.js
- package.json
This PR give the activity list item the ability to pass the responsibility of handling it's link to its parent. This is useful in the event a FRA is using the element and we want the FRA to handle page changes.
> The ability to send an event when clicked instead of direct to link

- components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- demo/d2l-evaluation-hub/data/activities/activitiesList/next.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/unassessedActivities.json
- test/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- test/d2l-evaluation-hub/data/next.json
- test/d2l-evaluation-hub/data/unassessedActivities.json
> Fix up test data and use new ui component

- components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- demo/d2l-evaluation-hub/d2l-evaluation-hub.html
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/enrollments/course.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/enrollments/course2.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/enrollments/filters/filters.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/enrollments/filters/filters2.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/enrollments/filters/roleMarkerFilter.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/enrollments/filters/roleMarkerFilter2.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/enrollments/users/user.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/enrollments/users/user2.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/orgs/activity1.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/orgs/activity2.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/orgs/activity3.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/orgs/activity4.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/users/master1.json
- demo/d2l-evaluation-hub/data/activities/activitiesList/activities/users/master2.json
- test/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- test/d2l-evaluation-hub/data/course.json
- test/d2l-evaluation-hub/data/filters.json
- test/d2l-evaluation-hub/data/master.json
- test/d2l-evaluation-hub/data/org.json
- test/d2l-evaluation-hub/data/roleMarkerFilter.json
- test/d2l-evaluation-hub/data/user-enrollment.json
* The new column shows up if the correct flags are on, I testing in LMS (see image above)
> * US103318 -  Supply and fetch master teacher data

- components/d2l-activity-evaluation-icon/d2l-activity-evaluation-icon-base.js
- demo/d2l-activity-evaluation-icon/d2l-activity-evaluation-icon-base.html
- package.json
- test/d2l-activity-evaluation-icon/d2l-activity-evaluation-icon-base.js
Adding tooltip.
* Talking to Erin she wants it on the bottom
* Talking with Erin she wants offset of 6
* The icon is 18px, since offset is calculated off center, we cover the 9px + 6px offset, which makes it 15
> US103573 - Add tooltip

- components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- demo/d2l-evaluation-hub/demo-data-parser.js
- demo/d2l-evaluation-hub/table.js
- test/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- test/d2l-evaluation-hub/data/next.json
- test/d2l-evaluation-hub/data/unassessedActivities.json
Now using `localized-formatted-date`.
> get new localized date and fix tests

- demo/d2l-evaluation-hub/demo-data-parser.js
- demo/d2l-evaluation-hub/table.js
Supporting draft evaluation entity in demo data
> Support evaluation entity in demo data

- components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- test/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
* Rendering column individually to allow me to place the draft icon in more easily. Josh was doing something similar as well for his activity name component.
> Render columns individual

- components/d2l-activity-evaluation-icon/d2l-activity-evaluation-icon-base.js
Removing since not working correctly
> Remove boundary on tooltip

- components/d2l-activity-name/d2l-activity-name.js
We should probably be doing this for every component
> Strip-whitespace for activity-name

- components/d2l-evaluation-hub/build/lang/ar.js
- components/d2l-evaluation-hub/build/lang/de.js
- components/d2l-evaluation-hub/build/lang/en.js
- components/d2l-evaluation-hub/build/lang/es.js
- components/d2l-evaluation-hub/build/lang/fi.js
- components/d2l-evaluation-hub/build/lang/fr.js
- components/d2l-evaluation-hub/build/lang/ja.js
- components/d2l-evaluation-hub/build/lang/ko.js
- components/d2l-evaluation-hub/build/lang/nl.js
- components/d2l-evaluation-hub/build/lang/pt.js
- components/d2l-evaluation-hub/build/lang/sv.js
- components/d2l-evaluation-hub/build/lang/tr.js
- components/d2l-evaluation-hub/build/lang/zh-tw.js
- components/d2l-evaluation-hub/build/lang/zh.js
- components/d2l-evaluation-hub/lang/ar.json
- components/d2l-evaluation-hub/lang/de.json
- components/d2l-evaluation-hub/lang/en.json
- components/d2l-evaluation-hub/lang/es.json
- components/d2l-evaluation-hub/lang/fi.json
- components/d2l-evaluation-hub/lang/fr.json
- components/d2l-evaluation-hub/lang/ja.json
- components/d2l-evaluation-hub/lang/ko.json
- components/d2l-evaluation-hub/lang/nl.json
- components/d2l-evaluation-hub/lang/pt.json
- components/d2l-evaluation-hub/lang/sv.json
- components/d2l-evaluation-hub/lang/tr.json
- components/d2l-evaluation-hub/lang/zh-tw.json
- components/d2l-evaluation-hub/lang/zh.json
* Terms were found taken from https://rally1.rallydev.com/#/42960320374d/detail/userstory/286605189004
> US104018 - Adding langTerms for error messages

- components/d2l-activity-name/d2l-activity-name.js
- demo/d2l-activity-name/d2l-activity-name.html
- demo/d2l-activity-name/data/topic1.json
- demo/d2l-activity-name/update-direction.js
Screenshot of demo. Resizing works too - feel free to checkout locally and test demo page out.
> Add proper spacing as per design; add nowrap to component

- components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- demo/d2l-evaluation-hub/demo-data-parser.js
- demo/d2l-evaluation-hub/page-handler.js
- package.json
- test/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
* Alert when failing to load data
* In future PR may add tryAgain functionality to the alert to try again from that dialog as well
> US104018 - Show alert when failing to load more data

- components/d2l-activity-evaluation-icon/d2l-activity-evaluation-icon.js
- demo/d2l-activity-evaluation-icon/d2l-activity-evaluation-icon.html
- demo/d2l-activity-evaluation-icon/data/activity-draft.json
- demo/index.html
- test/d2l-activity-evaluation-icon/d2l-activity-evaluation-icon.html
- test/d2l-activity-evaluation-icon/d2l-activity-evaluation-icon.js
- test/d2l-activity-evaluation-icon/data/activity-draft.json
- test/d2l-activity-evaluation-icon/data/activity-no-evaluation.json
- test/index.html
> US103573 - Adding HM wrapper for activity icon

- demo/d2l-evaluation-hub/table.js
Adding sort by last name http://search.dev.d2l/source/xref/Lms/le/activities/D2L.LE.Activities.Extensibility/Api/Hypermedia/Sorts/ByName/SortByLastName.cs#37
> US104674 - Add sort by last name

- components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
* Changing data structure to allow for multiple "headers" within a "header column"
* This is to support the two header (firstName and lastName) within one column
> US104674 - Put headers into header columns

- components/d2l-evaluation-hub/build/lang/ar.js
- components/d2l-evaluation-hub/build/lang/de.js
- components/d2l-evaluation-hub/build/lang/en.js
- components/d2l-evaluation-hub/build/lang/es.js
- components/d2l-evaluation-hub/build/lang/fi.js
- components/d2l-evaluation-hub/build/lang/fr.js
- components/d2l-evaluation-hub/build/lang/ja.js
- components/d2l-evaluation-hub/build/lang/ko.js
- components/d2l-evaluation-hub/build/lang/nl.js
- components/d2l-evaluation-hub/build/lang/pt.js
- components/d2l-evaluation-hub/build/lang/sv.js
- components/d2l-evaluation-hub/build/lang/tr.js
- components/d2l-evaluation-hub/build/lang/zh-tw.js
- components/d2l-evaluation-hub/build/lang/zh.js
- components/d2l-evaluation-hub/lang/ar.json
- components/d2l-evaluation-hub/lang/de.json
- components/d2l-evaluation-hub/lang/en.json
- components/d2l-evaluation-hub/lang/es.json
- components/d2l-evaluation-hub/lang/fi.json
- components/d2l-evaluation-hub/lang/fr.json
- components/d2l-evaluation-hub/lang/ja.json
- components/d2l-evaluation-hub/lang/ko.json
- components/d2l-evaluation-hub/lang/nl.json
- components/d2l-evaluation-hub/lang/pt.json
- components/d2l-evaluation-hub/lang/sv.json
- components/d2l-evaluation-hub/lang/tr.json
- components/d2l-evaluation-hub/lang/zh-tw.json
- components/d2l-evaluation-hub/lang/zh.json
Following example from LE. We will hardCode the seperator: http://search.dev.d2l/source/xref/Lms/platformTools/manageUsers/web/ManageUsersPage.cs#239
> LangTerms For names

- demo/d2l-evaluation-hub/page-handler.js
- demo/d2l-evaluation-hub/sort-handler.js
* Updating demo data to reflect changes being applied in https://git.dev.d2l/projects/CORE/repos/lp/pull-requests/12638/overview
> US104761 - Mock sort state prop

- components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- test/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
> - Updating performqueryaction to use alternate method

- components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
> Place arrow left of comma when sorting by first name

- components/d2l-activity-name/d2l-activity-name.js
- components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- demo/d2l-activity-name/d2l-activity-name.html
- demo/d2l-activity-name/data/topic1.json
- demo/d2l-evaluation-hub/d2l-evaluation-hub-activities-list-empty.html
- demo/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.html
- demo/d2l-evaluation-hub/d2l-evaluation-hub.html
- demo/d2l-evaluation-hub/update-direction.js
- ~Fix table RTL design~
- Fix Activity Name RTL
- Fix loading button RTL position
- Add the RTL file to the Quick Eval demos
> Fix Some RTL Issues shown by the screenshot in Mile's PR

- components/d2l-evaluation-hub/build/lang/ar.js
- components/d2l-evaluation-hub/build/lang/de.js
- components/d2l-evaluation-hub/build/lang/en.js
- components/d2l-evaluation-hub/build/lang/es.js
- components/d2l-evaluation-hub/build/lang/fi.js
- components/d2l-evaluation-hub/build/lang/fr.js
- components/d2l-evaluation-hub/build/lang/ja.js
- components/d2l-evaluation-hub/build/lang/ko.js
- components/d2l-evaluation-hub/build/lang/nl.js
- components/d2l-evaluation-hub/build/lang/pt.js
- components/d2l-evaluation-hub/build/lang/sv.js
- components/d2l-evaluation-hub/build/lang/tr.js
- components/d2l-evaluation-hub/build/lang/zh-tw.js
- components/d2l-evaluation-hub/build/lang/zh.js
- components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- components/d2l-evaluation-hub/lang/ar.json
- components/d2l-evaluation-hub/lang/de.json
- components/d2l-evaluation-hub/lang/en.json
- components/d2l-evaluation-hub/lang/es.json
- components/d2l-evaluation-hub/lang/fi.json
- components/d2l-evaluation-hub/lang/fr.json
- components/d2l-evaluation-hub/lang/ja.json
- components/d2l-evaluation-hub/lang/ko.json
- components/d2l-evaluation-hub/lang/nl.json
- components/d2l-evaluation-hub/lang/pt.json
- components/d2l-evaluation-hub/lang/sv.json
- components/d2l-evaluation-hub/lang/tr.json
- components/d2l-evaluation-hub/lang/zh-tw.json
- components/d2l-evaluation-hub/lang/zh.json
> Light Table Style and Table Summary

- components/d2l-evaluation-hub/d2l-evaluation-hub.js
- demo/d2l-evaluation-hub/d2l-evaluation-hub.html
Display title and filters on the same line if the title is passed in as an attribute
> Move title into the web component

- components/d2l-evaluation-hub/d2l-evaluation-hub.js
- demo/d2l-evaluation-hub/d2l-evaluation-hub.html
`title` is a key word that does special stuff.  Use `page-title` instead
> Actually use page-title

- components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- test/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- test/d2l-evaluation-hub/data/next.json
- test/d2l-evaluation-hub/data/unassessedActivities.json
I closed the other one, it was giving me a lot of trouble after all the merges from master
> US104672 - add filter and sort to eval link

- components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- demo/d2l-evaluation-hub/demo-data-parser.js
- test/d2l-evaluation-hub/data/org.json
* Depends on https://git.dev.d2l/projects/CORE/repos/lp/pull-requests/12690/overview
* Smoke tested it worked in LMS when dependency resolved
> Use the hotlink in organizations to get master teacher information

- components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- test/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
This does look better and works well  I made sure the screenreader experience with this change was still smooth.
> Hide the load more button when we are loading

- components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- demo/d2l-evaluation-hub/page-handler.js
> Remove loading spinner when error detected for loading more entries

- components/d2l-evaluation-hub/d2l-evaluation-hub.js
- package.json
- test/d2l-evaluation-hub/data/activityNameFilter-c806bbc6-cfb3-4b6b-ae74-d5e4e319183d.json
- test/d2l-evaluation-hub/data/courseFilter-f2b32f03-556a-4368-945a-2614b9f41f76.json
- test/d2l-evaluation-hub/data/dateFilter-05de346e-c94d-4e4b-b887-9c86c9a80351.json
- test/d2l-evaluation-hub/data/filters.json
- test/d2l-evaluation-hub/data/primaryFacilitatorFilter-35b3aca0-c10c-436d-b369-c8a3022455e3.json
~Will need to merge this after https://github.com/BrightspaceHypermediaComponents/common/pull/9~ Merged
> Filter is changing, update our whitelist and our tests

- components/d2l-activity-name/d2l-activity-name.js
> display activity name inline

- components/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
- demo/d2l-evaluation-hub/demo-data-parser.js
- package.json
- test/d2l-evaluation-hub/d2l-evaluation-hub-activities-list.js
Just drop the `d2l-profile-image` in there.
**Updated** - Here's what it looks like:
> Just add the profile image

- .travis.yml
- package.json
- scripts/remove_attest_from_project.js
- test/.eslintrc.json
- test/attest-helper.js
- test/d2l-activity-list-item/d2l-activity-list-item-test.html
- test/d2l-activity-list-item/d2l-activity-list-item-test.js
Also add an accessibility test to d2l-activity-list-item
> Add attest to the repo.

- demo/d2l-quick-eval/d2l-quick-eval-activities-list.html
- demo/d2l-quick-eval/d2l-quick-eval.html
- demo/d2l-quick-eval/demo-data-parser.js
- demo/d2l-quick-eval/page-handler.js
This is step one:
* Allow configuring default page size mock server uses with query parameter
> US104726 - Support page size in query param of demo

- demo/d2l-quick-eval/sort-handler.js
* Looks like I made a mistake at some point
* This should fix the demo for sorting
> Fix sort demo bug

- components/d2l-quick-eval/d2l-quick-eval-activities-list.js
**US105008**
Stacey fixed table for us! https://github.com/BrightspaceUI/table/releases/tag/v2.2.4
Many thanks @svanherk !
This PR should take care of things on our end.
> Set table background to transparent

- package.json
Version bump for this:
https://github.com/BrightspaceHypermediaComponents/activities/pull/129
Next time - remember to do it in the same PR...
> Version bump to 2.0.1

- components/d2l-activity-evaluation-icon/build/lang/ar.js
- components/d2l-activity-evaluation-icon/build/lang/de.js
- components/d2l-activity-evaluation-icon/build/lang/es.js
- components/d2l-activity-evaluation-icon/build/lang/fr.js
- components/d2l-activity-evaluation-icon/build/lang/ja.js
- components/d2l-activity-evaluation-icon/build/lang/ko.js
- components/d2l-activity-evaluation-icon/build/lang/nl.js
- components/d2l-activity-evaluation-icon/build/lang/pt.js
- components/d2l-activity-evaluation-icon/build/lang/sv.js
- components/d2l-activity-evaluation-icon/build/lang/tr.js
- components/d2l-activity-evaluation-icon/build/lang/zh-tw.js
- components/d2l-activity-evaluation-icon/build/lang/zh.js
Building translations from https://github.com/BrightspaceHypermediaComponents/activities/pull/139
> Build translations

- components/d2l-quick-eval/d2l-quick-eval-activities-list.js
> US105617 - Remove repetition of name in screen reader when navigating with arrows

- components/d2l-quick-eval/d2l-quick-eval-activities-list.js
- demo/d2l-quick-eval/table.js
- test/d2l-quick-eval/d2l-quick-eval-activities-list-sorting.js
> Sort by Primary Facilitator

- components/d2l-quick-eval/compatability/universal-methods.js
- components/d2l-quick-eval/d2l-quick-eval-activities-list.js
- test/d2l-quick-eval/compatability/universal-methods.html
- test/d2l-quick-eval/compatability/universal-methods.js
- test/index.html
* Progress to support IE11
* This gets demo to work with fake data but not with real data yet
> DE33386 - Demo working in IE11

- components/d2l-quick-eval/compatability/universal-methods.js
- components/d2l-quick-eval/d2l-quick-eval-activities-list.js
- test/d2l-quick-eval/compatability/universal-methods.js
* On initial load QE should now load in IE11
* Filtering still doesn't work
> DE33386 - Allow QE to load in IE11 with real LMS hookup

- components/d2l-quick-eval/QuickEvalLocalize.js
* Testing by changing the `lang` attribute on the html tag
> US105697 - Supporting new locales

- components/d2l-quick-eval/d2l-quick-eval-activities-list.js
- components/d2l-quick-eval/d2l-quick-eval-search-results-summary-container.js
- components/d2l-quick-eval/d2l-quick-eval.js
- test/d2l-quick-eval/d2l-quick-eval-search-results-summary-container.html
- test/d2l-quick-eval/d2l-quick-eval.html
- test/index.html
Applying https://github.com/BrightspaceHypermediaComponents/activities/pull/169 to `20.19.5`
> Apply cert fix for US106128 to the 20.19.5 release branch

- components/d2l-activity-card/d2l-activity-card.js
- components/d2l-activity-list-item/d2l-activity-list-item.js
- demo/d2l-activity-list-item/index.html
- test/d2l-activity-card/d2l-activity-card-test.html
- test/d2l-activity-card/d2l-activity-card-test.js
… shimmers to pulsing (even for text placeholders).
Rename shimmer to placeholer so it's more generic.
Change the href of activity-card to always be activity homepage.
Story: https://rally1.rallydev.com/#/39602890252ud/detail/userstory/304121020968
> Change loading animation in activity-card and activity-list-item from… 

- package.json
> New version: 3.1.1

- components/d2l-quick-eval/QuickEvalLogging.js
- components/d2l-quick-eval/d2l-quick-eval-activities-list.js
- components/d2l-quick-eval/d2l-quick-eval.js
- test/d2l-quick-eval/d2l-quick-eval-logging.html
- test/d2l-quick-eval/quick-eval-logging-test-component.js
- test/index.html
> US105214 - Add ability to log error

- components/d2l-quick-eval/d2l-quick-eval-activities.js
- components/d2l-quick-eval/d2l-quick-eval-view-toggle.js
- components/d2l-quick-eval/d2l-quick-eval.js
- demo/d2l-quick-eval/d2l-quick-eval-activities.html
- demo/d2l-quick-eval/d2l-quick-eval.html
- demo/index.html
- test/d2l-quick-eval/d2l-quick-eval.html
US105774: https://rally1.rallydev.com/#/238990806412d/detail/userstory/299142688352
> Empty activity page

- components/d2l-activity-card/d2l-activity-card.js
- components/d2l-quick-eval/behaviors/d2l-hm-search-behavior.js
- components/d2l-quick-eval/d2l-quick-eval-activities.js
- components/d2l-quick-eval/d2l-quick-eval.js
- test/d2l-quick-eval/behaviors/d2l-hm-search-behavior-test-component.js
- test/d2l-quick-eval/behaviors/d2l-hm-search-behavior.html
- test/d2l-quick-eval/behaviors/d2l-hm-search-behavior.js
- test/index.html
**US106345** https://rally1.rallydev.com/#/238990806412d/detail/userstory/303650255168
> Extract d2l-hm-search-behavior

- components/d2l-quick-eval/behaviors/d2l-quick-eval-siren-helper-behavior.js
- components/d2l-quick-eval/d2l-quick-eval-activities-list.js
- demo/d2l-quick-eval/activity-handler.js
- demo/d2l-quick-eval/d2l-quick-eval.html
- demo/d2l-quick-eval/table.js
Needs to go in together with
* https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/124/overview
> US107199 - Use user preference for date time format

- components/d2l-quick-eval/d2l-quick-eval-submissions-table.js
- components/d2l-quick-eval/d2l-quick-eval-submissions.js
Moving more decision making to the controller. The controller doesn't need to know about `_pageNextHref` it only needs to know if it should render the load-more button or not.
> Move nextPageHref from table to controller

- components/d2l-quick-eval/d2l-quick-eval-submissions-table.js
- components/d2l-quick-eval/d2l-quick-eval-submissions.js
Following the pattern of calculating in the controller and then telling `table` what's good
> Move last decision making out of `table`

- components/d2l-quick-eval/build/lang/ar.js
- components/d2l-quick-eval/build/lang/da-dk.js
- components/d2l-quick-eval/build/lang/de.js
- components/d2l-quick-eval/build/lang/es.js
- components/d2l-quick-eval/build/lang/fr-fr.js
- components/d2l-quick-eval/build/lang/fr.js
- components/d2l-quick-eval/build/lang/ja.js
- components/d2l-quick-eval/build/lang/ko.js
- components/d2l-quick-eval/build/lang/nl.js
- components/d2l-quick-eval/build/lang/pt.js
- components/d2l-quick-eval/build/lang/sv.js
- components/d2l-quick-eval/build/lang/tr.js
- components/d2l-quick-eval/build/lang/zh-tw.js
> MANUALLY add langterms after merging the langterm PR

- package.json
Update this repo in version 20197 to use the new translations from organization repo.
> Update Org to V5

- components/d2l-quick-eval/compatability/ie11shims.js
- test/d2l-quick-eval/compatability/ie11shims.js
* Backporting for cert https://github.com/BrightspaceHypermediaComponents/activities/pull/233
> DE34932 - Treate plus as space

- components/d2l-quick-eval/activities-list/d2l-quick-eval-activities-list.js
- test/d2l-quick-eval/d2l-quick-eval-activities-list.js
Changed the markup to use `<ul>` and `<li>` for screen-readers. Also changed the headers to `h2` from `h3`.
> US107131/ min activities list

- test/d2l-activity-name/data/assignment1.json
- test/d2l-activity-name/data/quizAttempt1.json
- test/d2l-activity-name/data/topic1.json
Might as well put these in since it makes our JSON more realistic
> Tweaks to json

- components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js
- demo/d2l-quick-eval/d2l-quick-eval-activities.html
Not showing due date if the duedate object is falsey. Maybe there is a better way to check for this?
> don't show due date if there is none

- components/d2l-quick-eval/activities-list/d2l-quick-eval-activities-list.js
- components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js
- components/d2l-quick-eval/behaviors/d2l-quick-eval-siren-helper-behavior.js
- components/d2l-quick-eval/d2l-quick-eval-activities.js
- demo/d2l-quick-eval/interceptor.js
- demo/index.html
- test/d2l-quick-eval/d2l-quick-eval-activities.js
- test/d2l-quick-eval/data/assignmentEvaluationStatus.json
- test/d2l-quick-eval/data/quizEvaluationStatus.json
- test/d2l-quick-eval/data/topicEvaluationStatus.json
[US108297](https://rally1.rallydev.com/#/detail/userstory/318899091508?fdp=true): [UI] Hook Publish All for  all activities - Currently supported Assignments and Discussions
This is just the logic - there is a follow up story to handle the confirmation dialog/error messages/etc.
> Wire up publish all

- components/d2l-quick-eval/d2l-quick-eval-view-toggle.js
- components/d2l-quick-eval/d2l-quick-eval.js
- demo/d2l-quick-eval/d2l-quick-eval-view-toggle.html
- test/d2l-quick-eval/d2l-quick-eval-view-toggle.html
- test/d2l-quick-eval/d2l-quick-eval-view-toggle.js
Since toggle state isn't part of HM we will need to pass down relative url to update the config, as well as its current state
> US107861 - Use and save toggle state

- components/d2l-quick-eval/build/lang/de.js
- components/d2l-quick-eval/build/lang/pt.js
- components/d2l-quick-eval/lang/de.json
- components/d2l-quick-eval/lang/pt.json
> Fix translator errors

- components/d2l-quick-eval/d2l-quick-eval.js
Not sure if linting either isn't enabled or isn't able to catch this kind of error...
> fixing extra quote

- components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js
Erin reviewed with other designers and recommended this change.
> change activity-card border to mica

- components/d2l-quick-eval/activities-list/d2l-quick-eval-activities-list.js
I think it is better and simple to use d2l-typography styles - http://design.d2l/style/typography/.
Confirmed with Erin that heading is h2 with d2l Heading 3 - Lato Bold 20 style.
> use D2L typography styles

- components/d2l-quick-eval/build/lang/fr-fr.js
- components/d2l-quick-eval/lang/fr-fr.json
Note - Looks like this term did not get translated and I do not know how such things get flagged by the lang term process.  I tried to ask - https://d2l.slack.com/archives/C0TF4KSGZ/p1560861531005500
> using the LMS term for Assignment in fr-fr package instead of english

- components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card-action-button.js
> US109176 - add cursor style

- components/d2l-quick-eval/d2l-quick-eval-activities.js
Problem: After publishAll, we were not updating the publish action to match the actual backend state.
Solution: also update publishAction after publishAll
> US108701 - also update publishAction after publishAll

- components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card-items.js
- components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js
* Should make things usable in Edge now
> US108830 - Fix edge

- components/d2l-activity-name/d2l-activity-name.js
- components/d2l-quick-eval/activities-list/d2l-quick-eval-activities-list.js
> add text overflow

- components/d2l-quick-eval/build/lang/ar.js
- components/d2l-quick-eval/build/lang/da-dk.js
- components/d2l-quick-eval/build/lang/de.js
- components/d2l-quick-eval/build/lang/es.js
- components/d2l-quick-eval/build/lang/fi.js
- components/d2l-quick-eval/build/lang/fr-fr.js
- components/d2l-quick-eval/build/lang/fr.js
- components/d2l-quick-eval/build/lang/ja.js
- components/d2l-quick-eval/build/lang/ko.js
- components/d2l-quick-eval/build/lang/nl.js
- components/d2l-quick-eval/build/lang/pt.js
- components/d2l-quick-eval/build/lang/sv.js
- components/d2l-quick-eval/build/lang/tr.js
- components/d2l-quick-eval/build/lang/zh-tw.js
- components/d2l-quick-eval/build/lang/zh.js
- components/d2l-quick-eval/lang/ar.json
- components/d2l-quick-eval/lang/da-dk.json
- components/d2l-quick-eval/lang/de.json
- components/d2l-quick-eval/lang/es.json
- components/d2l-quick-eval/lang/fi.json
- components/d2l-quick-eval/lang/fr-fr.json
- components/d2l-quick-eval/lang/fr.json
- components/d2l-quick-eval/lang/ja.json
- components/d2l-quick-eval/lang/ko.json
- components/d2l-quick-eval/lang/nl.json
- components/d2l-quick-eval/lang/pt.json
- components/d2l-quick-eval/lang/sv.json
- components/d2l-quick-eval/lang/tr.json
- components/d2l-quick-eval/lang/zh-tw.json
- components/d2l-quick-eval/lang/zh.json
> Adding localization entries for all languages.

- components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js
Fixes a problem where cards overflow due to a long title.
> Fix card-title overflow

- components/d2l-quick-eval/d2l-quick-eval-activities.js
as per design on https://rally1.rallydev.com/#/238990806412d/detail/userstory/329131006348?fdp=true
> move cat image down via padding

- components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js
- demo/d2l-quick-eval/d2l-quick-eval-activity-card.html
- test/d2l-quick-eval/d2l-quick-eval-activity-card.js
Should have no visual change outside of fixing the spacing between the bullet points and the text.
> Adding quick eval subititle to activity card.

- components/d2l-quick-eval/behaviors/d2l-quick-eval-siren-helper-behavior.js
- test/d2l-quick-eval/data/unassessedActivitiesCollection.json
Just using the new prop.
[ DO NOT MERGE UNTIL BACK END IS IN.](https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/2817/overview)
> use new localized date

- components/d2l-quick-eval/behaviors/d2l-quick-eval-siren-helper-behavior.js
- test/d2l-quick-eval/data/unassessedActivitiesCollection.json
Reverts BrightspaceHypermediaComponents/activities#313
> Revert "use new localized date"

- components/d2l-quick-eval/behaviors/d2l-quick-eval-siren-helper-behavior.js
- test/d2l-quick-eval/data/unassessedActivitiesCollection.json
Reverts BrightspaceHypermediaComponents/activities#317
> Revert "Revert "use new localized date""

- components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card-unread-submissions.js
- components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card.js
- components/d2l-quick-eval/d2l-quick-eval-activities.js
Should still look and behave as previously, except now there's a tab stop.
> Changing unread submission to use link.

- package.json
> Bumping version for ci.

- components/d2l-quick-eval/behaviors/d2l-quick-eval-siren-helper-behavior.js
- components/d2l-quick-eval/d2l-quick-eval-submissions-table.js
- components/d2l-quick-eval/d2l-quick-eval-submissions.js
Two really small items from the Lockhart list:
`Kitchen Sink - Break out of if-statements early (Slide 24)`
`Kitchen Sink - String template literals (Slide 25)`
> String template literals, and break out of ifs early

- components/d2l-quick-eval/behaviors/d2l-quick-eval-telemetry-behavior.js
- test/d2l-quick-eval/behaviors/d2l-quick-eval-telemetry-behavior.js
Tests are promised, I don't think that `_markExists` really needs one, but if someone wants one I wont argue against adding it.
> adding tests for view telemetry

- components/d2l-quick-eval/activity-card/d2l-quick-eval-activity-card-items.js
> removed visibleOnAncestorBehaviour

- .travis.yml
Fix for the Travis Config causing the version number to be bumped twice.
> Fix New Travis Config

- components/d2l-activity-editor/lang/en.js
Forgot to remove this in #415, but it's no longer needed.
> US110605 Followup: remove unused lang folder

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
- components/d2l-activity-editor/d2l-activity-editor.js
- demo/d2l-activity-editor/d2l-activity-assignment-editor/data/assignmentActivity.json
- package.json
When the assignment name is updated, this will show "Saving..." as the network request occurs. When the network request successfully completes, it shows "✔️ Saved" after a few moments (the delay is set by the component itself, and is not configurable). If the network request fails, the component hides itself (behaviour that is also defined by the component itself, and is not configurable).
> US110194 Add autosave component

- components/d2l-quick-eval/d2l-quick-eval-activities.js
part 2 of this PR https://github.com/BrightspaceHypermediaComponents/common/pull/33
proof: ![Screen Shot 2019-10-03 at 5 27 09 PM](https://user-images.githubusercontent.com/52468201/66167497-43046880-e608-11e9-85af-ff2e59e2c9ec.png)
> use label instead of aria-label in d2l-hm-search

- components/d2l-quick-eval/d2l-quick-eval-submissions.js
already added it for activities.
> added label to submissions too

- test/d2l-quick-eval/perceptual/d2l-quick-eval-activity-card-new-submissions.visual-diff.html
- test/d2l-quick-eval/perceptual/d2l-quick-eval-activity-card-new-submissions.visual-diff.js
> add vdiff coverage for new submissions

- components/d2l-activity-admin-list/d2l-activity-admin-list.js
- components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
- demo/d2l-activity-collection-editor/d2l-activity-collection-editor-demo.html
- demo/data/base/collection.json
- demo/data/base/learning-path-activity-usage.json
- package.json
Depends on: https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/77
> adding edit link for learning path activity usages.

- components/d2l-quick-eval/d2l-quick-eval.js
- components/d2l-quick-eval/dismiss/d2l-quick-eval-ellipsis-menu.js
This is (hopefully) the first Lit component we make in quick-eval. This is what it looks like:
Not sure what to do about the "double chin", open to ideas about that.
Will add lang terms soon. I promise 🤞
> added dismiss menu

- components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
- demo/data/base/organization.json
Depends on: https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/87
> using specialization entity from siren-sdk

- components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
Setters to apply changes to the database when users save their edited title and description have been added.
> Added setters to edit-in-place integration

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
Bad merge resulted in showing the attachments stuff twice. I'm excited about attachments, but that seems a bit overkill tbh
> US110586 Fixup

- components/d2l-quick-eval/behaviors/d2l-quick-eval-siren-helper-behavior.js
- components/d2l-quick-eval/d2l-quick-eval-activities.js
- components/d2l-quick-eval/dismiss/d2l-quick-eval-action-dismiss-dialog.js
- components/d2l-quick-eval/dismiss/dismiss-types.js
- demo/d2l-quick-eval/d2l-quick-eval-activities.html
- demo/d2l-quick-eval/d2l-quick-eval.html
After this PR, you should be able to dismiss activities forever. Next up is `dismiss until`
> Add Dismiss Forever

- components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
When changing the hidden state the list no longer flashes:
> No more flashing for the collection editor

- components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
Fixing the tab order for this page
> Fix tab order

- components/d2l-quick-eval/dismiss/d2l-quick-eval-action-dismiss-dialog.js
> [US112301] Clear the selected options on opening the dialog

- components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
Adds the X and when you press it the course is removed.
> Remove a item from a collection

- components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
- components/d2l-activity-editor/d2l-activity-visibility-editor.js
> Hide hidden/visible toggle

- components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
> Add the course subtitle

- components/d2l-quick-eval/d2l-quick-eval-activities.js
- components/d2l-quick-eval/dismiss/d2l-quick-eval-action-dismiss-dialog.js
Wanted to address small things that annoyed me. Just a mini-dragon-slayer.
Specifically:
When we press cancel in the dialog it logs errors.
I didn't like the way we reset the dialog.
> minor fixes

- README.md
Noticed it was outdated, so I'm just fixing it up.
> Update Vdiff message in README

- components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
Spacing for the main desktop view.
Out of scope: 
Localization
responsive
> Create Page: Polish step 1

- components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
- components/d2l-activity-collection-editor/lang/en.js
- components/d2l-activity-collection-editor/lang/fr.js
- components/d2l-activity-collection-editor/localization.js
Localization and loading skeletons for create learning path page (not including the Add Activity Dialog)
> Localization and Loading Skeletons

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
- components/d2l-activity-editor/d2l-activity-editor.js
> Move save-status to footer

- components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
- components/d2l-activity-collection-editor/lang/en.js
- components/d2l-activity-collection-editor/lang/fr.js
> When there are no activities.

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
- components/d2l-activity-editor/d2l-activity-score-editor.js
- components/d2l-activity-editor/lang/en.js
Moving score up, to the left of due date. Also using "number" input for score and updating the wording of empty score error.
> Us111489 move score position

- components/d2l-quick-eval/d2l-quick-eval-activities.js
- components/d2l-quick-eval/d2l-quick-eval-submissions.js
- components/d2l-quick-eval/d2l-quick-eval.js
- components/d2l-quick-eval/dismiss/d2l-quick-eval-ellipsis-menu.js
Just adding the properties, not doing anything with them yet
backend: https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/6806/overview
> Add course level properties to qe

- components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
> Fix X going over nav.

- components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
Load more now shows spinner
Can only be clicked once
> Fix Load More in activity browser

- components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js
Should be the microphone per the designs, not the headphones.
> US111909 Fixup audio icon

- components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
- components/d2l-activity-collection-editor/lang/en.js
- components/d2l-activity-collection-editor/lang/fr.js
https://rally1.rallydev.com/#/39602890252d/detail/userstory/324781707916?fdp=true
When a user clicks on the remove course we want  a toast to notify the user of the task.
> Added alert message when user delete an activity

- components/d2l-activity-editor/.eslintrc.json
- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-footer.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/lang/en.js
- components/d2l-activity-editor/d2l-activity-editor-buttons.js
- components/d2l-activity-editor/lang/en.js
- package.json
- test/d2l-activity-editor/d2l-activity-editor-buttons.html
- test/d2l-activity-editor/d2l-activity-editor-buttons.js
- test/index.html
First step for implementing save/cancel - add a save event.
> Refactor save/cancel buttons into activity component so resuable and add save event

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
- test/d2l-activity-editor/mixins/d2l-activity-editor-container-mixin.js
> This just hooks up the save mixins to the top level activity assignment editor

- components/d2l-activity-editor/localization.js
Fixes https://trello.com/c/bqQWq8Cj/88-rtl-translated-items-differ-than-other-languages-in-face
> translate all supported languages

- components/d2l-activity-editor/d2l-activity-score-editor.js
- components/d2l-activity-editor/lang/en.js
https://trello.com/c/nAaGwBhT/105-update-menu-and-dialog-text-to-edit-grades-link
> Change langterm 'Edit Grade Item Link' to 'Edit Grades Link'

- components/d2l-activity-editor/d2l-activity-availability-dates-editor.js
- components/d2l-activity-editor/state/activity-usage.js
- test/d2l-activity-editor/d2l-activity-availability-dates-editor.html
- test/d2l-activity-editor/d2l-activity-availability-dates-editor.js
- test/d2l-activity-editor/state/activity-usage.spec.js
- test/index.html
- add start and end date properties and methods to the activity-usage mobx store
- convert editor to use store
- add editor ui and store tests
> Convert availability-dates-editor to save/cancel

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
- components/d2l-activity-editor/mixins/d2l-activity-editor-container-mixin.js
~Add `returnUrl` to the assignment editor (which is set as an attribute by the renderer in the LMS), and follow that URL on save.~
Fire event after validations and saves have completed successfully. This event will be handled on the main page (in the LMS), and the user redirected to the previous page.
> US113169 Implement save-and-close pattern

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-anonymous-marking-editor.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-anonymous-marking-summary.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment-store.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.js
- test/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.spec.js
[US114431](https://rally1.rallydev.com/#/detail/userstory/375347576500?fdp=true)
This PR makes anonymous marking mobx.
Relies on [siren-sdk ➡](https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/151)
> US114431 Add anonymous marking mobx

- .travis.yml
Doing this temporarily so I get emails for all the failures. This is to gain some insight into why the vdiff tests are failing sometimes. Not sure if you want to add yourself as well @cbusmand2l
> Register for email notifications from travis

- package.json
We don't use this library so lets remove it.  Ran a build + tests and everything seems fine.
Closes #756
> Removing the async library

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
- components/d2l-activity-editor/d2l-activity-score-editor.js
- components/d2l-activity-editor/lang/en.js
> Add radio btns to 'Choose From Grades' Dialog and show Name/Pts under 'Create New and link' option

- components/d2l-activity-editor/d2l-activity-grades-dialog.js
- components/d2l-activity-editor/d2l-activity-score-editor.js
- components/d2l-activity-editor/state/activity-score-grade.js
Move d2l-dialog for grades to its own component
> Refactor dialog to its own component

- package.json
- test/d2l-activity-card/d2l-activity-card-test.js
- test/d2l-activity-list-item/d2l-activity-list-item-test.js
- test/d2l-quick-eval/behaviors/d2l-quick-eval-telemetry-behavior.js
- test/d2l-quick-eval/d2l-quick-eval-logging.html
- test/d2l-quick-eval/d2l-quick-eval-view-toggle.js
Upgraded sinon to version 9.0.1
Updated some of the tests that were failing due to `sinon.sandbox.create` being deprecated (https://github.com/sinonjs/sinon/blob/master/CHANGELOG.md#800--2019-12-22)
Closes #759
> Upgrade sinon to 9.0.1

- README.md
[![Dependabot Status](https://api.dependabot.com/badges/status?host=github&repo=BrightspaceHypermediaComponents/activities)](https://dependabot.com) [![Build status](https://travis-ci.com/brightspaceHypermediaComponents/activities.svg?branch=master)](https://travis-ci.com/brightspaceHypermediaComponents/activities)
> Added dependabot + build status badges to the README

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-availability-editor.js
- components/d2l-activity-editor/d2l-activity-conditions-editor.js
- components/d2l-activity-editor/d2l-activity-conditions-summary.js
- components/d2l-activity-editor/d2l-activity-usage-conditions-summary.js
- components/d2l-activity-editor/lang/en.js
- components/d2l-activity-editor/state/conditions.js
[US114762](https://rally1.rallydev.com/#/detail/userstory/376876593184?fdp=true)
This PR adds the summarizer for RCs, fixes the create new dialog size, and removes the HTML filtering for condition text.
> US114762 Summarizer text for rcs

- components/d2l-activity-editor/mixins/d2l-activity-editor-container-mixin.js
also see: https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/9697/overview
> Toast message should only appear on FACE Save

- components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
- components/d2l-activity-collection-editor/lang/en.js
[Rally](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?qdp=%2Fdetail%2Fdefect%2F363027686564)
After fix
> added search placeholder

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-evaluation-editor.js
- components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-summary-wrapper.js
- components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-summary.js
- components/d2l-activity-editor/d2l-activity-rubrics/lang/en.js
- components/d2l-activity-editor/d2l-activity-rubrics/state/association-collection.js
- components/d2l-activity-editor/state/activity-usage.js
- test/d2l-activity-editor/state/activity-usage.spec.js
Adding rubric summary to the evaluation accordion.
> Add rubric summary

- components/d2l-activity-editor/lang/en.js
It is only being used in one place right now.
> Change 'Ok' to 'OK'

- components/d2l-activity-editor/lang/en.js
**Trello 1**
Existing Langterm:
- No existing Grade Items exist to be linked
New Langterm:
- No existing grade items
**Trello 2**
Current Langterms:
- Create and link to New Grade Item
- Link to Existing Grade Item
Desired Langterms:
- Create and link to a new grade item
- Link to an existing grade item
> Update "No existing grade items" langterm

- components/d2l-activity-editor/d2l-activity-assignment-editor/activity-summarizer-styles.js
Styles ware being applied in a different order on Edge only:
https://trello.com/c/reauWSPn/146-edge-odd-rhp-styling
> Fix styling for old Edge

- components/d2l-activity-editor/lang/en.js
[DE37696](https://rally1.rallydev.com/#/357252966636d/detail/defect/366397534648?fdp=true)
> change to learners from student

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
- components/d2l-activity-editor/d2l-activity-attachments/state/attachment-store.js
- doesn't currently name the attachment based on the URL (that will come in the next commits)
> detect URLs in Instructions field and add as attachment in FACE assignmnts

- components/d2l-activity-editor/d2l-activity-grades-dialog.js
- components/d2l-activity-editor/d2l-activity-grades/state/grade-candidate-collection.js
- components/d2l-activity-editor/state/activity-score-grade.js
- components/d2l-activity-editor/state/activity-usage.js
Gets the save action from the currently selected entity, and passes it into the data for the save.
Tests are coming.
> US113746 Call action to associate new grade with a category on assignment save

- components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-editor.js
- components/d2l-activity-editor/d2l-activity-rubrics/state/association-collection.js
Adding dirty and hasPendingChanges functions to work with the unsaved changes dialog to rubrics.
> DE38665 - Unsaved rubrics changes

- components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachment.js
https://rally1.rallydev.com/#/29180338367d/detail/defect/385346465792?fdp=true
> setting attributes as property by prefacing with dot

- components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-container.js
https://rally1.rallydev.com/#/29180338367d/detail/userstory/389246630868?fdp=true
> add rubric button margin alignment

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-evaluation-editor.js
https://rally1.rallydev.com/#/29180338367d/detail/userstory/389703962996
> rubrics summary text order adjustment

- components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-container.js
- components/d2l-activity-editor/d2l-activity-rubrics/lang/en.js
[DE38864](https://rally1.rallydev.com/#/110294864140d/detail/defect/388166279620)
> DE38864: adding alt text to overlay close button

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-annotations-editor.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-evaluation-editor.js
- components/d2l-activity-editor/d2l-activity-competencies-summary.js
- components/d2l-activity-editor/d2l-activity-competencies.js
- components/d2l-activity-editor/lang/en.js
- components/d2l-activity-editor/state/activity-usage.js
- test/d2l-activity-editor/state/activity-usage.spec.js
Relies on https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/187
> US115945 Render number of unevaluated competencies in evaluation accordion

- components/d2l-activity-editor/d2l-activity-competencies.js
- components/d2l-activity-editor/lang/en.js
> Adjust competencies summary langterms

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-assignment-turnitin-editor.js
- components/d2l-activity-editor/d2l-activity-competencies.js
Wire up abort handler for competencies dialog, tweak styles
> Competencies trello fixes

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
- components/d2l-activity-editor/mixins/d2l-activity-editor-container-mixin.js
For [DE39076](https://rally1.rallydev.com/#/110294864140d/detail/defect/391026725736)
> Replaced d2l-dialog for discard changes with d2l-dialog-confirm

- components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-editor.js
If the association is added but not yet saved, show the remove button
> Show the remove button for associations that are pending

- components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachment.js
https://rally1.rallydev.com/#/29180338367d/detail/defect/394007210116
> DE39229 - don't pass undefined baseHref

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
https://trello.com/c/Iyfj51MC/201-remove-auto-save-indicator-appears-when-auto-saving-rubrics
> remove auto save indicator from footer

- components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachment.js
(cherry picked from commit 8c1079f50d85ae3dea0a1c9454ccb9c84491b222)
https://rally1.rallydev.com/#/29180338367d/detail/defect/394066580792
> [Cert DE39245] - don't pass undefined baseHref

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
- components/d2l-activity-editor/d2l-activity-editor-buttons.js
- components/d2l-activity-editor/lang/en.js
https://rally1.rallydev.com/#/29180338367d/detail/userstory/391262573396
https://rally1.rallydev.com/#/29180338367d/detail/userstory/391495449276
> US116632 US116585 Shorten save button text and fix due date picker spacing in mobile

- components/d2l-activity-editor/d2l-activity-html-editor.js
> DE39243 Cert 20.20.6: Fix orgUnitId resolution for embedded iframes in HTML editor

- components/d2l-activity-editor/d2l-activity-editor-buttons.js
- components/d2l-activity-editor/d2l-activity-visibility-editor-toggle.js
https://rally1.rallydev.com/#/29180338367d/detail/userstory/388899934252?fdp=true
> visibility toggle text removed in mobile view

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
- components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-editor.js
https://trello.com/c/ckeakpjS/196-mobile-reduce-space-between-attachment-bar-and-secondary-panel
> remove extra bottom padding

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-footer.js
- components/d2l-activity-editor/d2l-activity-editor-buttons.js
https://rally1.rallydev.com/#/29180338367d/detail/userstory/388899934252?fdp=true
> position footer buttons to be all on one line in mobile

- components/d2l-activity-editor/lang/en.js
https://trello.com/c/hoWo1ePM/206-update-lang-term-in-competencies-to-ensure-alignment-w-assessment
> update competencies summary langerm

- components/d2l-activity-editor/d2l-activity-outcomes.js
https://rally1.rallydev.com/#/29180338367d/detail/userstory/389962037972
> US116429 - only show direct alignments

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-evaluation-editor.js
https://trello.com/c/7Z8dtPG8/207-ld-flag-turning-off-m2-flag-with-some-m3-feature-flags-on-wont-hide-all-m2-features
> M2 features in the evaluation accordion should check M2 flag

- components/d2l-activity-editor/lang/ar.js
- components/d2l-activity-editor/lang/da-dk.js
- components/d2l-activity-editor/lang/de.js
- components/d2l-activity-editor/lang/es.js
- components/d2l-activity-editor/lang/fr.js
- components/d2l-activity-editor/lang/ja.js
- components/d2l-activity-editor/lang/ko.js
- components/d2l-activity-editor/lang/nl.js
- components/d2l-activity-editor/lang/pt.js
- components/d2l-activity-editor/lang/sv.js
- components/d2l-activity-editor/lang/tr.js
- components/d2l-activity-editor/lang/zh-tw.js
- components/d2l-activity-editor/lang/zh.js
> DE39499 Cert 20.20.7: Translation updates

- components/d2l-activity-editor/d2l-activity-editor.js
https://rally1.rallydev.com/#/29180338367d/detail/defect/398651793780?fdp=true
> add delay-transition to d2l-backdrop to introduce delay before fade starts

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-availability-editor.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/lang/en.js
- components/d2l-activity-editor/d2l-activity-special-access-editor.js
- components/d2l-activity-editor/lang/en.js
- components/d2l-activity-editor/state/activity-special-access.js
- components/d2l-activity-editor/state/activity-usage.js
- test/d2l-activity-editor/state/activity-special-access.spec.js
- test/d2l-activity-editor/state/activity-usage.spec.js
https://rally1.rallydev.com/#/29180338367d/detail/userstory/397387989372
> US117523 - Render Special Access in right-hand panel

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-evaluation-editor.js
https://rally1.rallydev.com/#/29180338367d/detail/defect/400539899736?fdp=true
> evaluation and feedback summary order correction

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-availability-editor.js
- components/d2l-activity-editor/d2l-activity-special-access-summary.js
- components/d2l-activity-editor/lang/en.js
https://rally1.rallydev.com/#/29180338367d/detail/userstory/397387995716?fdp=true
> Special access summary text

- components/d2l-activity-editor/lang/en.js
@kieranderson  will this make yours angry?
> updating RC summary text to be lower case

- components/d2l-activity-editor/d2l-activity-grades-dialog.js
Trello: https://trello.com/c/zAZFhBPK/157-face-choose-from-grades-dialog-sizing
> Choose from grades dialog width changed to 460px

- components/d2l-activity-editor/d2l-activity-grades-dialog.js
- components/d2l-activity-editor/d2l-activity-score-editor.js
- components/d2l-activity-editor/lang/en.js
- components/d2l-activity-editor/state/activity-dates.js
Cert for #983 and #987 
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fdefect%2F405070209580
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fdefect%2F406343628716
> DE39807 DE39837 Cert 20.20.8: Fix activity editor langterm keys

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-availability-editor.js
https://trello.com/c/juhodlB6/218-special-access-double-chin
> Fix double chin at bottom of FACE availability accordion

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
- components/d2l-activity-editor/mixins/d2l-activity-editor-features-mixin.js
Using specific feature flag in M4, here is the PR to add email on submission LD flag.
> Create m4 email submission LD flag

- components/d2l-activity-editor/d2l-activity-special-access-editor.js
- components/d2l-activity-editor/d2l-activity-special-access-summary.js
- components/d2l-activity-editor/lang/en.js
https://trello.com/c/f1MWoT8o/227-no-users-w-special-access
> Tweak special access description and summary for special case

- components/d2l-activity-collection-editor/d2l-activity-collection-editor.js
- components/d2l-activity-collection-editor/localization.js
Context: 
DE39804 - Fix broken langs for d2l-activity-collection-editor
> DE39804 Fix broken langs

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-annotations-summary.js
Same fix as for master, going to release branch
> DE39920 fix annotation text missing

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-submission-and-completion.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-evaluation-editor.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-type-editor.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/state/assignment.js
Fix read-only view for Assignment Type and Submission Type, Submission File Limit, Submission Rules, and Completion Type fields.
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F399772334476
> US117892 - Part 1 - Fixing assignment read-only view (assignment type, submission & completions options)

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
Fixes https://trello.com/c/D5lrBpvK/239-submission-state-lock-icon-alignment
> align icon to base of text

- components/d2l-activity-editor/d2l-activity-grades-dialog.js
- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grade-category-selector.js
https://trello.com/c/snhdmU2q/158-face-choose-from-grades-radio-button-padding
> paddings and margins

- components/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fdefect%2F408477251884&fdp=true
> remove extra tooltip in FACE attachment icons and make sure NVDA still reads the icons

- components/d2l-activity-editor/d2l-activity-special-access-editor.js
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F406292188564%2Ftasks
> US118695 - Launch fullscreen dialog for special access

- package.json
Changed to pull in changes to this labs component automatically.
> Less specific dependency on list-item-accumulator

- components/d2l-activity-editor/mixins/d2l-activity-editor-mixin.js
Converter function will return the parameter `value` except when `value` is the string `"undefined"` in which case it returns `''`, the empty string.
> US120105 Add converter function to handle 'undefined' href str and return empty "" str

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-footer.js
- components/d2l-activity-editor/mixins/d2l-skeletize-mixin.js
https://rally1.rallydev.com/#/detail/userstory/423713941720?fdp=true
Need some help fixing linting issues my VS Code isn't helping with
> US120106 Implement skeleton re-usable styles and mixin

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-footer.js
Let footer component render normally
> Remove properties method & add constructor; set skeleton=false

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-footer.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-secondary.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor.js
https://rally1.rallydev.com/#/detail/userstory/423713247156?fdp=true
**Resolved: ~~Lint issues causing CI test failures~~**
The ordering rule for imports wants multiple import statements to preceed single import statements but this tends to conflict with the alphabetical imports rule.
> US120104 AsyncContainerMixin

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
- components/d2l-activity-editor/d2l-activity-score-editor.js
- components/d2l-activity-editor/mixins/d2l-skeletize-mixin.js
- test/d2l-activity-editor/d2l-activity-score-editor.js
https://rally1.rallydev.com/#/detail/userstory/423713964032?fdp=true
> US120108 Implement skeleton behavior on score out of

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-footer.js
https://rally1.rallydev.com/#/detail/userstory/423713967192/tasks?fdp=true
Will have to consult Joseph for the design on this as we could skeletize the buttons instead of the whole div:
> US120111 Add d2l-skeletize to footer

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
https://rally1.rallydev.com/#/detail/userstory/423713959428?fdp=true
> US120107 Apply d2l-skeletize to labels; Pass skeleton down to child components

- package.json
[US119539](https://rally1.rallydev.com/#/110294864140d/custom/110851118712?detail=%2Fuserstory%2F414155548564&fdp=true)
version bump to get [this](https://github.com/BrightspaceUI/core/pull/818) change to check the blobs dictionary for a request/response into activities
> version bump core to get changes for oslo

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
- components/d2l-activity-editor/d2l-activity-due-date-editor.js
> fix due date merge error

- components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-container.js
- components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-editor.js
- components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-wrapper.js
https://trello.com/c/dGDD3gBm/8-de40540-cannot-delete-an-added-rubric-clicking-the-x-does-nothing
> [Master] DE40540 - fix cannot remove attached rubric

- components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-container.js
- components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-editor.js
- components/d2l-activity-editor/d2l-activity-rubrics/d2l-activity-rubrics-list-wrapper.js
(cherry picked from commit a459a4c8a49314423c6e3ca4d5ad3fc95a77e71f)
https://rally1.rallydev.com/#/29180338367/dashboard?detail=%2Fdefect%2F435363311116
> [CERT] DE40540 - fix cannot remove attached rubric

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-availability-editor.js
https://rally1.rallydev.com/#/29180338367ud/iterationstatus?detail=%2Fuserstory%2F413481592160&fdp=true
> US119469 add start / end dates to availability dates accordion

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-availability-editor.js
https://rally1.rallydev.com/#/29180338367ud/iterationstatus?detail=%2Fuserstory%2F413481607148&fdp=true
> US119470 add summarizer text for start/end dates

- components/d2l-activity-collection-editor/lang/tr.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/lang/ja.js
- components/d2l-activity-editor/lang/ar.js
- components/d2l-activity-editor/lang/cy-gb.js
- components/d2l-activity-editor/lang/da-dk.js
- components/d2l-activity-editor/lang/de.js
- components/d2l-activity-editor/lang/es-es.js
- components/d2l-activity-editor/lang/es.js
- components/d2l-activity-editor/lang/fr-fr.js
- components/d2l-activity-editor/lang/fr.js
- components/d2l-activity-editor/lang/ja.js
- components/d2l-activity-editor/lang/ko.js
- components/d2l-activity-editor/lang/nl.js
- components/d2l-activity-editor/lang/pt.js
- components/d2l-activity-editor/lang/sv.js
- components/d2l-activity-editor/lang/tr.js
- components/d2l-activity-editor/lang/zh-tw.js
- components/d2l-activity-editor/lang/zh.js
Context: https://github.com/BrightspaceHypermediaComponents/activities/pull/1169
The bots PR had merge conflicts so I resolved them on this branch.
Closes #1169
> Update translations 2011 28/10/2020

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-disable-right-click-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-timing-and-display-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.js
- test/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.spec.js
https://rally1.rallydev.com/#/detail/userstory/438844242444?fdp=true
> US120984 - Quiz Disable Right Click UI

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-disable-right-click-summary.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-timing-and-display-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
https://rally1.rallydev.com/#/detail/userstory/449829054032?fdp=true
> US121856 - Quiz Disable Right Click Summary

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
- components/d2l-activity-editor/d2l-activity-outcomes.js
- components/d2l-activity-editor/state/activity-usage.js
- test/d2l-activity-editor/state/activity-usage.spec.js
Relies on siren-sdk PR https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/229
https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F455318565812%2Ftasks
> Replace flat save-cancel outcomes with autosaving hierarchical outcomes

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-availability-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor-secondary.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-password-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-timing-and-display-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.js
- package.json
- test/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.spec.js
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F456674904728
> US122429 Quiz password ui

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-availability-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-password-summary.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=/userstory/456675108144
> Added password summary component

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-disable-pager-and-alerts-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-timing-and-display-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.js
- test/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.spec.js
[US120986](https://rally1.rallydev.com/#/detail/userstory/438844250288?fdp=true): [ui] Add block alerts checkbox
> US120986 Quizzes: Add block alerts/disable pager and alerts checkbox

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-attempts-and-completion-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-notification-email-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.js
- test/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.spec.js
https://rally1.rallydev.com/#/detail/userstory/438838251528?fdp=true
> US120977 - Add Notification Email field to Quiz

- components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
Rally ticket: https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F455885094408
> Update content editor fonts

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-disable-pager-and-alerts-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-disable-right-click-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-hints-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-prevent-moving-backwards-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-timing-and-display-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.js
- components/d2l-activity-editor/styles/checkbox-styles.js
- test/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.spec.js
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=/userstory/458770937868
> US122653 Quizzing prevent moving backwards

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-prevent-moving-backwards-summary.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-timing-and-display-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.js
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=/userstory/458770939676
> Added prevent moving backwards summary

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-disable-pager-and-alerts-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-shuffle-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-timing-and-display-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.js
- test/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.spec.js
[US122651](https://rally1.rallydev.com/#/detail/userstory/458770910924/tasks?fdp=true): [ui] Shuffle questions
> US122651 Quizzes: shuffle questions

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-timing-and-display-editor.js
> FIX MASTER

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-availability-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
First part of https://rally1.rallydev.com/#/29180338367ud/iterationstatus?detail=%2Fuserstory%2F413484054592&fdp=true
There is no dirty check (also not in Assignments, need to confirm whether one is needed)
Subsequent PR will show read-only version if permission lacking, for both quiz and assignment.
> US119477 add release conditions compoment to quiz

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-shuffle-summary.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-timing-and-display-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.js
[US122652](https://rally1.rallydev.com/#/detail/userstory/458770914576?fdp=true): [ui] Summarizer: Shuffle questions
> US122652 Quizzes: Add summarizer for shuffle questions

- components/d2l-quick-eval/d2l-quick-eval-submissions-table.js
> Remove overflow and truncate long usernames in Quick Eval submission list

- components/d2l-activity-editor/d2l-activity-quiz-divider.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor-detail.js
Small PR to add skeleton styles to the newly created divider component. Original component PR https://github.com/BrightspaceHypermediaComponents/activities/pull/1219
> Added skeleton styles to the quizzing divider

- test/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.spec.js
[US122652](https://rally1.rallydev.com/#/detail/userstory/458770914576?fdp=true): [ui] Summarizer: Shuffle questions
> US122652 Quizzes: Add tests for shuffle

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-availability-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-password-editor.js
https://trello.com/c/H3nokjpI/273-extra-white-space-under-release-conditions-element
> fix: extra whitespace between RC and password

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-availability-editor.js
https://rally1.rallydev.com/#/29180338367ud/iterationstatus?detail=%2Fuserstory%2F413484055008&fdp=true
> US119478 add summarizer for quiz release conditions

- components/d2l-activity-editor/lang/ar.js
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fdefect%2F463038062548&fdp=true
There were some invisible characters within the plural arabic translations that I removed. Tested locally by creating new lang terms with corrected values, but not able to test modified original terms locally, so this will need to be tested after deployment.
> fix: DE41667 remove invisible characters from arabic plural translations

- components/d2l-work-to-do/d2l-work-to-do-activity-list-header.js
- components/d2l-work-to-do/d2l-work-to-do.js
- components/d2l-work-to-do/env/index.js
https://rally1.rallydev.com/#/detail/userstory/422999259560?fdp=true
> Update WorkToDo with Config from LE

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor-detail.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.js
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F458494147960&fdp=true?fdp=true
> US122636 - Delete quiz on cancel

- components/d2l-activity-editor/d2l-activity-usage-conditions-editor.js
- components/d2l-activity-editor/state/conditions.js
[DE41544](https://rally1.rallydev.com/#/110294864140d/dashboard?detail=%2Fdefect%2F460011628812)
> DE41544: Fix release conditions dirty check

- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F461235145752
Updated accessibility text to match user story.
> Updated accessible text to match story

- .github/workflows/prchecklist.yml
Created a PR checklist in activities to remind people to include the semver in the title/merge commit
Based on https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/243
> fix: Create prchecklist.yml

- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
[US123062](https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F461233726748&fdp=true?fdp=true): Rename block alerts field
Updates langterm
> US123062 Quizzes: Rename block alerts field

- components/d2l-activity-editor/d2l-activity-conditions-editor.js
[DE41544](https://rally1.rallydev.com/#/110294864140d/dashboard?detail=%2Fdefect%2F460011628812)
> fix: DE41544 Fix for when dirty check was not checking conditions changes

- test/d2l-activity-editor/d2l-activity-attachments/state/attachment.spec.js
Support handling Audio/Video attachments as links which store URNs
> feat: US123107

- .github/workflows/prchecklist.yml
Not sure if there's a better way to word the reminder as this didn't release: https://github.com/BrightspaceHypermediaComponents/activities/pull/1289
> fix: Semver keyword in PR title doesn't release

- components/d2l-work-to-do/d2l-work-to-do.js
https://rally1.rallydev.com/#/357251704080ud/custom/367300408400?detail=%2Fuserstory%2F459381433584&fdp=true?fdp=true
> View All now redirects to full page view

- components/d2l-work-to-do/d2l-work-to-do.js
https://rally1.rallydev.com/#/357251704080ud/custom/367300408400?detail=%2Fuserstory%2F464048560492&fdp=true
> Filter upcoming and overdue collections based on WTD config

- .github/workflows/ci.yml
- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
- components/d2l-activity-editor/d2l-activity-outcomes.js
- wct.conf.json
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fdefect%2F483998902076
Reverted changes that dispatched an async event to manage loading alignments.
> Revert changes to alignments loading

- components/d2l-work-to-do/lang/en.js
- components/d2l-work-to-do/lang/es.js
- components/d2l-work-to-do/lang/fr.js
- components/d2l-work-to-do/lang/ja.js
- components/d2l-work-to-do/lang/ko.js
- components/d2l-work-to-do/lang/nl.js
- components/d2l-work-to-do/lang/pt.js
- components/d2l-work-to-do/lang/sv.js
- components/d2l-work-to-do/lang/tr.js
- components/d2l-work-to-do/lang/zh-tw.js
- components/d2l-work-to-do/lang/zh.js
See slack thread: https://d2l.slack.com/archives/G0150CJ3SB1/p1610739146017300
> fix: change Back to D2L to say Back to Home instead

- components/d2l-work-to-do/d2l-work-to-do.js
- components/d2l-work-to-do/env/index.js
See https://rally1.rallydev.com/#/357251704080ud/dashboard?detail=%2Fuserstory%2F424735308936 for original rally ticket, and https://d2l.slack.com/archives/G0150CJ3SB1/p1610572621089200 for the thread on us deciding to do 20 for the page number.
> fix: put page size into a constant, separate from MaxWidgetDisplay

- .github/workflows/ci.yml
- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
- components/d2l-activity-editor/d2l-activity-outcomes.js
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=/defect/484000074416
* Revert changes to alignments loading
* Removed saucelabs tests from CI temporarily for hotfix
> fix: Hotfix for assignments skeleton loading due to learning outcomes

- .github/workflows/prchecklist.yml
Make it clearer that it should be the commit title
> Change wording: message->title

- components/d2l-activity-editor/d2l-activity-content-editor/web-link/d2l-activity-content-web-link-url-preview.js
- components/d2l-activity-editor/lang/en.js
> Add Preview Label for weblinks

- components/d2l-work-to-do/d2l-work-to-do.js
https://rally1.rallydev.com/#/357251704080d/custom/367300408400?detail=%2Fuserstory%2F459454738300&fdp=true?fdp=true
> US122757: Use work to do filter action

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-detail.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor-detail.js
Turns out my previous lint fix broke it again. Need to compare undefined var with 'undefined' not 'null'.
> fix: US123716 proper lint fix

- test/d2l-activity-editor/d2l-activity-attachments/d2l-activity-attachments-picker.js
Wait until children render before running tests.
> DE42086 try to fix sauce tests

- components/d2l-activity-editor/d2l-activity-score-editor.js
Cert PR for #1406 
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fdefect%2F486533124656
> Cert: DE42184 Fix score-out-of throwing error on save after save-in-place

- components/d2l-work-to-do/d2l-work-to-do-empty-state-image.js
- components/d2l-work-to-do/d2l-work-to-do.js
- components/d2l-work-to-do/lang/en.js
- components/d2l-work-to-do/lang/es.js
- components/d2l-work-to-do/lang/fr.js
- components/d2l-work-to-do/lang/ja.js
- components/d2l-work-to-do/lang/ko.js
- components/d2l-work-to-do/lang/nl.js
- components/d2l-work-to-do/lang/pt.js
- components/d2l-work-to-do/lang/sv.js
- components/d2l-work-to-do/lang/tr.js
- components/d2l-work-to-do/lang/zh-tw.js
- components/d2l-work-to-do/lang/zh.js
https://rally1.rallydev.com/#/357251704080ud/custom/367300408400?detail=%2Fuserstory%2F483243445644&fdp=true
> W2D: Update empty states

- components/d2l-work-to-do/d2l-work-to-do.js
Update to allow the root entity to be an organization for this PR: https://github.com/Brightspace/lms/pull/5667
https://rally1.rallydev.com/#/357251704080d/custom/367300408400?detail=%2Fuserstory%2F480453371564&fdp=true&fdp=true?fdp=true
> fix: US123834: Allow organization as root entity in w2d widget.

- components/d2l-work-to-do/d2l-work-to-do-activity-list-item-detailed.js
Oversight from https://github.com/BrightspaceHypermediaComponents/activities/pull/1335
> fix: hover state of detailed w2d list items

- components/d2l-work-to-do/d2l-work-to-do-activity-list-item-basic.js
- components/d2l-work-to-do/d2l-work-to-do-activity-list-item-detailed.js
https://rally1.rallydev.com/#/357251704080/custom/367300408400?detail=%2Fdefect%2F482557191752&fdp=true?fdp=true
> Fix d2l-icon border radius in w2d list items

- components/d2l-work-to-do/d2l-work-to-do-activity-list-item-basic.js
- components/d2l-work-to-do/d2l-work-to-do-activity-list-item-detailed.js
- components/d2l-work-to-do/d2l-work-to-do.js
https://rally1.rallydev.com/#/357251704080d/workviews?detail=%2Fdefect%2F464034359184&view=b064b584-6337-43c1-b9a9-28047568284d&fdp=true?fdp=true
https://rally1.rallydev.com/#/357251704080d/custom/367300408400?detail=%2Fdefect%2F483995040488&fdp=true?fdp=true
Render all items only once the item details have been fetched.
> fix: DE41706: Sync item rendering.

- components/d2l-work-to-do/d2l-work-to-do-activity-list-item-detailed.js
https://rally1.rallydev.com/#/357251704080d/custom/367300408400?detail=%2Fdefect%2F486936639864&fdp=true?fdp=true
Added this logic to the basic item, but forgot to add it to the detailed item.
> fix: DE42230: Hide org info for courses in W2D

- components/d2l-work-to-do/d2l-work-to-do.js
https://rally1.rallydev.com/#/357251704080ud/custom/367300408400?detail=%2Fdefect%2F486828986160&fdp=true?fdp=true
> fix: Add retry logic in W2D

- components/d2l-work-to-do/d2l-work-to-do-activity-list-item-basic.js
- components/d2l-work-to-do/d2l-work-to-do-activity-list-item-detailed.js
https://rally1.rallydev.com/#/357251704080ud/workviews?detail=%2Fdefect%2F486935076844&view=b064b584-6337-43c1-b9a9-28047568284d&fdp=true?fdp=true
> fix: Show correct activity icons in W2D

- components/d2l-work-to-do/d2l-work-to-do-activity-list-item-detailed.js
https://rally1.rallydev.com/#/357251704080d/custom/367300408400?detail=%2Fdefect%2F486936639864&fdp=true&fdp=true?fdp=true
> fix: DE42230: Add follow rel path to list-item-detailed

- components/d2l-work-to-do/d2l-work-to-do.js
https://rally1.rallydev.com/#/357251704080ud/custom/367300408400?detail=%2Fuserstory%2F486935048844&fdp=true?fdp=true
> feat: US124298: W2D fetch 1 year in fullscreen.

- components/d2l-activity-editor/d2l-activity-html-new-editor.js
A quick ask from Joseph and Patrick (no trello or story associated)
> fix: increase initial height of new html editor

- components/d2l-work-to-do/d2l-work-to-do.js
https://rally1.rallydev.com/#/357251704080ud/workviews?detail=%2Fuserstory%2F486933827748&view=b064b584-6337-43c1-b9a9-28047568284d&fdp=true?fdp=true
> fix: Update W2D upcomingCollectionCount in full page view

- components/d2l-work-to-do/d2l-work-to-do.js
https://rally1.rallydev.com/#/357251704080ud/workviews?detail=%2Fdefect%2F492733430220&view=b064b584-6337-43c1-b9a9-28047568284d&fdp=true?fdp=true
> fix: Update W2D overdueCount and upcomingCount

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-timing-container.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-timing-and-display-editor.js
Refactored timing dialog to use the ActivityEditorDialogMixin
US123360: [ui] Timing: Render dialog body for Timing Options
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F464625055264&fdp=true?fdp=true
> US123360 refactor timing dialog to use mixin

- components/d2l-activity-editor/d2l-activity-content-editor/d2l-activity-content-editor-detail.js
- components/d2l-activity-editor/d2l-activity-content-editor/lti-link/d2l-activity-content-lti-link-detail.js
- components/d2l-activity-editor/d2l-activity-content-editor/lti-link/state/content-lti-link-store.js
- components/d2l-activity-editor/d2l-activity-content-editor/lti-link/state/content-lti-link.js
- components/d2l-activity-editor/d2l-activity-content-editor/module/d2l-activity-content-module-detail.js
- components/d2l-activity-editor/d2l-activity-content-editor/shared-components/d2l-activity-content-editor-styles.js
- components/d2l-activity-editor/d2l-activity-content-editor/state/content.js
- components/d2l-activity-editor/d2l-activity-content-editor/web-link/d2l-activity-content-web-link-detail.js
- test/d2l-activity-editor/d2l-activity-content-editor/lti-link/d2l-activity-content-lti-link-detail.test.js
- test/d2l-activity-editor/d2l-activity-content-editor/state/content-lti-link.spec.js
- test/d2l-activity-editor/d2l-activity-content-editor/state/content.spec.js
[US124064](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fuserstory%2F483733093636&fdp=true?fdp=true): FACE LTI links - Show Name
Needs [this `siren-sdk` PR](https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/261) merged first
> US124064 Adding LTI link title functionality

- package.json
This will close a few of the open dependabot PRs.
> dep: Remove unused dependencies

- activities.serge.json
Added `d2l-activity-date` lang to serge for translations.
> Added activity date to serge

- components/d2l-work-to-do/d2l-work-to-do-activity-list-item-basic.js
- components/d2l-work-to-do/d2l-work-to-do-activity-list-item-detailed.js
- components/d2l-work-to-do/d2l-work-to-do.js
https://rally1.rallydev.com/#/357251704080ud/workviews?detail=%2Fuserstory%2F459574112788&view=b064b584-6337-43c1-b9a9-28047568284d
Replaced the old code we had to calculate whether or not an activity has started, so now we just look for the `started` class on each activity to determine whether it has started or not
> W2D: use the isStarted property

- activities.serge.json
https://rally1.rallydev.com/#/357251704080/custom/367300408400?detail=%2Fuserstory%2F499651204184&fdp=true?fdp=true
> Add serge config for w2d

- components/d2l-quick-eval-widget/d2l-quick-eval-widget-controller.js
- components/d2l-quick-eval-widget/d2l-quick-eval-widget.js
- components/d2l-work-to-do/d2l-work-to-do-activity-list-item-basic.js
- demo/d2l-quick-eval-widget/data/evaluation-status-assignment.json
- demo/d2l-quick-eval-widget/data/evaluation-status-discussion.json
- demo/d2l-quick-eval-widget/data/evaluation-status-quiz.json
- test/d2l-quick-eval-widget/data/evaluation-status-assignment.json
- test/d2l-quick-eval-widget/data/evaluation-status-discussion.json
- test/d2l-quick-eval-widget/data/evaluation-status-quiz.json
Before: All items linked to 'evaluate all submissions'
Now: Items with > 0 submissions will link to 'evaluate new submissions'
> QE Widget items with new submissions link to evaluate new submissions only

- components/d2l-work-to-do/lang/ar.js
- components/d2l-work-to-do/lang/cy-gb.js
- components/d2l-work-to-do/lang/cy.js
- components/d2l-work-to-do/lang/da.js
- components/d2l-work-to-do/lang/de.js
- components/d2l-work-to-do/lang/es-es.js
- components/d2l-work-to-do/lang/fr-ca.js
- components/d2l-work-to-do/mixins/d2l-work-to-do-localization-mixin.js
https://rally1.rallydev.com/#/357251704080/custom/367300408400?detail=%2Fuserstory%2F499651456572&fdp=true?fdp=true
> W2D: Add missing language files

- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz-timing.js
Support for Timing Type (Recommended/Enforced) radio buttons and SubmissionLateType radio buttons (show/hide extended deadline select box when uselatelimit radio button is selected.)
> US123360 - Support for quiz timing optimistic loading

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-timing-container.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-timing-editor.js
> US123360 - Some minor UI things for quiz timing dialog editor

- components/d2l-activity-editor/d2l-activity-score-editor.js
- components/d2l-activity-editor/lang/en.js
https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fuserstory%2F496651508736&fdp=true
and
https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fuserstory%2F501454060080&fdp=true
> feat: rename grades terms

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-timing-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz-timing.js
> US123360 - add set show clock function

- components/d2l-activity-editor/d2l-activity-grades-dialog.js
- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grade-category-selector.js
https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fuserstory%2F496652209108&fdp=true
> feat: progressively show grade categories

- components/d2l-work-to-do/d2l-work-to-do.js
- components/d2l-work-to-do/lang/ar.js
- components/d2l-work-to-do/lang/cy-gb.js
- components/d2l-work-to-do/lang/cy.js
- components/d2l-work-to-do/lang/da.js
- components/d2l-work-to-do/lang/de.js
- components/d2l-work-to-do/lang/en.js
- components/d2l-work-to-do/lang/es-es.js
- components/d2l-work-to-do/lang/es.js
- components/d2l-work-to-do/lang/fr-ca.js
- components/d2l-work-to-do/lang/fr.js
- components/d2l-work-to-do/lang/ja.js
- components/d2l-work-to-do/lang/ko.js
- components/d2l-work-to-do/lang/nl.js
- components/d2l-work-to-do/lang/pt.js
- components/d2l-work-to-do/lang/sv.js
- components/d2l-work-to-do/lang/tr.js
- components/d2l-work-to-do/lang/zh-tw.js
- components/d2l-work-to-do/lang/zh.js
semi-temporary change until we get OSLO/custom langterms fully working.
https://rally1.rallydev.com/#/357251704080ud/custom/367300408400?detail=%2Fuserstory%2F501907821268
> W2D: replace title "My Work To Do" with "Work To Do"

- components/d2l-work-to-do/d2l-work-to-do.js
- components/d2l-work-to-do/mixins/d2l-work-to-do-localization-mixin.js
see rally story: https://rally1.rallydev.com/#/357251704080ud/workviews?detail=%2Fdefect%2F492471246888&view=b064b584-6337-43c1-b9a9-28047568284d&fdp=true?fdp=true
Followed the steps here: https://docs.dev.d2l/index.php/Oslo but I don't know there's a way to test locally before merging so the LMS can pick up my changes. More context in slack thread: https://d2l.slack.com/archives/C0PHG3QB0/p1613056400089700
> W2D: custom langterm integration

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-timing-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz-timing.js
> US123360 - Quiz Timing read-only view

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-timing-editor.js
> US123360 - stop empty inputs from being processed as valid inputs

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-timing-editor.js
> US123360 - Minor Quiz Timing UI changes

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-timing-container.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-timing-and-display-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-timing-summary.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz-timing.js
- components/d2l-activity-editor/mixins/d2l-activity-editor-working-copy-dialog-mixin.js
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F504705306364%2Ftasks
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fuserstory%2F463925596540%2Ftasks
> US125414, US123281 Add Quiz Timing Summary to Accordion

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-timing-container.js
- components/d2l-activity-editor/mixins/d2l-activity-editor-working-copy-dialog-mixin.js
Trello: https://trello.com/c/FTrDJirs/326-face-quiz-timing-summarizers-dont-update-after-fixing-validation-errors
Associated Rally Story:
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F463925596540&fdp=true?fdp=true
> Fix issue where error state is true even when error is fixed

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor-detail.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/mixins/d2l-activity-quiz-editor-telemetry-mixin.js
- components/d2l-activity-editor/mixins/d2l-activity-editor-telemetry-mixin.js
Part of F16997 retire quiz introduction field
- Send a telemetry event when the intro is merged in FACE quiz
Rally Story:
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F499905664308&fdp=true?fdp=true
> US125094: FACE Quiz - Send Telemetry on Intro Merge

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-timing-editor.js
> Fix time invalid check

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-attempt-conditions-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-attempts-container.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-attempts-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz-attempts.js
Follows Vincent's Timing PR: https://github.com/BrightspaceHypermediaComponents/activities/pull/1603
> FACE Quizzing: Fix Attempts Working Copy dialog 

- components/d2l-activity-editor/d2l-activity-assignment-editor/mixins/d2l-activity-assignment-lang-mixin.js
- components/d2l-activity-editor/mixins/d2l-activity-editor-lang-mixin.js
https://github.com/BrightspaceUI/core/blob/master/mixins/localize-mixin.md
> Update the activity and assignment editor to use the LocalizeDynamicMixin

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-attempts-editor.js
Confused RIO conditions with Attempt Conditions.
> fix: RIO rendering

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-header-footer-container.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-header-footer-editor.js
https://rally1.rallydev.com/#/16349626795d/dashboard?detail=%2Fuserstory%2F482797593636%2Ftasks&fdp=true?fdp=true
> feat:  US123931 Add and Cancel buttons now work.

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-header-footer-container.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-timing-and-display-editor.js
Styling change to header label.   Needed for Water demo.
> fix:  US123931 Styling fix.

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-attempt-conditions-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-attempts-container.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz-attempts.js
[US125799](https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F508497864840&fdp=true?fdp=true): [ui] Attempts: Utilize optimistic updates
> US125799 Quizzes: Attempts utilizes optimistic updates

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-header-footer-editor.js
https://rally1.rallydev.com/#/16349626795d/dashboard?detail=%2Fuserstory%2F482797593636&fdp=true?fdp=true
> fix:  US123931 Fixed to work with HTML editor turned off.

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-attempts-and-completion-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-attempts-summary.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor-secondary.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
[US125895](https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F509112848996&fdp=true?fdp=true): [ui] Accordion summary for attempts
> US125895 Quizzes: [ui] Accordion summary for attempts

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-manage-attempts-container.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz-attempts.js
[US125894](https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F509111919136&fdp=true?fdp=true): [ui] Dialog summary for attempts
> US125894 Quizzes: Attempts dialog summary

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor-detail.js
https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F516914643580&fdp=true?fdp=true
> feat:  US126437 Added alert for when a header is made visible via FACE.

- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.js
- test/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.spec.js
https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F516914643580%2Ftasks&fdp=true?fdp=true
> fix:  US126437 bug fix.  Entity property is now initialized.

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-availability-editor.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-submission-and-completion.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-evaluation-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-attempts-and-completion-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-availability-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-evaluation-and-feedback-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-timing-and-display-editor.js
- components/d2l-activity-editor/styles/accordion-styles.js
- test/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-evaluation-editor.test.js
https://rally1.rallydev.com/#/29180338367/portfolioitemstreegrid?detail=%2Fuserstory%2F509676521676&fdp=true
> US125927 use consistent styling for components within accordions

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-submission-and-completion.js
https://trello.com/c/y6lm7hNG/376-categories-please-make-summary-text-match-open-accordion-field-order
> Changed summarizer order to match component order

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-add-activity-menu.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor-action-bar.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor-detail.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.js
- test/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.spec.js
Accompanying siren-sdk PR: https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/321
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F604399313080
CI will need the siren-sdk changes to pass.
> US128126 Render "Add Existing" and "Create New" drop-down menus

- components/d2l-activity-editor/d2l-activity-content-editor/web-link/state/content-web-link.js
fix: This reverts commit e879c3d487d77276e43f4e6450c2f490af422a28.
> revert: fix: spacing changes just to trigger release for previous fix to saveHref

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-add-activity-menu.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor-action-bar.js
Updates mobile styles to match updated mobile FACE quizzing design:
https://xd.adobe.com/view/0941c89d-9eb5-4a99-a484-bafcacb7e1b1-5c12
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F604399313080
> US128126 "Add Existing/New" quiz menu mobile styling

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-add-activity-menu.js
Launches LMS full-screen dialog when a menu item from the "Add Existing/New" is selected, passing the appropriate `type` value into the url. Handling the "Save" action will be handled in the next story.
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F604399870264
> US128127 Open full-screen dialog for creating new question

- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz.js
https://trello.com/c/nYSQo26o/381-face-quiz-save-and-close-button-is-not-working
> Wrap async mobx prop in runinaction to fix save-and-close error

- components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-file-detail.js
- components/d2l-activity-editor/d2l-activity-content-editor/module/d2l-activity-content-module-detail.js
- components/d2l-activity-editor/d2l-activity-html-new-editor.js
- components/d2l-activity-editor/d2l-activity-text-editor.js
Cert fix of this pr: https://github.com/BrightspaceHypermediaComponents/activities/pull/1734
> [Cert] Default to font families in Content editors

- components/d2l-activity-editor/d2l-activity-content-editor/shared-components/d2l-activity-content-editor-styles.js
[DE43565](https://rally1.rallydev.com/#/289692574792/detail/defect/604746646724)
This reverts commit e879c3d487d77276e43f4e6450c2f490af422a28.
> Revert "revert: fix: spacing changes just to trigger release for previous fix to saveHref"

- components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-file-detail.js
- components/d2l-activity-editor/d2l-activity-html-new-editor.js
Backporting the fixes in https://github.com/BrightspaceHypermediaComponents/activities/pull/1738 and https://github.com/BrightspaceHypermediaComponents/activities/pull/1740
> DE43589 backport undefined html content fix

- components/d2l-activity-editor/d2l-activity-assignment-editor/lang/ar.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/lang/cy.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/lang/da.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/lang/de.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/lang/es-es.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/lang/es.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/lang/fr-fr.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/lang/fr.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/lang/nl.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/lang/pt.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/lang/sv.js
- components/d2l-activity-editor/d2l-activity-assignment-editor/lang/tr.js
- components/d2l-activity-editor/lang/ar.js
- components/d2l-activity-editor/lang/cy.js
- components/d2l-activity-editor/lang/da.js
- components/d2l-activity-editor/lang/de.js
- components/d2l-activity-editor/lang/es-es.js
- components/d2l-activity-editor/lang/es.js
- components/d2l-activity-editor/lang/fr-fr.js
- components/d2l-activity-editor/lang/fr.js
- components/d2l-activity-editor/lang/ja.js
- components/d2l-activity-editor/lang/ko.js
- components/d2l-activity-editor/lang/nl.js
- components/d2l-activity-editor/lang/pt.js
- components/d2l-activity-editor/lang/sv.js
- components/d2l-activity-editor/lang/tr.js
- components/d2l-activity-editor/lang/zh-cn.js
- components/d2l-activity-editor/lang/zh-tw.js
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fdefect%2F605195643028
Merging lang term changes to cert branch that were introduced here: https://github.com/BrightspaceHypermediaComponents/activities/pull/1748
> feat: Translation Updates (#1748)

- components/d2l-activity-editor/d2l-activity-grades-dialog.js
- components/d2l-activity-editor/d2l-activity-score-editor.js
This was branched off your branch Margaret. But I'll be merging this in Master and not your branch. It's just pointing to your branch at the moment so that we can see the change I've made. I won't merge this until your branch is merged into master.
> Don't checkout or fetch checkout entity if selectbox flag is off

- components/d2l-activity-editor/d2l-activity-grades-dialog.js
- components/d2l-activity-editor/d2l-activity-grades/state/grade-candidate-collection.js
- components/d2l-activity-editor/d2l-activity-grades/state/grade-candidate.js
- components/d2l-activity-editor/state/associate-grade.js
- test/d2l-activity-editor/d2l-activity-grades/state/grade-candidate.spec.js
https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fuserstory%2F505558523792&fdp=true
> feat: US125502 add get grade candidate functionality

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-add-activity-menu.js
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F606031728984%2Ftasks&fdp=true?fdp=true
> feat: US128510: add new browse url for OpenFullscreen() to use. 

- .github/workflows/ci.yml
- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grade-category-selector.js
- components/d2l-activity-editor/lang/en.js
- package.json
Change "choose category" button to match design.
Design: https://xd.adobe.com/view/c7be292b-c61a-45c3-960e-ba06ec346f0b-92ed/screen/fc982207-6ad3-4f73-aa34-3befeb0c4bd2/
https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fuserstory%2F505559228552&fdp=true&itemRef=%2Fhierarchicalrequirement%2F505559228552&previousTokens=%2F29180338367ud%2Fcustom%2F486232622040%3Fdetail%3D%252Fuserstory%252F505559228552&project=%2Fproject%2F29180338367&ref=%2Fhierarchicalrequirement%2F505559228552&relationship=tasks
> US125504 change category button to match design

- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grade-candidate-selector.js
- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grades-dialog.js
- components/d2l-activity-editor/state/associate-grade.js
> US125507 - Fetch candidates and categories when dialog opens

- components/d2l-activity-editor/d2l-activity-grades/state/grade-scheme-collection.js
- components/d2l-activity-editor/d2l-activity-grades/state/grade-scheme.js
- components/d2l-activity-editor/state/associate-grade.js
https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fuserstory%2F505558536824&fdp=true&itemRef=%2Fhierarchicalrequirement%2F505558536824&previousTokens=%2F29180338367ud%2Fcustom%2F486232622040%3Fdetail%3D%252Fuserstory%252F505558536824&project=%2Fproject%2F29180338367&ref=%2Fhierarchicalrequirement%2F505558536824&relationship=tasks
> feat: US125503 add schemes functions and objects

- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grade-type-scheme-selector.js
- components/d2l-activity-editor/d2l-activity-grades/state/grade-scheme-collection.js
- components/d2l-activity-editor/d2l-activity-grades/state/grade-scheme.js
- components/d2l-activity-editor/lang/en.js
- components/d2l-activity-editor/state/associate-grade.js
https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fuserstory%2F505558536824&fdp=true
> feat: US125503 add scheme dropdown

- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grade-category-selector.js
> what the heck is a `newGradeCandidatesCollection`, just call it the `gradeCategoryCollection`

- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grade-type-scheme-selector.js
- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grades-dialog.js
- components/d2l-activity-editor/d2l-activity-grades/state/grade-candidate-collection.js
- components/d2l-activity-editor/d2l-activity-grades/state/grade-scheme.js
- components/d2l-activity-editor/state/associate-grade.js
https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F601489857733&fdp=true?fdp=true
> US129035 - fix grades/categories/schemes items being individually fetched

- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grade-type-scheme-selector.js
- components/d2l-activity-editor/d2l-activity-grades/state/grade-scheme.js
- components/d2l-activity-editor/state/associate-grade.js
Use linked scheme entity found in associate-grade entity
https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/351
> Don't refetch schemes entity on select

- components/d2l-activity-editor/d2l-activity-editor.js
https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F600744235069%2Ftasks&fdp=true?fdp=true
> US128779 - Fix Dirty Check

- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grade-type-scheme-selector.js
- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grades-dialog.js
- components/d2l-activity-editor/state/associate-grade.js
https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F600744235069%2Ftasks&fdp=true?fdp=true
> Simplify getGradeSchemes

- components/d2l-activity-editor/state/associate-grade.js
Don't wait for PATCH response before updating UI when changing gradebook status, grade name, or maxPoints.
https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fuserstory%2F600744235069
> fix: some initial ui performance improvements

- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-edit-new-grade.js
- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grades-dialog.js
https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F600744235069%2Ftasks&fdp=true?fdp=true
> Misc dialog height and width and button spacing fixes

- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-edit-new-grade.js
- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grade-category-selector.js
- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grade-type-scheme-selector.js
Task https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Ftask%2F602378484889
from story https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F600744235069%2Ftasks&fdp=true?fdp=true
> US128779 - fix margin between items in grades dialog

- components/d2l-activity-editor/lang/ar.js
- components/d2l-activity-editor/lang/cy.js
- components/d2l-activity-editor/lang/da.js
- components/d2l-activity-editor/lang/de.js
- components/d2l-activity-editor/lang/es-es.js
- components/d2l-activity-editor/lang/es.js
- components/d2l-activity-editor/lang/fr-fr.js
- components/d2l-activity-editor/lang/fr.js
- components/d2l-activity-editor/lang/ja.js
- components/d2l-activity-editor/lang/ko.js
- components/d2l-activity-editor/lang/nl.js
- components/d2l-activity-editor/lang/pt.js
- components/d2l-activity-editor/lang/sv.js
- components/d2l-activity-editor/lang/tr.js
- components/d2l-activity-editor/lang/zh-cn.js
- components/d2l-activity-editor/lang/zh-tw.js
Updating Translations 2107 25/06/2021
Backporting #1845
> Backporting 20.21.7 translations

- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grade-candidate-selector.js
- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grade-category-selector.js
- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grade-type-scheme-selector.js
- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grades-dialog.js
Tasks
https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Ftask%2F602375612375
https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Ftask%2F600744236473
from story https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F600744235069&fdp=true?fdp=true
> US128779 - More CSS adjustments!

- components/d2l-activity-editor/lang/fr-on.js
Updating Translations 2107 fr-on FRAs 29/06/2021
PR to master: https://github.com/BrightspaceHypermediaComponents/activities/pull/1855, https://github.com/BrightspaceHypermediaComponents/activities/pull/1856
https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fdefect%2F602874398299&fdp=true?fdp=true
> Backporting 20.21.7 fr-on translations

- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grades-dialog.js
- components/d2l-activity-editor/d2l-activity-score-editor.js
- components/d2l-activity-editor/mixins/d2l-activity-editor-dialog-mixin.js
- components/d2l-activity-editor/mixins/d2l-activity-editor-working-copy-dialog-mixin.js
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F600744235069&expandApp=486232622048&fdp=true?fdp=true
> US128779 - Fix dialog closing prematurely before save is complete

- components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-file-detail.js
- components/d2l-activity-editor/lang/en.js
Co-authored with @quinnbudan 
- [US127820](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F602981068972&fdp=true?fdp=true): FACE HTML file - Support Template Selection - Handle the case when the API returns 0 templates
This PR handles the case when no HTML templates are returned.
This PR handles the case when no HTML templates are returned. The solution is to show a small message in the dropdown and support screen readers.
N/A
> US127820 - no html templates available

- components/d2l-activity-editor/lang/en.js
Removing a duplicate langterm causing OSLO to fail.
> Removed duplicate langterm

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-ip-restrictions-container.js
https://trello.com/c/m9h6gil0/348-ip-restrictions-add-cancel-button-padding-is-inconsistent-from-other-face-quiz-dialogs
> Fix spacing on ip restrictions footer buttons

- components/d2l-activity-editor/state/activity-usage.js
- components/d2l-activity-editor/state/working-copy.js
Merging this into your branch Margaret
> Move code to update associateGradeHref to activity-usage MobX

- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grade-category-selector.js
- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grade-type-scheme-selector.js
- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grades-dialog.js
https://rally1.rallydev.com/#/10235005524d/dashboard?detail=%2Fuserstory%2F600744235069&fdp=true?fdp=true
> US128779 - Modify padding to specs

- .github/workflows/ci.yml
Backport PRs created by the bot do not have CI triggered when marked as ready to review
* Updated CI workflow to include more types as a trigger
https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F603436954475%2Ftasks&fdp=true?fdp=true
> US129748 Included more PR types for the CI workflow

- components/d2l-activity-editor/lang/fr-on.js
Master PR:
https://github.com/BrightspaceHypermediaComponents/activities/pull/1919
> DE44687 [hotfix] Activities > Add in fr-ON translations for HTML template selection

- components/d2l-activity-editor/d2l-activity-assignment-editor/lang/en.js
https://rally1.rallydev.com/#/42960320374d/dashboard?detail=%2Fuserstory%2F606111825419
> fix: US130754 - updated wording for custom allowable filetypes text box

- components/d2l-activity-editor/d2l-activity-assignment-editor/d2l-activity-assignment-editor-submission-and-completion.js
> Updating restrict file extensions help documentation link

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-retake-incorrect-only-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
[US131489](https://rally1.rallydev.com/#/?detail=/userstory/608664369071&fdp=true): Update RIO help pop-up wording
Updated UI: Screenshot shown here:
> feat: US131489 Update RIO help pop up wording

- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
Rally Stor US127895: 
https://rally1.rallydev.com/#/?detail=/userstory/603281741384&fdp=true
> US127895 updated disableRightClickHelpDialogParagraph2

- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grades-dialog.js
- components/d2l-activity-editor/d2l-activity-score-editor.js
- components/d2l-activity-editor/state/scoring.js
https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fuserstory%2F608101223185&fdp=true
> fix: dirty check score-out-of changes

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor-action-bar.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor-detail.js
- components/d2l-activity-editor/d2l-activity-score-editor.js
- components/d2l-activity-editor/state/scoring.js
https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fuserstory%2F606249971567&fdp=true
> feat: US130775 add allow ungraded, and use gradeMaxPoints when present

- components/d2l-activity-editor/d2l-activity-content-editor/scorm/d2l-activity-content-scorm-activity-detail.js
Quick commit to add missing `semver` keyword
> fix: Get SCORM info from content service

- components/d2l-activity-editor/d2l-activity-grades/d2l-activity-grades-dialog.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-editor-action-bar.js
- components/d2l-activity-editor/d2l-activity-score-editor.js
- components/d2l-activity-editor/state/scoring.js
https://rally1.rallydev.com/#/29180338367ud/custom/486232622040?detail=%2Fuserstory%2F606249971567&fdp=true
> fix: US130775 use gradeMaxPoints for GradeOutOf value

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-submission-views-container.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-submission-views-editor.js
So that it matches timing, attempts, iprestrictions file naming format
> Rename submission-views-dialog to be submission-views-editor

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-submission-view-release-description.js
https://rally1.rallydev.com/#/?detail=/userstory/610534920471&fdp=true
> US132399 - Fix release date time limit description

- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz-submission-view.js
- test/d2l-activity-editor/d2l-activity-quiz-editor/state/activity-submission-view.spec.js
https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fuserstory%2F611715477831
> US132834  - Get attemptRestrictions options

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-submission-views-container.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-submission-views-dialog-card.js
https://rally1.rallydev.com/#/?detail=/userstory/610534919425&fdp=true
> US132397 - Save edit card and save when dialog closes 

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-submission-views-dialog-card.js
https://rally1.rallydev.com/#/?detail=/userstory/611712819337&fdp=true
> US132829 - Hook up Delete View button on card in dialog

- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F611076824093
> Adjusted email notification langterm

- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fuserstory%2F611076835079
> Adjusted right click langterms

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-submission-views-dialog-card-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-submission-views-dialog-card.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz-submission-view.js
- test/d2l-activity-editor/d2l-activity-quiz-editor/state/activity-submission-view.spec.js
https://rally1.rallydev.com/#/?detail=/userstory/610534913293&fdp=true
> Fix submission view to get both html and text message properties

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-sync-gradebook-editor.js
Getting this console error occasionally because it's trying to read property of undefined:
> fix: US129509 read property of undefined

- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz-submission-view.js
- test/d2l-activity-editor/d2l-activity-quiz-editor/state/activity-submission-view.spec.js
https://rally1.rallydev.com/#/?detail=/userstory/613849027377&fdp=true
> US133503 - check for ip-restrictions sub-entity

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-evaluation-and-feedback-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-sync-gradebook-summary.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
https://rally1.rallydev.com/#/?detail=/userstory/602632659569&fdp=true
> feat: US129510 add sync to gradebook summary

- components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-media-file-detail.js
- components/d2l-activity-editor/d2l-activity-content-editor/content-file/state/content-file.js
- package.json
https://rally1.rallydev.com/#/?detail=/userstory/609662239823&fdp=true
siren-sdk: https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/420
LMS: [WIP PR](https://github.com/Brightspace/lms/compare/nabrown/TA158697-audio-video-hm-properties...dacho/nabrown/TA158697-audio-video-hm-properties?expand=1)
--- 
Opens up this dialog:
> Add Producer for Content Service video/audio objects

- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-submission-views-add-additional-view.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-submission-views-dialog-card.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/d2l-activity-quiz-submission-views-editor.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/lang/en.js
- components/d2l-activity-editor/d2l-activity-quiz-editor/state/quiz-submission-views.js
https://rally1.rallydev.com/#/?detail=/userstory/610534917433&fdp=true
> US132396 - Add additional view

- components/d2l-activity-editor/d2l-activity-content-editor/content-file/d2l-activity-content-media-file-detail.js
This pr does the work to actually show the captions within the media file, if present.
> Display captions on media files FACE page
